import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createAcademicResultsService } from '../src/academic-results.js';
import { createAttendanceService } from '../src/attendance.js';
import { createStaffService } from '../src/staff.js';
import { createStudentService } from '../src/students.js';
import { createSubjectService } from '../src/subjects.js';
import { createAcademicAttendanceIntelligence, createAcademicAttendanceTools, createAIDataQualityGuard, createProductionDataGuard } from '../src/ai/index.js';

const now = () => '2026-09-04T12:00:00.000Z';
const manager = (overrides = {}) => ({ id: 'head', userId: 'head', schoolId: 'school-osaah-daylight', roleKey: 'HEADTEACHER', permissions: new Set(['academics.read', 'attendance.read', 'results.read', 'marks.write']), assignedClassIds: [], assignedSubjectIds: [], ...overrides });
function setup({ academicResults: suppliedAcademic, attendance: suppliedAttendance, explain, includeSubjects = false } = {}) { const students = createStudentService({ now }); const subjects = createSubjectService({ now }); const attendance = suppliedAttendance ?? createAttendanceService({ now }); const staff = createStaffService({ now }); const academicResults = suppliedAcademic ?? createAcademicResultsService({ now, students, subjects }); const service = createAcademicAttendanceIntelligence({ academicResults, attendance, students, subjects: includeSubjects ? subjects : null, staff, productionDataGuard: createProductionDataGuard({ environment: 'production', clock: now }), dataQualityGuard: createAIDataQualityGuard({ clock: now }), now, explain }); return { service, students, subjects, attendance, staff, academicResults }; }
function addStudent(system, name, classId = 'Primary 4') { return system.students.createStudent({ firstName: name, surname: 'Student', classId }); }
function score(system, student, total, actor = manager(), extra = {}) { const subject = system.subjects.list({ classId: student.classId }, actor)[0]; return system.academicResults.saveScore({ studentId: student.id, classId: student.classId, subjectId: subject.id, academicYear: '2026', term: 'T1', caScore: total / 2, examScore: total / 2, ...extra }, actor); }

test('deterministic Academic and Attendance Intelligence', async (t) => {
  await t.test('includes production scores and calculates verified academic metrics', async () => { const system = setup(); const a = addStudent(system, 'Ama'), b = addStudent(system, 'Kojo'); score(system, a, 80); score(system, b, 60); const result = await system.service.academicSnapshot({ actor: manager(), academicYear: '2026', term: 'T1', classId: 'Primary 4' }); assert.equal(result.metrics.classAverage, 70); assert.equal(result.metrics.highestVerifiedScore, 80); assert.equal(result.metrics.lowestVerifiedScore, 60); });
  await t.test('excludes TEST scores through Production Data Guard', async () => { const base = setup(); const student = addStudent(base, 'Ama'); const valid = score(base, student, 70); valid.provenance = 'TEST'; const academicResults = { listScores: () => [valid] }; const system = setup({ academicResults }); addStudent(system, 'Ama'); const result = await system.service.academicSnapshot({ actor: manager(), academicYear: '2026', term: 'T1' }); assert.equal(result.metrics.scoreCount, 0); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('treats missing scores as missing rather than zero and marks quality PARTIAL', async () => { const system = setup({ includeSubjects: true }); const student = addStudent(system, 'Ama'); score(system, student, 80); const result = await system.service.academicSnapshot({ actor: manager(), academicYear: '2026', term: 'T1', classId: 'Primary 4' }); assert.equal(result.metrics.classAverage, 80); assert.ok(result.metrics.missingScoreCount > 0); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('does not change official grades or positions', async () => { const system = setup(); const student = addStudent(system, 'Ama'); score(system, student, 82); const filters = { studentId: student.id, classId: student.classId, academicYear: '2026', term: 'T1' }; const before = system.academicResults.result(filters, manager()); await system.service.academicSnapshot({ actor: manager(), ...filters }); const after = system.academicResults.result(filters, manager()); assert.deepEqual(after, before); });
  await t.test('keeps teacher access within assigned classes', async () => { const system = setup(); const teacher = manager({ id: 'teacher', roleKey: 'TEACHER', assignedClassIds: ['Primary 4'], permissions: new Set(['academics.read', 'attendance.read', 'results.read']) }); await assert.rejects(() => system.service.academicSnapshot({ actor: teacher, classId: 'JHS 1' }), (error) => error.code === 'SCOPE_DENIED'); });
  await t.test('preserves present, absent, tardy, and excused attendance meanings', async () => { const system = setup(); for (const [index, status] of ['PRESENT', 'ABSENT', 'LATE', 'EXCUSED_ABSENCE'].entries()) { const student = addStudent(system, `S${index}`); system.attendance.saveStudentAttendance({ date: '2026-09-04', classId: 'Primary 4', studentId: student.id, status }, { userId: 'teacher' }); } const result = await system.service.attendanceSnapshot({ actor: manager(), date: '2026-09-04', classId: 'Primary 4' }); assert.deepEqual({ present: result.metrics.present, absent: result.metrics.absent, tardy: result.metrics.tardy, excused: result.metrics.excused }, { present: 1, absent: 1, tardy: 1, excused: 1 }); assert.equal(result.metrics.attendancePercentage, 50); });
  await t.test('does not turn missing attendance submissions into absences', async () => { const system = setup(); const a = addStudent(system, 'Ama'); addStudent(system, 'Kojo'); system.attendance.saveStudentAttendance({ date: '2026-09-04', classId: 'Primary 4', studentId: a.id, status: 'PRESENT' }, { userId: 'teacher' }); const result = await system.service.attendanceSnapshot({ actor: manager(), date: '2026-09-04', classId: 'Primary 4' }); assert.equal(result.metrics.absent, 0); assert.equal(result.metrics.missingSubmissions, 1); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('excludes TEST attendance', async () => { const record = { id: 'test', schoolId: 'school-osaah-daylight', provenance: 'TEST', date: '2026-09-04', classId: 'Primary 4', studentId: 's', status: 'ABSENT', updatedAt: now() }; const attendance = { listStudentRecords: () => [record], listStaffRecords: () => [] }; const system = setup({ attendance }); addStudent(system, 'Ama'); const result = await system.service.attendanceSnapshot({ actor: manager(), date: '2026-09-04', classId: 'Primary 4' }); assert.equal(result.metrics.absent, 0); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('reports approved staff leave separately from absence', async () => { const system = setup(); const leave = system.staff.applyLeave({ staffId: 'staff-1', leaveType: 'ANNUAL', startsOn: '2026-09-01', endsOn: '2026-09-05' }); system.staff.decideLeave(leave.id, 'APPROVED', { userId: 'head' }); const result = await system.service.attendanceSnapshot({ actor: manager(), date: '2026-09-04' }); assert.equal(result.metrics.staff.approvedLeave, 1); assert.equal(result.metrics.staff.absent, 0); });
  await t.test('requires independent authorization for combined analysis and avoids causation', async () => { const system = setup(); const student = addStudent(system, 'Ama'); score(system, student, 40); system.attendance.saveStudentAttendance({ date: '2026-09-04', classId: 'Primary 4', studentId: student.id, status: 'ABSENT' }, { userId: 'teacher' }); const combined = await system.service.combined({ actor: manager(), academicYear: '2026', term: 'T1', date: '2026-09-04', classId: 'Primary 4' }); assert.ok(combined.indicators.includes('ACADEMIC_REVIEW_RECOMMENDED')); assert.match(combined.statement, /do not establish causation/); await assert.rejects(() => system.service.combined({ actor: manager({ permissions: new Set(['academics.read', 'results.read']) }) }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('compares academic and attendance periods deterministically', async () => { const system = setup(); const student = addStudent(system, 'Ama'); score(system, student, 60, manager(), { term: 'T1' }); score(system, student, 80, manager(), { term: 'T2' }); system.attendance.saveStudentAttendance({ date: '2026-09-03', classId: 'Primary 4', studentId: student.id, status: 'ABSENT' }, { userId: 'teacher' }); system.attendance.saveStudentAttendance({ date: '2026-09-04', classId: 'Primary 4', studentId: student.id, status: 'PRESENT' }, { userId: 'teacher' }); assert.equal((await system.service.compareAcademic({ actor: manager(), classId: 'Primary 4', periods: [{ academicYear: '2026', term: 'T1' }, { academicYear: '2026', term: 'T2' }] })).change, 20); assert.equal((await system.service.compareAttendance({ actor: manager(), classId: 'Primary 4', periods: [{ date: '2026-09-03' }, { date: '2026-09-04' }] })).change, 100); });
  await t.test('AI cannot modify scores or attendance and provider outage preserves metrics', async () => { const system = setup({ explain: async () => { throw new Error('offline'); } }); const student = addStudent(system, 'Ama'); const saved = score(system, student, 72); const beforeAttendance = system.attendance.counts(); const result = await system.service.dashboard({ actor: manager(), academicYear: '2026', term: 'T1' }); assert.equal(result.explanation, null); assert.equal(result.academic.metrics.classAverage, 72); assert.equal(system.academicResults.listScores({}, manager())[0].totalScore, saved.totalScore); assert.deepEqual(system.attendance.counts(), beforeAttendance); });
  await t.test('result comments remain non-published AI drafts requiring human approval', () => { const system = setup(); const draft = system.service.draftResultComment({ actor: manager(), studentId: 's1', text: 'Shows steady progress.' }); assert.equal(draft.status, 'DRAFT'); assert.equal(draft.published, false); assert.equal(draft.requiresHumanApproval, true); assert.equal(draft.approvedBy, null); });
  await t.test('registers production-only Academic and Attendance READ/ANALYZE tools and safe dashboard UI', async () => { const system = setup(); const tools = createAcademicAttendanceTools(system.service); assert.ok(tools.every((tool) => tool.productionDataOnly && ['READ', 'ANALYZE'].includes(tool.operationType))); const ui = await readFile(new URL('../public/academic-attendance-intelligence.js', import.meta.url), 'utf8'); assert.match(ui, /data\.academic/); assert.match(ui, /verified academic and attendance metrics remain visible/); assert.doesNotMatch(ui, /innerHTML|OpenAI|api[_ -]?key/i); });
});
