import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createAdmissionFormService } from '../src/admission-form.js';
import { createAttendanceService } from '../src/attendance.js';
import { createStaffService } from '../src/staff.js';
import { createAdmissionsWorkforceIntelligence, createAdmissionsWorkforceTools, createAIDataQualityGuard, createProductionDataGuard } from '../src/ai/index.js';

const now = () => '2026-09-04T12:00:00.000Z';
const actor = (roleKey = 'HEADTEACHER', permissions = new Set(['admissions.read', 'staff.read'])) => ({ id: roleKey, schoolId: 'school-osaah-daylight', roleKey, portal: 'school', permissions });
const required = { studentSurname: 'Mensah', studentFirstName: 'Ama', dateOfBirth: '2015-01-01', gender: 'Female', hometown: 'Bogoso', region: 'Western', nationality: 'Ghanaian', classAppliedFor: 'Basic 4', residentialAddress: 'Bogoso', digitalAddress: 'WS-1', nearestLandmark: 'School', primaryGuardianPrimaryPhone: '0240000000', academicYear: '2026', admissionTerm: 'T1' };
function setup(options = {}) { const admissions = options.admissions ?? createAdmissionFormService({ now }); const staff = options.staff ?? createStaffService({ now }); const attendance = createAttendanceService({ now }); const service = createAdmissionsWorkforceIntelligence({ admissions, staff, attendance, productionDataGuard: createProductionDataGuard({ environment: 'production', clock: now }), dataQualityGuard: createAIDataQualityGuard({ clock: now }), now, ...options }); return { admissions, staff, attendance, service }; }
function application(system, input = {}) { return system.admissions.createApplication({ ...required, ...input }, { id: 'parent', portal: 'parent' }); }
function complete(system, app) { system.admissions.updateApplication(app.applicationNumber, { ...required, parentDeclarationAccepted: true }, { id: 'parent', portal: 'parent' }); for (const documentType of ['PASSPORT_PHOTOGRAPHS', 'BIRTH_CERTIFICATE_OR_GHANA_CARD', 'NHIS_CARD', 'LAST_ACADEMIC_REPORT']) system.admissions.attachDocument(app.applicationNumber, { documentType, fileReference: `${documentType}.pdf` }, { id: 'parent', portal: 'parent' }); }

test('deterministic Admissions and Workforce Intelligence', async (t) => {
  await t.test('distinguishes complete and incomplete applications with missing requirements', async () => { const system = setup(); const done = application(system), missing = application(system, { studentFirstName: 'Kojo' }); complete(system, done); const result = await system.service.admissionsSnapshot({ actor: actor() }); assert.equal(result.metrics.completeApplications, 1); assert.equal(result.metrics.incompleteApplications, 1); assert.ok(result.metrics.reviewQueue.find((item) => item.applicationNumber === missing.applicationNumber).missingRequirements.some((item) => item.startsWith('DOCUMENT:'))); });
  await t.test('flags duplicates only for neutral human review', async () => { const system = setup(); application(system); application(system); const result = await system.service.admissionsSnapshot({ actor: actor() }); assert.equal(result.duplicateFlags[0].match, 'EXACT_MATCH'); assert.equal(result.duplicateFlags[0].reviewRequired, true); assert.ok(['EXACT_MATCH', 'STRONG_MATCH', 'POSSIBLE_MATCH'].includes(result.duplicateFlags[0].match)); assert.equal(Object.hasOwn(result.duplicateFlags[0], 'decision'), false); });
  await t.test('does not equate acceptance with enrollment', async () => { const system = setup(); const app = application(system); complete(system, app); system.admissions.submitApplication(app.applicationNumber, { id: 'parent', portal: 'parent' }); system.admissions.reviewApplication(app.applicationNumber, { status: 'ACCEPTED', classAssigned: 'Basic 4', entranceAssessmentScore: 70 }, actor()); let result = await system.service.admissionsSnapshot({ actor: actor() }); assert.equal(result.metrics.offersIssued, 1); assert.equal(result.metrics.enrolled, 0); system.admissions.attachStudent(app.applicationNumber, 'STD-1', actor()); result = await system.service.admissionsSnapshot({ actor: actor() }); assert.equal(result.metrics.enrolled, 1); });
  await t.test('does not invent class capacity', async () => { const result = await setup().service.admissionsSnapshot({ actor: actor() }); assert.equal(result.metrics.classCapacity, null); assert.ok(result.warnings.some((warning) => warning.includes('not configured'))); });
  await t.test('excludes TEST admissions', async () => { const record = { ...application(setup()), provenance: 'TEST' }; const admissions = { listApplications: () => [record], listDocuments: () => [], feeDivisionForClass: () => 'PRIMARY' }; const result = await setup({ admissions }).service.admissionsSnapshot({ actor: actor() }); assert.equal(result.metrics.applications, 0); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('handles active/inactive and teaching/non-teaching staff', async () => { const system = setup(); system.staff.createProfile({ fullName: 'Teacher', roleKey: 'TEACHER', employmentType: 'FULL_TIME', departmentId: 'ACADEMIC', qualification: 'BEd' }); system.staff.createProfile({ fullName: 'Officer', roleKey: 'HR_OFFICER', employmentType: 'FULL_TIME', departmentId: 'ADMIN', qualification: 'BA' }); system.staff.createProfile({ fullName: 'Former', roleKey: 'TEACHER', employmentStatus: 'RESIGNED' }); const result = await system.service.workforceSnapshot({ actor: actor() }); assert.equal(result.metrics.activeStaff, 2); assert.equal(result.metrics.inactiveStaff, 1); assert.equal(result.metrics.teachingStaff, 1); assert.equal(result.metrics.nonTeachingStaff, 1); });
  await t.test('reports configured coverage gaps without inventing requirements', async () => { const descriptive = await setup().service.workforceSnapshot({ actor: actor() }); assert.equal(descriptive.metrics.coverageGaps, null); assert.ok(descriptive.warnings.some((warning) => warning.includes('descriptive only'))); const configured = setup({ coverageRequirements: [{ classId: 'Primary 4', subjectId: 'Math' }] }); assert.equal((await configured.service.workforceSnapshot({ actor: actor() })).metrics.coverageGaps.length, 1); });
  await t.test('includes approved leave and staff attendance summaries', async () => { const system = setup(); const profile = system.staff.createProfile({ fullName: 'Teacher', roleKey: 'TEACHER' }); const leave = system.staff.applyLeave({ staffId: profile.id, leaveType: 'ANNUAL', startsOn: '2026-09-01', endsOn: '2026-09-05' }); system.staff.decideLeave(leave.id, 'APPROVED', { userId: 'head' }); system.attendance.saveStaffAttendance({ staffId: profile.id, date: '2026-09-04', type: 'CHECK_IN' }, { userId: 'head' }); const result = await system.service.workforceSnapshot({ actor: actor() }); assert.equal(result.metrics.approvedLeave, 1); assert.equal(result.metrics.attendance.checkIns, 1); });
  await t.test('reports missing, expiring, and expired documents', async () => { const system = setup(); system.staff.createProfile({ fullName: 'Missing', roleKey: 'TEACHER' }); system.staff.createProfile({ fullName: 'Docs', roleKey: 'TEACHER', documents: [{ expiresOn: '2026-09-20' }, { expiresOn: '2026-08-01' }] }); const result = await system.service.workforceSnapshot({ actor: actor() }); assert.equal(result.metrics.documents.missing, 1); assert.equal(result.metrics.documents.expiring, 1); assert.equal(result.metrics.documents.expired, 1); assert.ok(result.indicators.includes('DOCUMENT_REVIEW_REQUIRED')); });
  await t.test('describes workload only from actual assignments', async () => { const system = setup(); const profile = system.staff.createProfile({ fullName: 'Teacher', roleKey: 'TEACHER' }); system.staff.assign(profile.id, { classId: 'Primary 4', subjectId: 'Math' }); const workload = (await system.service.workforceSnapshot({ actor: actor() })).metrics.workloads[0]; assert.equal(workload.assignmentCount, 1); assert.equal(Object.hasOwn(workload, 'overloaded'), false); });
  await t.test('minimizes sensitive fields from aggregate output', async () => { const system = setup(); system.staff.createProfile({ fullName: 'Teacher', roleKey: 'TEACHER', address: 'Private', confidential: { salary: 1 }, phone: '0240000000' }); application(system); const output = JSON.stringify(await system.service.dashboard({ actor: actor() })); assert.doesNotMatch(output, /Private|0240000000|salary|primaryGuardian/i); });
  await t.test('enforces admissions and workforce role authorization independently', async () => { const system = setup(); await assert.rejects(() => system.service.admissionsSnapshot({ actor: actor('HR_OFFICER', new Set(['staff.read'])) }), (error) => error.code === 'PERMISSION_DENIED'); await assert.rejects(() => system.service.workforceSnapshot({ actor: actor('ADMISSIONS_OFFICER', new Set(['admissions.read'])) }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('cannot make admissions or HR decisions', async () => { const system = setup(); const beforeAdmissions = system.admissions.counts(), beforeStaff = system.staff.counts(); const result = await system.service.dashboard({ actor: actor() }); assert.deepEqual(system.admissions.counts(), beforeAdmissions); assert.deepEqual(system.staff.counts(), beforeStaff); assert.equal(JSON.stringify(result).includes('APPROVE'), false); });
  await t.test('provider outage leaves deterministic metrics visible', async () => { const system = setup({ explain: async () => { throw new Error('offline'); } }); application(system); const result = await system.service.dashboard({ actor: actor() }); assert.equal(result.admissions.metrics.applications, 1); assert.equal(result.explanation, null); });
  await t.test('registers production-only tools and a provider-independent dashboard', async () => { const system = setup(); assert.ok(createAdmissionsWorkforceTools(system.service).every((tool) => tool.productionDataOnly && ['READ', 'ANALYZE'].includes(tool.operationType))); const ui = await readFile(new URL('../public/admissions-workforce-intelligence.js', import.meta.url), 'utf8'); assert.match(ui, /verified admissions and workforce metrics remain visible/); assert.doesNotMatch(ui, /innerHTML|OpenAI|api[_ -]?key/i); });
});
