import test from 'node:test';
import assert from 'node:assert/strict';
import { AIProviderError, AI_PROVIDER_ERRORS, createAIAuditLogger, createAICapabilityRegistry, createAIDataQualityGuard, createAIGateway, createAIOrchestrator, createAIProviderRegistry, createAIToolRegistry, createInMemoryAIAuditSink, createProductionDataGuard, createSchoolContextService } from '../src/ai/index.js';

const actor = (overrides = {}) => ({ id: 'user-1', schoolId: 'school-1', roleKey: 'HEADTEACHER', portal: 'school', permissions: new Set(['academics.read', 'finance.read']), ...overrides });
const answer = (text = 'Grounded answer.') => ({ text, toolRequests: [], finishStatus: 'STOP', usage: { inputTokens: 2, outputTokens: 2, totalTokens: 4 } });
const tools = (...requests) => ({ text: null, toolRequests: requests, finishStatus: 'TOOL_REQUESTS', usage: { inputTokens: 2, outputTokens: 1, totalTokens: 3 } });
const call = (name, argumentsValue = {}, id = `${name}-call`) => ({ id, name, arguments: argumentsValue });
class ScriptedProvider {
  constructor(steps) { this.steps = steps; this.requests = []; }
  async generate(request) { this.requests.push(request); const step = this.steps[Math.min(this.requests.length - 1, this.steps.length - 1)]; if (step instanceof Error) throw step; return typeof step === 'function' ? step(request, this.requests.length) : step; }
  async toolCall(request) { return this.generate(request); }
  async healthCheck() { return { configured: true, healthy: true, reason: null }; }
}

function setup(steps, { limits, partial = false, toolFailure = false, hangingTool = false, includeWrite = false } = {}) {
  const provider = new ScriptedProvider(steps); const providerRegistry = createAIProviderRegistry([{ providerId: 'scripted', modelId: 'test-model', enabled: true, timeoutMs: 100, retryLimit: 0, maxOutputTokens: 64, healthState: 'HEALTHY', provider }]);
  const capabilityRegistry = createAICapabilityRegistry();
  const capability = (id, permission, toolNames) => ({ id, moduleId: `${id}-test`, moduleName: `${id} test`, category: id.toUpperCase(), version: '1.0.0', enabled: true, description: `${id} test capability.`, requiredPermissions: [permission], requiredRoles: ['HEADTEACHER'], dataDomain: id.toUpperCase(), tools: toolNames, metrics: [], productionDataOnly: true, provenanceAware: true, dataQualityAware: true, dataQualityRequirements: ['COMPLETENESS'], auditRequired: true });
  capabilityRegistry.register(capability('academic', 'academics.read', ['academic.summary', ...(includeWrite ? ['academic.write'] : [])])); capabilityRegistry.register(capability('finance', 'finance.read', ['finance.summary']));
  const toolRegistryBase = createAIToolRegistry(); const schema = { type: 'object', properties: { schoolId: { type: 'string' }, fail: { type: 'boolean' } }, additionalProperties: false }; const outputSchema = { type: 'object', properties: { records: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, value: { type: 'number' } } } } } };
  const register = (name, capabilityId, permission, value) => toolRegistryBase.register({ name, capabilityId, description: `Read ${capabilityId} summary.`, operationType: 'READ', requiredPermission: permission, inputSchema: schema, outputSchema, productionDataOnly: true, schoolScoped: true, dataQualityAware: true, auditRequired: true, enabled: true, handler: async () => { if (hangingTool && name === 'academic.summary') return new Promise(() => {}); if (toolFailure && name === 'academic.summary') throw new Error('private failure'); return { records: [{ id: `${capabilityId}-production`, value, provenance: 'PRODUCTION' }, ...(partial && name === 'academic.summary' ? [{ id: 'excluded', value: 999, provenance: 'TEST' }] : [])] }; } });
  register('academic.summary', 'academic', 'academics.read', 4); register('finance.summary', 'finance', 'finance.read', 20);
  const writeTool = { name: 'academic.write', capabilityId: 'academic', description: 'Forbidden write.', operationType: 'WRITE', requiredPermissions: ['academics.read'], inputSchema: schema, outputSchema, productionDataOnly: true, schoolScoped: true, dataQualityAware: true, auditRequired: true, enabled: true, handler: () => { throw new Error('must not run'); } };
  const toolRegistry = includeWrite ? { get: (name) => name === writeTool.name ? writeTool : toolRegistryBase.get(name), list: (options) => [...toolRegistryBase.list(options), writeTool] } : toolRegistryBase;
  const auditLogger = createAIAuditLogger({ sink: createInMemoryAIAuditSink(), environment: 'test', onFailure: () => {} }); const productionDataGuard = createProductionDataGuard({ environment: 'production' }); const dataQualityGuard = createAIDataQualityGuard({ auditLogger }); const production = (record) => ({ schoolId: 'school-1', provenance: 'PRODUCTION', ...record });
  const schoolContextService = createSchoolContextService({ sources: { schoolProfile: [production({ id: 'school-1', name: 'OSAAH' })], academicYears: [production({ id: 'year-1', status: 'ACTIVE' })], terms: [production({ id: 'term-1', academicYearId: 'year-1', status: 'ACTIVE' })], calendarEvents: [] }, modules: [], capabilityRegistry, productionDataGuard, dataQualityGuard, auditLogger, clock: () => '2026-09-04T12:00:00.000Z' });
  const orchestrator = createAIOrchestrator({ providerRegistry, providerId: 'scripted', capabilityRegistry, toolRegistry, productionDataGuard, dataQualityGuard, auditLogger, limits }); const gateway = createAIGateway({ capabilityRegistry, toolRegistry, schoolContextService, productionDataGuard, dataQualityGuard, auditLogger, orchestrator });
  const ask = (overrides = {}) => gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', query: 'What is the current result?', requestId: 'request-1', correlationId: 'correlation-1', ...overrides });
  return { ask, provider, auditLogger };
}

test('repository-native AI Orchestrator', async (t) => {
  await t.test('returns a bounded zero-tool conversational response', async () => { const result = await setup([answer('Hello.')]).ask(); assert.equal(result.narrative, 'Hello.'); assert.equal(result.grounding.grounded, false); assert.equal(result.orchestration.rounds, 1); });
  await t.test('executes one validated tool and returns grounded evidence', async () => { const system = setup([tools(call('academic.summary')), answer()]); const result = await system.ask(); assert.equal(result.orchestration.toolsExecuted, 1); assert.equal(result.grounding.authoritativeToolResults[0].data.records[0].value, 4); assert.ok(system.auditLogger.recent({ limit: 100 }).some((event) => event.eventType === 'AI_ORCHESTRATION_COMPLETED' && event.metadata.toolsExecuted === 1)); });
  await t.test('executes bounded multi-tool requests sequentially', async () => { const result = await setup([tools(call('academic.summary'), call('finance.summary')), answer()]).ask({ capabilityIds: ['finance'] }); assert.equal(result.orchestration.toolsExecuted, 2); assert.deepEqual(result.grounding.authoritativeToolResults.map((item) => item.capabilityId), ['academic', 'finance']); });
  await t.test('supports sequential tool use across rounds', async () => { const result = await setup([tools(call('academic.summary')), tools(call('finance.summary')), answer()]).ask({ capabilityIds: ['finance'] }); assert.equal(result.orchestration.rounds, 3); assert.equal(result.orchestration.toolsExecuted, 2); });
  await t.test('rejects an unauthorized second capability before provider access', async () => { const system = setup([answer()]); await assert.rejects(() => system.ask({ authenticatedUser: actor({ permissions: new Set(['academics.read']) }), capabilityIds: ['finance'] }), (error) => error.code === 'PERMISSION_DENIED'); assert.equal(system.provider.requests.length, 0); });
  await t.test('rejects unknown provider tools', async () => { await assert.rejects(() => setup([tools(call('unknown.tool'))]).ask(), (error) => error.code === 'INVALID_REQUEST'); });
  await t.test('rejects malformed tool arguments', async () => { await assert.rejects(() => setup([tools(call('academic.summary', []))]).ask(), (error) => error.code === 'INVALID_REQUEST'); });
  await t.test('rejects provider WRITE requests without execution', async () => { await assert.rejects(() => setup([tools(call('academic.write'))], { includeWrite: true }).ask(), (error) => error.code === 'WRITE_DISABLED'); });
  await t.test('preserves partial quality and warnings in final grounding', async () => { const result = await setup([tools(call('academic.summary')), answer('Everything is complete.')], { partial: true }).ask(); assert.equal(result.status, 'DEGRADED'); assert.equal(result.grounding.quality.status, 'PARTIAL'); assert.equal(result.grounding.quality.verifiedComplete, false); assert.equal(result.narrative, null); assert.ok(result.grounding.warnings.some((warning) => warning.includes('cannot be presented as verified complete'))); });
  await t.test('normalizes provider failure through the Gateway', async () => { const failure = new AIProviderError(AI_PROVIDER_ERRORS.UNAVAILABLE, 'unavailable'); await assert.rejects(() => setup([failure]).ask(), (error) => error.code === 'PROVIDER_UNAVAILABLE'); });
  await t.test('continues safely with partial tool success', async () => { const result = await setup([tools(call('academic.summary', { fail: true }), call('finance.summary')), answer('Only available evidence is summarized.')], { toolFailure: true }).ask({ capabilityIds: ['finance'] }); assert.equal(result.status, 'DEGRADED'); assert.deepEqual(result.grounding.authoritativeToolResults.map((item) => item.status), ['FAILED', 'SUCCEEDED']); assert.equal(result.grounding.quality.status, 'UNAVAILABLE'); });
  await t.test('stops provider tool loops at the round limit', async () => { await assert.rejects(() => setup([tools(call('academic.summary'))], { limits: { maxToolCalls: 4, maxRounds: 2, maxDurationMs: 100, maxOutputTokens: 32, maxContextChars: 10000 } }).ask(), (error) => error.code === 'ORCHESTRATION_LIMIT'); });
  await t.test('stops orchestration at the execution timeout', async () => { await assert.rejects(() => setup([tools(call('academic.summary'))], { hangingTool: true, limits: { maxToolCalls: 2, maxRounds: 2, maxDurationMs: 10, maxOutputTokens: 32, maxContextChars: 10000 } }).ask(), (error) => error.code === 'ORCHESTRATION_TIMEOUT'); });
  await t.test('rejects cross-school tool arguments', async () => { await assert.rejects(() => setup([tools(call('academic.summary', { schoolId: 'school-2' }))]).ask(), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('provider narrative cannot replace authoritative deterministic values', async () => { const result = await setup([tools(call('academic.summary')), answer('The deterministic value is 999.')]).ask(); assert.equal(result.narrative, null); assert.equal(result.grounding.authoritativeToolResults[0].data.records[0].value, 4); assert.equal(Object.isFrozen(result.grounding.authoritativeToolResults), true); assert.ok(result.grounding.warnings.some((warning) => warning.includes('ungrounded deterministic value'))); });
});
