import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { createAIAdministration, createAIActionStore, createHumanControlledActions } from '../src/ai/index.js';

const admin = (permissions = ['ai.admin.health.read']) => ({ id: 'admin-1', schoolId: 'school-1', roleKey: 'SCHOOL_ADMIN', permissions: new Set(permissions) });
const capabilityRegistry = { list: () => [{ id: 'finance', enabled: true, health: 'ACTIVE', dataQualityAware: true, productionDataOnly: true }, { id: 'future-disabled', enabled: false, health: 'DISABLED', dataQualityAware: true, productionDataOnly: true }] };
const toolRegistry = { list: () => [{ name: 'finance.status', enabled: true }, { name: 'disabled.tool', enabled: false }] };
const auditEvents = [{ eventType: 'AI_GATEWAY_COMPLETED', schoolId: 'school-1', durationMs: 25, tokenUsage: { totalTokens: 12 }, estimatedCost: 0.01 }, { eventType: 'AI_GATEWAY_REJECTED', schoolId: 'school-1', errorCode: 'WRITE_DISABLED', requestStatus: 'BLOCKED', capabilityId: 'finance' }];

test('AI production administration and acceptance', async (t) => {
  await t.test('returns complete safe administrative health metadata', async () => { const health = await createAIAdministration({ enabled: true, capabilityRegistry, toolRegistry, auditLogger: { recent: () => auditEvents }, integrityConfigured: true, components: { gateway: 'HEALTHY', orchestrator: 'HEALTHY', productionDataGuard: 'HEALTHY', dataQualityGuard: 'HEALTHY', schoolContext: 'HEALTHY' }, clock: () => Date.parse('2026-09-05T12:00:00Z') }).health({ actor: admin() }); assert.equal(health.gateway.state, 'HEALTHY'); assert.equal(health.capabilityRegistry.registeredCount, 2); assert.equal(health.metrics.requestCount, 1); assert.equal(health.metrics.totalTokens, 12); });
  await t.test('restricts health through server-side RBAC', async () => { await assert.rejects(() => createAIAdministration().health({ actor: admin([]) }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('reports disabled provider without affecting deterministic components', async () => { const health = await createAIAdministration({ enabled: false, integrityConfigured: true, components: { productionDataGuard: 'HEALTHY', dataQualityGuard: 'HEALTHY' } }).health({ actor: admin() }); assert.equal(health.provider.state, 'UNAVAILABLE'); assert.equal(health.productionDataGuard.state, 'HEALTHY'); assert.equal(health.dataQualityGuard.state, 'HEALTHY'); });
  await t.test('isolates provider health-check outage', async () => { const health = await createAIAdministration({ enabled: true, providerRegistry: { healthCheck: async () => { throw new Error('raw provider secret'); } } }).health({ actor: admin() }); assert.deepEqual(health.provider.state, 'UNAVAILABLE'); assert.doesNotMatch(JSON.stringify(health), /raw provider secret/); });
  await t.test('caches health checks to prevent dashboard request storms', async () => { let calls = 0, time = 1000; const service = createAIAdministration({ enabled: true, providerRegistry: { healthCheck: async () => { calls += 1; return { healthy: true }; } }, clock: () => time, cacheTtlMs: 15000 }); await service.health({ actor: admin() }); await service.health({ actor: admin() }); assert.equal(calls, 1); time += 16000; await service.health({ actor: admin() }); assert.equal(calls, 2); });
  await t.test('bounds capabilities, tools and recent errors', async () => { const capabilities = { list: () => Array.from({ length: 150 }, (_, index) => ({ id: `cap-${index}`, enabled: true, health: 'ACTIVE' })) }, tools = { list: () => Array.from({ length: 250 }, (_, index) => ({ name: `tool-${index}` })) }, events = Array.from({ length: 40 }, (_, index) => ({ errorCode: `E${index}` })); const health = await createAIAdministration({ capabilityRegistry: capabilities, toolRegistry: tools, auditLogger: { recent: () => events } }).health({ actor: admin() }); assert.equal(health.capabilityRegistry.registeredCount, 100); assert.equal(health.toolRegistry.registeredCount, 200); assert.equal(health.recentErrors.length, 20); });
  await t.test('never exposes secret-bearing health fields', async () => { const health = await createAIAdministration({ enabled: true, providerId: 'openai', modelId: 'approved-model', integrityConfigured: true }).health({ actor: admin() }); const output = JSON.stringify(health).toLowerCase(); for (const name of ['api_key', 'integrity_key', 'authorization', 'cookie', 'database_url', 'prompt']) assert.equal(output.includes(name), false); });
  await t.test('bounds action-review queries', async () => { const seed = Array.from({ length: 120 }, (_, index) => ({ id: `a-${index}`, schoolId: 'school-1', status: 'DRAFT' })); const service = createHumanControlledActions({ store: createAIActionStore(seed), integrityKey: 'test-key' }); assert.equal(service.list({ actor: { ...admin(), permissions: new Set(['ai.actions.review']) }, limit: 500 }).length, 100); });
  await t.test('environment example contains placeholders only', async () => { const env = await readFile(new URL('../.env.example', import.meta.url), 'utf8'); assert.match(env, /OSAAH_AI_ACTION_INTEGRITY_KEY=replace-with-/); assert.doesNotMatch(env, /sk-[A-Za-z0-9]{20,}/); });
  await t.test('AI administration UI is safe and mobile responsive', async () => { const [ui, css, app] = await Promise.all([readFile(new URL('../public/ai-administration.js', import.meta.url), 'utf8'), readFile(new URL('../public/styles.css', import.meta.url), 'utf8'), readFile(new URL('../public/app.js', import.meta.url), 'utf8')]); assert.doesNotMatch(ui, /innerHTML/); assert.match(ui, /\/api\/ai\/administration\/health/); assert.match(css, /ai-health-grid/); assert.match(css, /max-width:640px/); assert.match(app, /aiAdministrationObserver/); });
  await t.test('all migrations are ordered, repeat-safe and non-destructive', async () => { const directory = new URL('../schema/', import.meta.url), files = (await readdir(directory)).filter((name) => name.endsWith('.sql')).sort(); assert.equal(files.at(-1), '022_ai_human_controlled_actions.sql'); for (const file of files) { const sql = await readFile(new URL(file, directory), 'utf8'); assert.doesNotMatch(sql, /\bDROP\s+(TABLE|COLUMN|DATABASE)\b/i); } const actionSql = await readFile(new URL('../schema/022_ai_human_controlled_actions.sql', import.meta.url), 'utf8'); assert.match(actionSql, /CREATE TABLE IF NOT EXISTS/); assert.match(actionSql, /CREATE INDEX IF NOT EXISTS/); });
  await t.test('security paths retain production, injection and write controls', async () => { const files = await Promise.all(['production-data-guard.js', 'conversation.js', 'orchestrator.js', 'human-controlled-actions.js'].map((name) => readFile(new URL(`../src/ai/${name}`, import.meta.url), 'utf8'))); const combined = files.join('\n'); for (const marker of ['TEST', 'PROMPT_REJECTED', 'WRITE_DISABLED', 'ACTION_TAMPERED', 'CROSS_SCHOOL_DENIED']) assert.match(combined, new RegExp(marker)); });
  await t.test('global disable gates provider paths but preserves deterministic routes', async () => { const server = await readFile(new URL('../src/server.mjs', import.meta.url), 'utf8'); assert.match(server, /OSAAH_AI_ENABLED/); assert.match(server, /!aiRuntimeEnabled \|\| !aiGateway/); assert.match(server, /!aiRuntimeEnabled \|\| !aiConversation/); assert.match(server, /\/api\/ai\/financial-status/); });
});
