import test from 'node:test';
import assert from 'node:assert/strict';
import { AIProvider, AIProviderError, AI_PROVIDER_ERRORS, DisabledAIProvider, DeterministicMockAIProvider, createAIProviderRegistry, createAIGateway, providerAuditMetadata } from '../src/ai/index.js';

const request = Object.freeze({ query: 'Summarize attendance.', schoolContext: { schoolId: 'school-1' }, toolDefinitions: [], toolResults: [], requestId: 'req-1', correlationId: 'corr-1' });
const registration = (overrides = {}) => ({ providerId: 'mock', modelId: 'deterministic-v1', enabled: true, healthState: 'HEALTHY', timeoutMs: 50, retryLimit: 0, maxOutputTokens: 256, provider: new DeterministicMockAIProvider(), ...overrides });

test('AI provider abstraction', async (t) => {
  await t.test('registers provider metadata without exposing the adapter', () => { const registry = createAIProviderRegistry([registration()]); assert.deepEqual(registry.get('mock'), { providerId: 'mock', modelId: 'deterministic-v1', enabled: true, timeoutMs: 50, retryLimit: 0, maxOutputTokens: 256, healthState: 'HEALTHY' }); assert.equal('provider' in registry.get('mock'), false); });
  await t.test('selects only the explicitly requested provider', () => { const registry = createAIProviderRegistry([registration()]); assert.equal(registry.select('mock').modelId, 'deterministic-v1'); });
  await t.test('fails closed for disabled providers', async () => { const registry = createAIProviderRegistry([registration({ enabled: false, provider: new DisabledAIProvider({ providerId: 'mock', modelId: 'none' }) })]); await assert.rejects(() => registry.invoke('mock', 'generate', request), (error) => error.code === AI_PROVIDER_ERRORS.DISABLED); });
  await t.test('fails closed for unknown providers without fallback', async () => { const registry = createAIProviderRegistry([registration()]); await assert.rejects(() => registry.invoke('unknown', 'generate', request), (error) => error.code === AI_PROVIDER_ERRORS.UNAVAILABLE); });
  await t.test('rejects missing or malformed configuration', () => { assert.throws(() => createAIProviderRegistry().register({ providerId: 'bad' }), (error) => error.code === AI_PROVIDER_ERRORS.CONFIGURATION); });
  await t.test('reports provider health', async () => { const registry = createAIProviderRegistry([registration()]); assert.deepEqual(await registry.healthCheck('mock'), { configured: true, healthy: true, reason: null }); });
  await t.test('normalizes timeouts', async () => { const provider = { generate: () => new Promise(() => {}), toolCall: () => new Promise(() => {}), healthCheck: async () => ({ healthy: true }) }; const registry = createAIProviderRegistry([registration({ provider, timeoutMs: 5 })]); await assert.rejects(() => registry.invoke('mock', 'generate', request), (error) => error.code === AI_PROVIDER_ERRORS.TIMEOUT); });
  await t.test('rejects invalid provider responses', async () => { const provider = { generate: async () => ({ text: 42 }), toolCall: async () => ({ text: 42 }), healthCheck: async () => ({ healthy: true }) }; const registry = createAIProviderRegistry([registration({ provider })]); await assert.rejects(() => registry.invoke('mock', 'generate', request), (error) => error.code === AI_PROVIDER_ERRORS.INVALID_RESPONSE); });
  await t.test('mock provider is deterministic and network-free', async () => { const provider = new DeterministicMockAIProvider(); assert.deepEqual(await provider.generate(request), await provider.generate(request)); });
  await t.test('isolates secrets and raw application objects', async () => { const provider = new DeterministicMockAIProvider(); await assert.rejects(() => provider.generate({ ...request, database: {} }), (error) => error.code === AI_PROVIDER_ERRORS.CONFIGURATION && !JSON.stringify(error).includes('credential')); await assert.rejects(() => provider.generate({ ...request, schoolContext: { authToken: 'credential' } }), (error) => error.code === AI_PROVIDER_ERRORS.CONFIGURATION && !JSON.stringify(error).includes('credential')); });
  await t.test('normalizes response and audit-safe metadata', async () => { const registry = createAIProviderRegistry([registration()]); const result = await registry.invoke('mock', 'generate', { ...request, maxOutputTokens: 999 }); assert.equal(result.provider, 'mock'); assert.equal(result.model, 'deterministic-v1'); assert.equal(result.finishStatus, 'STOP'); assert.deepEqual(providerAuditMetadata(result), { provider: 'mock', model: 'deterministic-v1', latencyMs: result.latencyMs, requestStatus: 'SUCCESS', tokenUsage: result.usage }); });
  await t.test('leaves the gateway unavailable when no provider is configured', async () => { const gateway = createAIGateway({ capabilityRegistry: {}, toolRegistry: {}, schoolContextService: {}, productionDataGuard: {}, dataQualityGuard: {}, auditLogger: {} }); assert.equal(gateway.providerConfigured, false); assert.equal((await new AIProvider().healthCheck()).configured, false); });
});
