import test from 'node:test';
import assert from 'node:assert/strict';
import { CORE_LEVELS, createStudentService } from '../src/students.js';
import { createExaminationService } from '../src/examinations.js';
import { createClassDatabaseService } from '../src/class-database.js';

const actor = { id: 'part3-headteacher', userId: 'part3-headteacher', roleKey: 'HEADTEACHER', portal: 'school', schoolId: 'school-osaah-daylight', permissions: new Set(['students.read', 'promotion.write']) };
const context = (classId, academicYearId = '2026/2027', termId = 'Third Term') => ({ classId, academicYearId, termId });
function setup() { const students = createStudentService(); const examinations = createExaminationService({ students, classes: CORE_LEVELS }); const classDatabase = createClassDatabaseService({ students, classes: CORE_LEVELS }); return { students, examinations, classDatabase }; }
function student(students, input) { return students.createStudent({ firstName: input.firstName, surname: input.surname, classId: input.classId, academicYearId: input.academicYearId ?? '2026/2027', termId: input.termId ?? 'Third Term', admissionDate: '2026-09-01' }); }

test('Primary 1 promotion automatically moves current Class Database membership and preserves identity/history', () => { const { students, examinations, classDatabase } = setup(); const kofi = student(students, { firstName: 'Kofi', surname: 'Mensah', classId: 'Primary 1' }); students.linkParent(kofi.id, { parentId: 'parent-kofi', fullName: 'Ama Mensah', telephone: '0244000000', primary: true }); const id = kofi.permanentStudentId; const result = examinations.promote(kofi.id, '2026/2027', 'PROMOTED', actor, null, { ...context('Primary 1'), toClassId: 'Primary 2', nextAcademicYearId: '2027/2028', nextTermId: 'First Term' }); assert.equal(result.toClassId, 'Primary 2'); assert.equal(students.getStudent(kofi.id).permanentStudentId, id); assert.equal(students.getStudent(kofi.id).classId, 'Primary 2'); assert.equal(classDatabase.list({ classId: 'Primary 1' }, actor).some((row) => row.studentId === kofi.id), false); const moved = classDatabase.list({ classId: 'Primary 2' }, actor).find((row) => row.studentId === kofi.id); assert.equal(moved.studentName, 'Kofi Mensah'); assert.equal(moved.parentGuardianName, 'Ama Mensah'); assert.match(moved.registeredParentPhone, /233|0244/); assert.equal(students.getStudent(kofi.id).history.length, 2); assert.equal(students.getStudent(kofi.id).history[0].classId, 'Primary 1'); assert.equal(students.getStudent(kofi.id).history[1].reason, 'PROMOTED'); const retry = examinations.promote(kofi.id, '2026/2027', 'PROMOTED', actor, null, { ...context('Primary 1'), toClassId: 'Primary 2', nextAcademicYearId: '2027/2028', nextTermId: 'First Term' }); assert.equal(retry.id, result.id); assert.equal(students.getStudent(kofi.id).history.length, 2); });

test('repeat keeps the student in the same class for the next academic period without duplication', () => { const { students, examinations } = setup(); const adwoa = student(students, { firstName: 'Adwoa', surname: 'Owusu', classId: 'Primary 2' }); const id = adwoa.permanentStudentId; const result = examinations.promote(adwoa.id, '2026/2027', 'REPEAT', actor, null, { ...context('Primary 2'), nextAcademicYearId: '2027/2028', nextTermId: 'First Term' }); assert.equal(result.toClassId, 'Primary 2'); assert.equal(students.getStudent(adwoa.id).classId, 'Primary 2'); assert.equal(students.getStudent(adwoa.id).permanentStudentId, id); assert.equal(students.listStudents({}).filter((row) => row.id === adwoa.id).length, 1); assert.equal(students.getStudent(adwoa.id).history.at(-1).reason, 'REPEAT'); });

test('bulk promotion atomically handles promoted and repeated cohorts without duplicates', () => { const { students, examinations } = setup(); const promoted = [1, 2, 3].map((n) => student(students, { firstName: `Promoted${n}`, surname: 'Student', classId: 'Primary 4' })); const repeated = [1, 2].map((n) => student(students, { firstName: `Repeat${n}`, surname: 'Student', classId: 'Primary 4' })); const before = new Map([...promoted, ...repeated].map((row) => [row.id, row.permanentStudentId])); const result = examinations.bulkPromote({ academicYearId: '2026/2027', classId: 'Primary 4', termId: 'Third Term', toClassId: 'Primary 5', nextAcademicYearId: '2027/2028', nextTermId: 'First Term', decisions: [...promoted.map((row) => ({ studentId: row.id, decision: 'PROMOTED' })), ...repeated.map((row) => ({ studentId: row.id, decision: 'REPEAT', toClassId: 'Primary 4' }))] }, actor); assert.equal(result.length, 5); assert.equal(promoted.every((row) => students.getStudent(row.id).classId === 'Primary 5'), true); assert.equal(repeated.every((row) => students.getStudent(row.id).classId === 'Primary 4'), true); assert.equal(new Set(students.listStudents({}).map((row) => row.id)).size, 5); for (const row of [...promoted, ...repeated]) assert.equal(students.getStudent(row.id).permanentStudentId, before.get(row.id)); });

test('authorized JHS 3 completion archives the student and preserves parent identity and history', () => { const { students, examinations, classDatabase } = setup(); const ama = student(students, { firstName: 'Ama', surname: 'Boateng', classId: 'JHS 3', academicYearId: '2028/2029' }); students.linkParent(ama.id, { parentId: 'parent-ama', fullName: 'Kojo Boateng', telephone: '0205000000', primary: true }); const id = ama.permanentStudentId; const historyBefore = students.getStudent(ama.id).history.length; const result = examinations.promote(ama.id, '2028/2029', 'GRADUATED', actor, null, { ...context('JHS 3', '2028/2029', 'Third Term'), completionYear: '2029' }); assert.equal(result.completionYear, '2029'); const completed = students.getStudent(ama.id); assert.equal(completed.status, 'COMPLETED'); assert.equal(completed.classId, null); assert.equal(completed.permanentStudentId, id); assert.equal(students.listStudents({}).some((row) => row.id === ama.id), false); assert.equal(classDatabase.list({ classId: 'JHS 3' }, actor).some((row) => row.studentId === ama.id), false); const archive = classDatabase.listCompleted({ completionYear: '2029', search: id }, actor); assert.equal(archive.length, 1); assert.equal(archive[0].permanentStudentId, id); assert.equal(archive[0].studentName, 'Ama Boateng'); assert.equal(archive[0].parentGuardianName, 'Kojo Boateng'); assert.match(archive[0].registeredParentPhone, /233|0205/); assert.equal(completed.history.length, historyBefore + 1); assert.equal(completed.history.at(-1).reason, 'COMPLETION'); assert.deepEqual(classDatabase.completedOptions(actor).completionYears, ['2029']); const retry = examinations.complete(ama.id, { completionYear: '2029' }, actor); assert.equal(retry.permanentStudentId, id); assert.equal(students.getStudent(ama.id).history.length, historyBefore + 1); });

test('JHS 3 repeat never enters Completed Class Database', () => { const { students, examinations, classDatabase } = setup(); const yaw = student(students, { firstName: 'Yaw', surname: 'Kusi', classId: 'JHS 3', academicYearId: '2028/2029' }); const id = yaw.permanentStudentId; examinations.promote(yaw.id, '2028/2029', 'REPEAT', actor, null, { ...context('JHS 3', '2028/2029', 'Third Term'), nextAcademicYearId: '2029/2030', nextTermId: 'First Term' }); assert.equal(students.getStudent(yaw.id).classId, 'JHS 3'); assert.equal(students.getStudent(yaw.id).status, undefined); assert.equal(students.getStudent(yaw.id).permanentStudentId, id); assert.equal(classDatabase.listCompleted({ search: id }, actor).length, 0); assert.equal(classDatabase.list({ classId: 'JHS 3' }, actor).some((row) => row.studentId === yaw.id), true); });
