import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createExecutiveIntelligence } from '../src/ai/index.js';

const actor = (overrides = {}) => ({ id: 'leader-1', schoolId: 'school-1', roleKey: 'PROPRIETOR', permissions: new Set(['*']), ...overrides });
const quality = (status = 'COMPLETE') => ({ status, verifiedComplete: status === 'COMPLETE', warnings: status === 'COMPLETE' ? [] : [`${status} evidence`] });
const capability = (id, data) => ({ id, title: id, load: async () => typeof data === 'function' ? data() : data });
const snapshot = (id, status = 'COMPLETE', indicators = []) => ({ metrics: { [`${id}Count`]: 1 }, reportingPeriod: { academicYearId: '2026', termId: '1' }, dataQuality: quality(status), warnings: quality(status).warnings, indicators });

test('Executive Brief and Proactive Intelligence', async (t) => {
  await t.test('builds a complete executive brief', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance')), capability('learning', snapshot('learning'))] }); const result = await service.brief({ actor: actor() }); assert.equal(result.dataQuality.status, 'COMPLETE'); assert.deepEqual(result.includedCapabilities, ['finance', 'learning']); });
  await t.test('preserves partial capability quality', async () => { const result = await createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'PARTIAL'))] }).brief({ actor: actor() }); assert.equal(result.dataQuality.status, 'PARTIAL'); assert.match(result.warnings.join(' '), /PARTIAL/); });
  await t.test('returns a partial brief when a capability is unavailable', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance')), capability('operations', () => { throw new Error('offline'); })] }); const result = await service.brief({ actor: actor() }); assert.equal(result.dataQuality.status, 'PARTIAL'); assert.equal(result.sections.operations.status, 'UNAVAILABLE'); assert.equal(result.sections.finance.metrics.financeCount, 1); });
  await t.test('filters sections by independent role permission', async () => { const restricted = { id: 'finance', title: 'finance', load: async ({ actor: user }) => { if (!user.permissions.has('finance.read')) throw Object.assign(new Error('denied'), { code: 'PERMISSION_DENIED', status: 403 }); return snapshot('finance'); } }; const result = await createExecutiveIntelligence({ capabilities: [restricted, capability('learning', snapshot('learning'))] }).brief({ actor: actor({ permissions: new Set(['academics.read']) }) }); assert.deepEqual(result.excludedCapabilities, ['finance']); assert.ok(result.sections.learning); });
  await t.test('aggregates Finance, Academic, and Attendance facts', async () => { const learning = { academic: snapshot('academic'), attendance: snapshot('attendance') }; const result = await createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance')), capability('learning', learning)] }).brief({ actor: actor() }); assert.equal(result.sections.learning.academic.metrics.academicCount, 1); assert.equal(result.reportingPeriods.length, 3); });
  await t.test('creates a proactive financial exception from an existing indicator', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'COMPLETE', ['FINANCIAL_REVIEW_REQUIRED']))] }); const items = await service.refresh({ actor: actor() }); assert.equal(items[0].indicatorType, 'FINANCIAL_REVIEW_REQUIRED'); });
  await t.test('creates a score-entry exception', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('academics', snapshot('academics', 'PARTIAL', ['SCORE_ENTRY_REVIEW_REQUIRED']))] }); assert.ok((await service.refresh({ actor: actor() })).some((item) => item.indicatorType === 'SCORE_ENTRY_REVIEW_REQUIRED')); });
  await t.test('creates an attendance exception', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('attendance', snapshot('attendance', 'COMPLETE', ['ATTENDANCE_REVIEW_RECOMMENDED']))] }); assert.ok((await service.refresh({ actor: actor() })).some((item) => item.capability === 'attendance')); });
  await t.test('creates admissions and workforce exceptions', async () => { const people = { admissions: snapshot('admissions', 'COMPLETE', ['ADMISSION_REVIEW_REQUIRED']), workforce: snapshot('workforce', 'COMPLETE', ['STAFFING_REVIEW_REQUIRED']) }; const items = await createExecutiveIntelligence({ capabilities: [capability('people', people)] }).refresh({ actor: actor() }); assert.equal(items.filter((item) => !item.indicatorType.startsWith('DATA_QUALITY')).length, 2); });
  await t.test('creates operational exceptions', async () => { const items = await createExecutiveIntelligence({ capabilities: [capability('operations', snapshot('operations', 'COMPLETE', ['OPERATIONAL_REVIEW_REQUIRED']))] }).refresh({ actor: actor() }); assert.equal(items[0].indicatorType, 'OPERATIONAL_REVIEW_REQUIRED'); });
  await t.test('deduplicates identical unresolved alerts', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'PARTIAL'))] }); await service.refresh({ actor: actor() }); await service.refresh({ actor: actor() }); assert.equal(service.feed({ actor: actor() }).length, 1); });
  await t.test('supports authorized acknowledgement and resolution', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'PARTIAL'))] }); const [item] = await service.refresh({ actor: actor() }); assert.equal((await service.acknowledge({ actor: actor(), id: item.id, humanInitiated: true })).status, 'ACKNOWLEDGED'); assert.equal((await service.resolve({ actor: actor(), id: item.id, humanInitiated: true })).status, 'RESOLVED'); });
  await t.test('refreshes after a subscribed domain revision', async () => { let listener, indicator = []; const source = { subscribe: (callback) => { listener = callback; } }; const service = createExecutiveIntelligence({ capabilities: [capability('attendance', () => snapshot('attendance', 'COMPLETE', indicator))], revisionSources: [source] }); await service.brief({ actor: actor() }); indicator = ['ATTENDANCE_REVIEW_RECOMMENDED']; listener(); await new Promise((resolve) => setTimeout(resolve, 10)); assert.equal(service.feed({ actor: actor() }).length, 1); });
  await t.test('keeps deterministic metrics during provider outage', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance'))], explain: async () => { throw new Error('provider offline'); } }); const result = await service.brief({ actor: actor() }); assert.equal(result.sections.finance.metrics.financeCount, 1); assert.equal(result.explanation, null); });
  await t.test('does not invent alerts from unconfigured thresholds', async () => { const data = { metrics: { outstanding: 999999, collectionRate: 1 }, dataQuality: quality(), warnings: [], indicators: [] }; const items = await createExecutiveIntelligence({ capabilities: [capability('finance', data)] }).refresh({ actor: actor() }); assert.equal(items.length, 0); });
  await t.test('cannot perform corrective actions autonomously', async () => { const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'PARTIAL'))] }); const [item] = await service.refresh({ actor: actor() }); await assert.rejects(() => service.acknowledge({ actor: actor(), id: item.id }), (error) => error.code === 'WRITE_DISABLED'); });
  await t.test('rejects non-production evidence', async () => { const result = await createExecutiveIntelligence({ capabilities: [capability('finance', { ...snapshot('finance'), provenance: 'TEST' })] }).brief({ actor: actor() }); assert.equal(result.sections.finance.status, 'UNAVAILABLE'); });
  await t.test('audits brief and feed lifecycle metadata without source rows', async () => { const events = []; const service = createExecutiveIntelligence({ capabilities: [capability('finance', snapshot('finance', 'PARTIAL'))], auditLogger: { record: async (event) => events.push(event) } }); const [item] = await service.refresh({ actor: actor() }); await service.acknowledge({ actor: actor(), id: item.id, humanInitiated: true }); assert.ok(events.some((event) => event.eventType === 'AI_EXECUTIVE_BRIEF_GENERATED')); assert.ok(events.some((event) => event.eventType === 'AI_PROACTIVE_ITEM_CREATED')); assert.equal(JSON.stringify(events).includes('financeCount'), false); });
  await t.test('integrates a mobile-safe authorized dashboard', async () => { const [app, ui, css] = await Promise.all([readFile(new URL('../public/app.js', import.meta.url), 'utf8'), readFile(new URL('../public/executive-intelligence.js', import.meta.url), 'utf8'), readFile(new URL('../public/styles.css', import.meta.url), 'utf8')]); assert.match(app, /executive-intelligence/); assert.match(ui, /\/api\/ai\/executive-brief/); assert.doesNotMatch(ui, /innerHTML/); assert.match(css, /executive-grid/); });
});
