import test from 'node:test';
import assert from 'node:assert/strict';
import { createFeeCollectionsRepository } from '../src/fee-collections-repository.js';

const actor = (roleKey, schoolId = 'school-a') => ({ id: `${roleKey}-1`, roleKey, schoolId, permissions: new Set(['*']) });
function db() { const state = { rows: [{ id: 'c1', school_id: 'school-a', amount_received_minor: 10000 }], audit: [] }; return { state, async query(sql, p) { if (sql.includes('fee_collection_records')) return state.rows.filter((r) => r.school_id === p[0] && (!p[1] || r.id === p[1])); return []; }, async execute(sql, p) { if (sql.startsWith('UPDATE')) state.rows[0].amount_received_minor = p[0]; else state.audit.push({ id: p[0], school_id: p[1], collection_id: p[2], actor_user_id: p[3], reason: p[4], before: p[5], after: p[6] }); }, async transaction(work) { return work(this); } }; }

test('authorized accountant correction records before/after audit', async () => { const d = db(); const result = await createFeeCollectionsRepository({ adapter: d }).correctCollection('c1', { amountReceivedMinor: 12000, reason: 'Cashbook reconciliation' }, actor('ACCOUNTANT_BURSAR')); assert.equal(result.afterAmountReceivedMinor, 12000); assert.deepEqual(d.state.audit[0], { id: d.state.audit[0].id, school_id: 'school-a', collection_id: 'c1', actor_user_id: 'ACCOUNTANT_BURSAR-1', reason: 'Cashbook reconciliation', before: 10000, after: 12000 }); });
test('teacher, parent, foreign school, invalid amount, and blank reason are denied', async () => { const d = db(); const repo = createFeeCollectionsRepository({ adapter: d }); await assert.rejects(() => repo.correctCollection('c1', { amountReceivedMinor: 12000, reason: 'x' }, actor('TEACHER')), /permission/); await assert.rejects(() => repo.correctCollection('c1', { amountReceivedMinor: 12000, reason: 'x' }, actor('PARENT')), /permission/); await assert.rejects(() => repo.correctCollection('c1', { amountReceivedMinor: 12000, reason: 'x' }, actor('ACCOUNTANT_BURSAR', 'school-b')), /not found/); await assert.rejects(() => repo.correctCollection('c1', { amountReceivedMinor: -1, reason: 'x' }, actor('ACCOUNTANT_BURSAR')), /Invalid amount/); await assert.rejects(() => repo.correctCollection('c1', { amountReceivedMinor: 12000, reason: ' ' }, actor('ACCOUNTANT_BURSAR')), /reason/); assert.equal(d.state.audit.length, 0); });
