import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createFeeService } from '../src/fees.js';
import { createAIDataQualityGuard, createFinancialIntelligenceService, createFinancialIntelligenceTools, createProductionDataGuard } from '../src/ai/index.js';

const now = () => '2026-09-04T12:00:00.000Z';
const actor = (roleKey = 'ACCOUNTANT_BURSAR', permissions = new Set(['finance.read'])) => ({ id: `user-${roleKey}`, schoolId: 'school-osaah-daylight', roleKey, portal: 'school', permissions });
const engine = (fees, options = {}) => createFinancialIntelligenceService({ fees, productionDataGuard: createProductionDataGuard({ environment: 'production', clock: now }), dataQualityGuard: createAIDataQualityGuard({ clock: now }), now, ...options });
function invoice(fees, studentId, total, extra = {}) { return fees.invoice({ studentId, academicYearId: '2026', termId: 'T1', lineItems: [{ type: 'TUITION', amount: total }], ...extra }); }
function sourceFees(sources) { const listeners = new Set(); return { listInvoices: () => sources.invoices ?? [], listPayments: () => sources.payments ?? [], listExpenses: () => sources.expenses ?? [], listIncomes: () => sources.incomes ?? [], subscribe: (fn) => { listeners.add(fn); return () => listeners.delete(fn); }, revision: () => 1 }; }
const production = (record) => ({ id: crypto.randomUUID(), schoolId: 'school-osaah-daylight', provenance: 'PRODUCTION', academicYearId: '2026', termId: 'T1', createdAt: now(), ...record });

test('repository-native Financial Intelligence', async (t) => {
  await t.test('calculates full, partial, and unpaid liabilities from Fee Hub invoices and valid payments', async () => { const fees = createFeeService({ now }); const full = invoice(fees, 'full', 100); const partial = invoice(fees, 'partial', 80); invoice(fees, 'unpaid', 60); fees.pay({ invoiceNumber: full.invoiceNumber, amount: 100, method: 'BANK' }, { userId: 'bursar' }); fees.pay({ invoiceNumber: partial.invoiceNumber, amount: 30, method: 'BANK' }, { userId: 'bursar' }); const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.deepEqual({ expected: result.metrics.expectedRevenue, collected: result.metrics.totalCollected, outstanding: result.metrics.outstanding }, { expected: 240, collected: 130, outstanding: 110 }); assert.equal(result.metrics.fullyPaidStudents, 1); assert.equal(result.metrics.partiallyPaidStudents, 1); assert.equal(result.metrics.unpaidStudents, 1); });
  await t.test('includes valid expenses, refunds, and invoice discounts without treating refunds as collections', async () => { const fees = createFeeService({ now }); const bill = invoice(fees, 'student', 100, { discount: 10 }); const paid = fees.pay({ invoiceNumber: bill.invoiceNumber, amount: 50, method: 'BANK' }, { userId: 'bursar' }); fees.changeReceipt(paid.receiptNumber, 'REFUND', { userId: 'owner' }, 'Duplicate'); fees.recordExpense({ category: 'UTILITIES', amount: 12.34, academicYearId: '2026', termId: 'T1' }, { userId: 'bursar' }); const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.adjustments, 10); assert.equal(result.metrics.refunds, 50); assert.equal(result.metrics.totalCollected, 0); assert.equal(result.metrics.totalExpenses, 12.34); });
  await t.test('excludes failed and non-production payments and never counts receipt identity separately', async () => { const fees = sourceFees({ invoices: [production({ invoiceNumber: 'INV-1', studentId: 's1', total: 100, discount: 0, status: 'PART_PAID' })], payments: [production({ invoiceNumber: 'INV-1', receiptNumber: 'RCT-1', studentId: 's1', amount: 30, status: 'VALID' }), production({ invoiceNumber: 'INV-1', receiptNumber: 'RCT-2', studentId: 's1', amount: 40, status: 'FAILED' }), production({ invoiceNumber: 'INV-1', receiptNumber: 'RCT-3', studentId: 's1', amount: 50, status: 'VALID', provenance: 'TEST' })] }); const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.totalCollected, 30); assert.equal(result.sourceCounts.payments, 1); assert.equal(result.sourceCounts.excluded, 1); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('uses integer-pesewa arithmetic for currency precision', async () => { const fees = createFeeService({ now }); const bill = invoice(fees, 'student', 0.3); fees.pay({ invoiceNumber: bill.invoiceNumber, amount: 0.1, method: 'BANK' }, { userId: 'bursar' }); const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.outstanding, 0.2); assert.equal(result.metrics.collectionRate, 33.33); });
  await t.test('defaults to the active School Context period', async () => { const fees = createFeeService({ now }); invoice(fees, 'current', 100); invoice(fees, 'historic', 250, { academicYearId: '2025', termId: 'T3' }); const schoolContextService = { generate: async () => ({ academicYear: { id: '2026' }, term: { id: 'T1' } }) }; const result = await engine(fees, { schoolContextService }).snapshot({ actor: actor() }); assert.equal(result.reportingPeriod.source, 'SCHOOL_CONTEXT'); assert.equal(result.metrics.expectedRevenue, 100); });
  await t.test('supports authorized historical period selection and comparison', async () => { const fees = createFeeService({ now }); invoice(fees, 'current', 100); invoice(fees, 'historic', 250, { academicYearId: '2025', termId: 'T3' }); const service = engine(fees); const old = await service.snapshot({ actor: actor(), academicYearId: '2025', termId: 'T3' }); assert.equal(old.metrics.expectedRevenue, 250); const comparison = await service.compare({ actor: actor(), periods: [{ academicYearId: '2025', termId: 'T3' }, { academicYearId: '2026', termId: 'T1' }] }); assert.equal(comparison.change.expectedRevenue, -150); });
  await t.test('authorizes exactly the four required dashboard roles', async () => { const service = engine(createFeeService({ now })); for (const role of ['PROPRIETOR', 'HEADTEACHER', 'ASSISTANT_HEADTEACHER', 'ACCOUNTANT_BURSAR']) assert.equal((await service.snapshot({ actor: actor(role) })).dataQuality.status, 'COMPLETE'); await assert.rejects(() => service.snapshot({ actor: actor('TEACHER') }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('invalidates cached narration automatically after financial changes', async () => { const fees = createFeeService({ now }); let explanations = 0; const service = engine(fees, { explain: async () => `explanation-${++explanations}` }); await service.snapshot({ actor: actor() }); await service.snapshot({ actor: actor() }); assert.equal(explanations, 1); invoice(fees, 'student', 20); await service.snapshot({ actor: actor() }); assert.equal(explanations, 2); });
  await t.test('keeps deterministic figures available when the provider explanation fails', async () => { const fees = createFeeService({ now }); invoice(fees, 'student', 25); const result = await engine(fees, { explain: async () => { throw new Error('provider outage'); } }).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.expectedRevenue, 25); assert.equal(result.explanation, null); });
  await t.test('withholds definitive net position and warns when production evidence is partial', async () => { const fees = sourceFees({ invoices: [production({ invoiceNumber: 'INV-1', studentId: 's1', total: 100, discount: 0, status: 'ISSUED' }), production({ invoiceNumber: 'INV-X', studentId: 's2', total: 500, discount: 0, status: 'ISSUED', provenance: 'DEMO' })] }); const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.dataQuality.status, 'PARTIAL'); assert.equal(result.metrics.netFinancialPosition, null); assert.ok(result.warnings.some((warning) => warning.includes('excluded'))); });
  await t.test('retains available metrics but marks a critical unavailable source', async () => { const fees = sourceFees({ invoices: [production({ invoiceNumber: 'INV-1', studentId: 's1', total: 100, discount: 0, status: 'ISSUED' })] }); fees.listExpenses = () => { throw new Error('offline'); }; const result = await engine(fees).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.expectedRevenue, 100); assert.equal(result.metrics.netFinancialPosition, null); assert.equal(result.dataQuality.status, 'UNAVAILABLE'); assert.ok(result.warnings.includes('EXPENSES_SOURCE_UNAVAILABLE')); });
  await t.test('does not allow AI narration to override authoritative figures', async () => { const fees = createFeeService({ now }); invoice(fees, 'student', 42); const result = await engine(fees, { explain: async () => 'Expected revenue is GHS 999,999.' }).snapshot({ actor: actor(), academicYearId: '2026', termId: 'T1' }); assert.equal(result.metrics.expectedRevenue, 42); assert.match(result.explanation, /999,999/); });
  await t.test('registers five production-only Finance READ/ANALYZE tools', () => { const tools = createFinancialIntelligenceTools(engine(createFeeService({ now }))); assert.deepEqual(tools.map((tool) => tool.name), ['finance.status', 'finance.collections', 'finance.outstanding', 'finance.expenses', 'finance.period-comparison']); assert.ok(tools.every((tool) => tool.productionDataOnly && tool.dataQualityAware && ['READ', 'ANALYZE'].includes(tool.operationType))); });
  await t.test('dashboard client renders deterministic metrics independently of narration', async () => { const source = await readFile(new URL('../public/financial-intelligence.js', import.meta.url), 'utf8'); assert.match(source, /data\.metrics/); assert.match(source, /AI explanation is unavailable; verified figures remain available/); assert.match(source, /setInterval\(refresh, 60000\)/); assert.doesNotMatch(source, /OpenAI|api[_ -]?key|innerHTML/i); });
});
