import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { ROLE_DEFINITIONS, ROLE_KEYS } from '../src/roles.js';
import { SIDEBAR_CATEGORIES, visibleSidebar } from '../src/sidebar-registry.js';
import { createAuditLog } from '../src/audit.js';

test('role definitions include all required roles and proprietor is highest', () => { assert.equal(ROLE_DEFINITIONS.length, 21); assert.equal(ROLE_DEFINITIONS.find((r) => r.roleKey === 'PROPRIETOR').oversightRank, 100); assert.ok(ROLE_KEYS.has('PARENT')); assert.ok(ROLE_KEYS.has('STUDENT')); });
test('sidebar registry filters by permission and sorts modules', () => { const groups = visibleSidebar({ permissions: new Set(['users.read']) }); assert.equal(groups.length, 2); const system = groups.find((group) => group.category === 'SYSTEM & SECURITY'); assert.equal(system.modules[0].moduleKey, 'users'); assert.equal(SIDEBAR_CATEGORIES.length, 20); });
test('sidebar registry accepts a future module without editing navigation code', () => { const groups = visibleSidebar({ modules: [{ moduleKey: 'fees', moduleName: 'Fees', category: 'FEE HUB', route: '/fees', icon: '$', displayOrder: 1, requiredPermission: null, enabled: true }], permissions: new Set() }); assert.equal(groups[0].modules[0].moduleKey, 'fees'); });
test('audit logs require action and entity and are immutable-style', () => { const log = createAuditLog({ action: 'UPDATE', entity: 'School', entityId: 'school-1', previousValue: { name: 'Old' }, newValue: { name: 'New' } }, () => '2026-09-02T00:00:00.000Z'); assert.equal(log.occurredAt, '2026-09-02T00:00:00.000Z'); assert.throws(() => { log.action = 'DELETE'; }, TypeError); assert.throws(() => createAuditLog({ action: 'READ' }), /entity/); });
test('foundation schema contains relational anchors and audit indexes', async () => { const schema = await readFile(new URL('../schema/001_foundation.sql', import.meta.url), 'utf8'); for (const table of ['schools', 'academic_years', 'terms', 'levels', 'classes', 'streams', 'subjects', 'departments', 'houses', 'users', 'roles', 'permissions', 'user_roles', 'sidebar_modules', 'sidebar_categories', 'system_settings', 'audit_logs', 'students', 'staff']) assert.match(schema, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`)); assert.match(schema, /REFERENCES schools\(id\)/); assert.match(schema, /idx_audit_entity/); });
test('foundation seed preserves official school identity and registry categories', async () => { const seed = await readFile(new URL('../schema/002_foundation_seed.sql', import.meta.url), 'utf8'); assert.match(seed, /OSAAH DAYLIGHT SCH\. COM\./); assert.match(seed, /AIM HIGH, ACADEMIC IS OUR CORE VALUE/); assert.match(seed, /school-osaah-daylight/); assert.equal((seed.match(/UNION ALL SELECT/g) ?? []).length, 19); });
test('mobile-first shell includes viewport support and responsive navigation styles', async () => { const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8'); const css = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8'); assert.match(html, /name="viewport"/); assert.match(css, /min-width:320px/); assert.match(css, /@media\(min-width:760px\)/); assert.match(css, /\.sidebar\.open/); });
