import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createAIActionStore, createHumanControlledActions } from '../src/ai/index.js';

const key = 'test-only-integrity-key-with-sufficient-entropy';
const actor = (id = 'leader-1', schoolId = 'school-1', permissions = ['ai.actions.prepare', 'ai.actions.approve', 'ai.actions.review']) => ({ id, schoolId, roleKey: 'HEADTEACHER', permissions: new Set(permissions) });
const input = (user = actor()) => ({ actor: user, actionType: 'DRAFT_SCHOOL_NOTICE', proposedChange: 'Publish the reviewed reopening notice.', payload: { title: 'Reopening', body: 'School reopens Monday.', audience: 'SCHOOL' }, idempotencyKey: `key-${crypto.randomUUID()}` });
async function approved(service, preparer = actor(), approver = actor('leader-2')) { const draft = await service.prepare(input(preparer)); const pending = await service.submit({ actor: preparer, id: draft.id, expectedVersion: draft.version }); return service.approve({ actor: approver, id: draft.id, expectedVersion: pending.version }); }

test('Human-Controlled AI Actions', async (t) => {
  await t.test('prepares a safe draft', async () => { const item = await createHumanControlledActions({ integrityKey: key }).prepare(input()); assert.equal(item.status, 'DRAFT'); assert.match(item.integrity, /^[a-f0-9]{64}$/); });
  await t.test('denies unsupported action type', async () => { await assert.rejects(() => createHumanControlledActions({ integrityKey: key }).prepare({ ...input(), actionType: 'ARBITRARY_FUNCTION' }), (error) => error.code === 'ACTION_TYPE_DENIED'); });
  await t.test('submits with optimistic versioning', async () => { const service = createHumanControlledActions({ integrityKey: key }), draft = await service.prepare(input()); const pending = await service.submit({ actor: actor(), id: draft.id, expectedVersion: 1 }); assert.equal(pending.status, 'PENDING_APPROVAL'); assert.equal(pending.version, 2); });
  await t.test('approves exact proposed action', async () => { assert.equal((await approved(createHumanControlledActions({ integrityKey: key }))).status, 'APPROVED'); });
  await t.test('requires non-empty rejection reason', async () => { const service = createHumanControlledActions({ integrityKey: key }), draft = await service.prepare(input()), pending = await service.submit({ actor: actor(), id: draft.id, expectedVersion: draft.version }); await assert.rejects(() => service.reject({ actor: actor('leader-2'), id: draft.id, expectedVersion: pending.version, reason: '  ' }), (error) => error.code === 'REJECTION_REASON_REQUIRED'); });
  await t.test('denies cross-school approval', async () => { const service = createHumanControlledActions({ integrityKey: key }), draft = await service.prepare(input()), pending = await service.submit({ actor: actor(), id: draft.id, expectedVersion: draft.version }); await assert.rejects(() => service.approve({ actor: actor('other', 'school-2'), id: draft.id, expectedVersion: pending.version }), (error) => error.code === 'CROSS_SCHOOL_DENIED'); });
  await t.test('denies cross-school submission', async () => { const service = createHumanControlledActions({ integrityKey: key }), draft = await service.prepare(input()); await assert.rejects(() => service.submit({ actor: actor('other', 'school-2'), id: draft.id, expectedVersion: draft.version }), (error) => error.code === 'CROSS_SCHOOL_DENIED'); });
  await t.test('blocks execution after permission revocation', async () => { const service = createHumanControlledActions({ integrityKey: key, adapters: { DRAFT_SCHOOL_NOTICE: () => ({ id: 'notice' }) } }), item = await approved(service); await assert.rejects(() => service.execute({ actor: actor('leader-2', 'school-1', ['ai.actions.approve', 'ai.actions.review']), id: item.id, expectedVersion: item.version }), (error) => error.code === 'PERMISSION_REVOKED'); });
  await t.test('enforces separation of duties by default', async () => { const service = createHumanControlledActions({ integrityKey: key }), draft = await service.prepare(input()), pending = await service.submit({ actor: actor(), id: draft.id, expectedVersion: draft.version }); await assert.rejects(() => service.approve({ actor: actor(), id: draft.id, expectedVersion: pending.version }), (error) => error.code === 'SELF_APPROVAL_DENIED'); });
  await t.test('detects full-action metadata tampering', async () => { const base = createAIActionStore(); let tamper = false; const store = { insert: (x) => base.insert(x), list: (x) => base.list(x), compareAndSwap: (...x) => base.compareAndSwap(...x), get: (id) => { const row = base.get(id); return tamper && row ? { ...row, requiredApprovalPermission: 'permissions.change' } : row; } }; const service = createHumanControlledActions({ integrityKey: key, store }), draft = await service.prepare(input()); tamper = true; await assert.rejects(() => service.submit({ actor: actor(), id: draft.id, expectedVersion: draft.version }), (error) => error.code === 'ACTION_TAMPERED'); });
  await t.test('detects payload tampering', async () => { const base = createAIActionStore(); let tamper = false; const store = { insert: (x) => base.insert(x), list: (x) => base.list(x), compareAndSwap: (...x) => base.compareAndSwap(...x), get: (id) => { const row = base.get(id); return tamper && row ? { ...row, payload: { ...row.payload, body: 'Changed' } } : row; } }; const service = createHumanControlledActions({ integrityKey: key, store }), draft = await service.prepare(input()); tamper = true; await assert.rejects(() => service.submit({ actor: actor(), id: draft.id, expectedVersion: draft.version }), (error) => error.code === 'ACTION_TAMPERED'); });
  await t.test('blocks repeated execution and returns terminal result', async () => { let calls = 0; const service = createHumanControlledActions({ integrityKey: key, adapters: { DRAFT_SCHOOL_NOTICE: () => ({ id: `notice-${++calls}` }) } }), item = await approved(service), first = await service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }), second = await service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }); assert.equal(second.id, first.id); assert.equal(calls, 1); });
  await t.test('prevents concurrent execution claims', async () => { let release; const wait = new Promise((resolve) => { release = resolve; }); const service = createHumanControlledActions({ integrityKey: key, adapters: { DRAFT_SCHOOL_NOTICE: async () => { await wait; return { id: 'one' }; } } }), item = await approved(service), first = service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }); await new Promise((resolve) => setTimeout(resolve, 0)); await assert.rejects(() => service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }), (error) => error.code === 'ACTION_EXECUTION_IN_PROGRESS'); release(); await first; });
  await t.test('enforces school-scoped idempotency', async () => { const service = createHumanControlledActions({ integrityKey: key }), data = { ...input(), idempotencyKey: 'same-key' }; await service.prepare(data); await assert.rejects(() => service.prepare(data), (error) => error.code === 'IDEMPOTENCY_CONFLICT'); });
  await t.test('fails closed for unknown execution adapter', async () => { const service = createHumanControlledActions({ integrityKey: key }), item = await approved(service); await assert.rejects(() => service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }), (error) => error.code === 'ACTION_ADAPTER_UNAVAILABLE'); });
  await t.test('executes the existing business adapter once', async () => { let calls = 0; const service = createHumanControlledActions({ integrityKey: key, adapters: { DRAFT_SCHOOL_NOTICE: () => ({ id: `notice-${++calls}`, status: 'SENT' }) } }), item = await approved(service), result = await service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }); assert.equal(result.status, 'EXECUTED'); assert.equal(calls, 1); assert.deepEqual(result.executionResult, { id: 'notice-1', status: 'SENT' }); });
  await t.test('sanitizes execution failure', async () => { const service = createHumanControlledActions({ integrityKey: key, adapters: { DRAFT_SCHOOL_NOTICE: () => { throw new Error('secret database row'); } } }), item = await approved(service), result = await service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }); assert.equal(result.status, 'FAILED'); assert.equal(result.failureReason, 'The approved action could not be completed.'); assert.doesNotMatch(JSON.stringify(result), /secret database/); });
  await t.test('audits the durable lifecycle without payloads', async () => { const events = [], service = createHumanControlledActions({ integrityKey: key, auditLogger: { record: async (event) => events.push(event) }, adapters: { DRAFT_SCHOOL_NOTICE: () => ({ id: 'notice' }) } }), item = await approved(service); await service.execute({ actor: actor('leader-2'), id: item.id, expectedVersion: item.version }); assert.ok(['AI_ACTION_PREPARED', 'AI_ACTION_SUBMITTED', 'AI_ACTION_APPROVED', 'AI_ACTION_EXECUTION_STARTED', 'AI_ACTION_EXECUTED'].every((type) => events.some((event) => event.eventType === type))); assert.equal(JSON.stringify(events).includes('School reopens'), false); });
  await t.test('denies unauthorized action review', () => { const service = createHumanControlledActions({ integrityKey: key }); assert.throws(() => service.list({ actor: actor('teacher', 'school-1', []) }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('denies prohibited high-impact actions', async () => { await assert.rejects(() => createHumanControlledActions({ integrityKey: key }).prepare({ ...input(), proposedChange: 'Change the learner score to 100.' }), (error) => error.code === 'PROHIBITED_ACTION'); });
  await t.test('includes durable migration and explicit-confirmation review UI', async () => { const [sql, ui] = await Promise.all([readFile(new URL('../schema/022_ai_human_controlled_actions.sql', import.meta.url), 'utf8'), readFile(new URL('../public/ai-action-review.js', import.meta.url), 'utf8')]); assert.match(sql, /UNIQUE \(school_id, idempotency_key\)/); assert.match(sql, /version INTEGER/); assert.match(ui, /window\.confirm/); assert.match(ui, /proposedChange/); });
});
