import test from 'node:test';
import assert from 'node:assert/strict';
import { AIGatewayError, AI_PROVIDER_ERRORS, DeterministicMockAIProvider, OpenAIResponsesProvider, createAIAuditLogger, createAICapabilityRegistry, createAIDataQualityGuard, createAIGateway, createAIProviderRegistry, createAIToolRegistry, createConfiguredAIProviderRegistry, createInMemoryAIAuditSink, createProductionDataGuard, createSchoolContextService } from '../src/ai/index.js';

const providerRequest = { query: 'Give a safe summary.', schoolContext: { schoolId: 'school-1' }, toolDefinitions: [], toolResults: [], requestId: 'request-1', correlationId: 'correlation-1', maxOutputTokens: 32 };
const responseValue = { status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: 'Safe summary.' }] }], usage: { input_tokens: 8, output_tokens: 3, total_tokens: 11 } };
function httpResponse(status, value = responseValue) { return { status, ok: status >= 200 && status < 300, json: async () => value }; }
function configured(fetchImpl, overrides = {}) { return createConfiguredAIProviderRegistry({ fetchImpl, env: { OSAAH_AI_PROVIDER_ID: 'openai', OSAAH_AI_MODEL_ID: 'approved-model', OSAAH_AI_API_KEY: 'test-only-key', OSAAH_AI_PROVIDER_ENABLED: 'true', OSAAH_AI_PROVIDER_TIMEOUT_MS: '30', OSAAH_AI_PROVIDER_RETRY_LIMIT: '0', OSAAH_AI_MAX_OUTPUT_TOKENS: '64', ...overrides } }); }
const actor = () => ({ id: 'user-1', schoolId: 'school-1', roleKey: 'HEADTEACHER', portal: 'school', permissions: new Set(['academics.read']) });
function gatewaySetup(providerConfig = null, handler = async () => ({ records: [{ id: 'allowed', value: 4, secret: 'remove', provenance: 'PRODUCTION' }, { id: 'test-row', value: 9, provenance: 'TEST' }] })) {
  const capabilities = createAICapabilityRegistry([{ id: 'academic', moduleId: 'academic-test', moduleName: 'Academic Test', category: 'ACADEMICS', version: '1.0.0', enabled: true, description: 'Test capability.', requiredPermissions: ['academics.read'], requiredRoles: ['HEADTEACHER'], dataDomain: 'ACADEMICS', tools: ['academic.summary'], metrics: [], productionDataOnly: true, provenanceAware: true, dataQualityAware: true, dataQualityRequirements: ['COMPLETENESS'], auditRequired: true }]);
  const tools = createAIToolRegistry([{ name: 'academic.summary', capabilityId: 'academic', description: 'Read a safe summary.', operationType: 'READ', requiredPermission: 'academics.read', inputSchema: { type: 'object' }, outputSchema: { type: 'object', properties: { records: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, value: { type: 'number' } } } }, quality: { type: 'object', properties: { status: { type: 'string' } } } } }, productionDataOnly: true, schoolScoped: true, dataQualityAware: true, auditRequired: true, enabled: true, handler }]);
  const auditLogger = createAIAuditLogger({ sink: createInMemoryAIAuditSink(), environment: 'test', onFailure: () => {} }); const productionDataGuard = createProductionDataGuard({ environment: 'production' }); const dataQualityGuard = createAIDataQualityGuard({ auditLogger }); const production = (record) => ({ schoolId: 'school-1', provenance: 'PRODUCTION', ...record });
  const schoolContextService = createSchoolContextService({ sources: { schoolProfile: [production({ id: 'school-1', name: 'OSAAH' })], academicYears: [production({ id: 'year-1', status: 'ACTIVE' })], terms: [production({ id: 'term-1', academicYearId: 'year-1', status: 'ACTIVE' })], calendarEvents: [] }, modules: [], capabilityRegistry: capabilities, productionDataGuard, dataQualityGuard, auditLogger, clock: () => '2026-09-04T12:00:00.000Z' });
  return { auditLogger, gateway: createAIGateway({ capabilityRegistry: capabilities, toolRegistry: tools, schoolContextService, productionDataGuard, dataQualityGuard, auditLogger, providerRegistry: providerConfig?.registry, providerId: providerConfig?.providerId }) };
}

test('secure live AI provider connection', async (t) => {
  await t.test('accepts valid server configuration and reports health', async () => { const config = configured(async (url) => url.includes('/models/') ? httpResponse(200) : httpResponse(200)); assert.equal(config.enabled, true); assert.deepEqual(await config.registry.healthCheck('openai'), { configured: true, healthy: true, reason: null }); const result = await config.registry.invoke('openai', 'generate', providerRequest); assert.equal(result.text, 'Safe summary.'); assert.equal(result.usage.totalTokens, 11); });
  await t.test('server switch disables provider calls', async () => { let calls = 0; const config = createConfiguredAIProviderRegistry({ fetchImpl: async () => { calls += 1; return httpResponse(200); }, env: { OSAAH_AI_PROVIDER_ENABLED: 'false' } }); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.DISABLED); assert.equal(calls, 0); });
  await t.test('global AI switch overrides an enabled provider', async () => { let calls = 0; const config = configured(async () => { calls += 1; return httpResponse(200); }, { OSAAH_AI_ENABLED: 'false' }); assert.equal(config.globalEnabled, false); assert.equal(config.enabled, false); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.DISABLED); assert.equal(calls, 0); });
  await t.test('enabled provider rejects missing credentials', () => { assert.throws(() => createConfiguredAIProviderRegistry({ env: { OSAAH_AI_PROVIDER_ENABLED: 'true', OSAAH_AI_MODEL_ID: 'approved-model' } }), (error) => error.code === AI_PROVIDER_ERRORS.CONFIGURATION); });
  await t.test('normalizes rejected credentials', async () => { const config = configured(async () => httpResponse(401)); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.CONFIGURATION && !JSON.stringify(error).includes('test-only-key')); });
  await t.test('aborts and normalizes timeout', async () => { const config = configured((_url, options) => new Promise((_resolve, reject) => options.signal.addEventListener('abort', () => reject(new Error('aborted')))), { OSAAH_AI_PROVIDER_TIMEOUT_MS: '5' }); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.TIMEOUT); });
  await t.test('normalizes rate limits', async () => { const config = configured(async () => httpResponse(429)); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.RATE_LIMITED); });
  await t.test('normalizes provider outage, retries safely, and preserves deterministic paths', async () => { let calls = 0; const config = configured(async () => { calls += 1; return httpResponse(503); }, { OSAAH_AI_PROVIDER_RETRY_LIMIT: '1' }); await assert.rejects(() => gatewaySetup(config).gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', toolName: 'academic.summary', query: 'Safe summary?', providerRequired: true }), (error) => error.code === 'PROVIDER_UNAVAILABLE' && error.status === 503); assert.equal(calls, 2); const deterministic = await gatewaySetup().gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', toolName: 'academic.summary' }); assert.equal(deterministic.provider.invoked, false); });
  await t.test('rejects invalid provider responses', async () => { const config = configured(async () => httpResponse(200, { status: 'unexpected' })); await assert.rejects(() => config.registry.invoke('openai', 'generate', providerRequest), (error) => error.code === AI_PROVIDER_ERRORS.INVALID_RESPONSE); });
  await t.test('gateway minimizes fields before the live adapter', async () => { let sent; const config = configured(async (_url, options) => { sent = JSON.parse(options.body); return httpResponse(200); }); await gatewaySetup(config).gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', toolName: 'academic.summary', query: 'Safe summary?', providerRequired: true }); const serialized = JSON.stringify(sent); assert.equal(serialized.includes('remove'), false); assert.equal(serialized.includes('test-row'), false); assert.equal(serialized.includes('password'), false); assert.equal(sent.store, false); });
  await t.test('audit records safe provider metadata without prompt or secret', async () => { const config = configured(async () => httpResponse(200)); const system = gatewaySetup(config); await system.gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', toolName: 'academic.summary', query: 'Private prompt marker', providerRequired: true, requestId: 'audit-request', correlationId: 'audit-correlation' }); const events = system.auditLogger.recent({ limit: 100 }); const serialized = JSON.stringify(events); assert.equal(serialized.includes('Private prompt marker'), false); assert.equal(serialized.includes('test-only-key'), false); assert.ok(events.some((event) => event.eventType === 'AI_PROVIDER_RESPONSE' && event.provider === 'openai' && event.tokenUsage.totalTokens === 11), serialized); });
  await t.test('WRITE remains globally disabled', async () => { assert.throws(() => createAIToolRegistry().register({ name: 'academic.write', capabilityId: 'academic', description: 'Forbidden write.', operationType: 'WRITE', requiredPermission: 'academics.read', inputSchema: { type: 'object' }, outputSchema: { type: 'object' }, productionDataOnly: true, schoolScoped: true, dataQualityAware: true, auditRequired: true, enabled: true }), /cannot be enabled/); assert.equal(new AIGatewayError('WRITE_DISABLED').code, 'WRITE_DISABLED'); const malicious = { ...responseValue, output: [{ type: 'function_call', call_id: 'call-1', name: 'academic.write', arguments: '{}' }] }; const config = configured(async () => httpResponse(200, malicious)); await assert.rejects(() => gatewaySetup(config).gateway.execute({ authenticatedUser: actor(), capabilityId: 'academic', toolName: 'academic.summary', query: 'Write data', providerRequired: true }), (error) => error.code === 'INVALID_REQUEST'); });
  await t.test('authenticated Gateway security path is mandatory', async () => { let calls = 0; const config = configured(async () => { calls += 1; return httpResponse(200); }); await assert.rejects(() => gatewaySetup(config).gateway.execute({ capabilityId: 'academic', toolName: 'academic.summary', query: 'Bypass', providerRequired: true }), (error) => error.code === 'UNAUTHENTICATED'); assert.equal(calls, 0); });
  await t.test('deterministic mock provider remains regression-free', async () => { const provider = new DeterministicMockAIProvider(); assert.deepEqual(await provider.generate(providerRequest), await provider.generate(providerRequest)); });
});
