import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { createInMemoryMigrationAdapter, createMigrationRunner, discoverMigrations } from '../src/platform/migration-runner.js';

async function fixture(files = { '002_second.sql': 'CREATE TABLE second (id TEXT);', '001_first.sql': 'CREATE TABLE first (id TEXT);' }) { const directory = await mkdtemp(join(tmpdir(), 'osaah-migrations-')); for (const [name, sql] of Object.entries(files)) await writeFile(join(directory, name), sql); return directory; }
test('production migration runner', async (t) => {
  const directories = []; t.after(async () => Promise.all(directories.map((directory) => rm(directory, { recursive: true, force: true })))); const make = async (files) => { const directory = await fixture(files); directories.push(directory); return directory; };
  await t.test('discovers numeric migrations in order', async () => { const migrations = await discoverMigrations(await make()); assert.deepEqual(migrations.map((item) => item.version), [1, 2]); assert.match(migrations[0].checksum, /^[a-f0-9]{64}$/); });
  await t.test('applies pending migrations on first run', async () => { const adapter = createInMemoryMigrationAdapter(), runner = createMigrationRunner({ adapter, directory: await make(), clock: () => '2026-09-05T00:00:00Z' }); const result = await runner.apply(); assert.deepEqual(result.applied.map((item) => item.version), [1, 2]); assert.equal(adapter.storage.statements.length, 2); });
  await t.test('repeat apply is idempotent', async () => { const adapter = createInMemoryMigrationAdapter(), runner = createMigrationRunner({ adapter, directory: await make() }); await runner.apply(); assert.equal((await runner.apply()).applied.length, 0); assert.equal(adapter.storage.statements.length, 2); });
  await t.test('rolls back a failed migration transaction', async () => { const base = createInMemoryMigrationAdapter(), adapter = { ...base, execute: async (sql) => { if (sql.includes('second')) throw new Error('private database error'); return base.execute(sql); } }, runner = createMigrationRunner({ adapter, directory: await make() }); await assert.rejects(() => runner.apply(), (error) => error.code === 'MIGRATION_FAILED' && !error.message.includes('private')); assert.equal(base.storage.applied.length, 1); assert.equal(base.storage.statements.length, 1); });
  await t.test('rejects checksum changes after apply', async () => { const directory = await make(), adapter = createInMemoryMigrationAdapter(), runner = createMigrationRunner({ adapter, directory }); await runner.apply(); await writeFile(join(directory, '001_first.sql'), 'CREATE TABLE changed (id TEXT);'); await assert.rejects(() => runner.status(), (error) => error.code === 'MIGRATION_CHECKSUM_MISMATCH'); });
  await t.test('prevents concurrent migration execution', async () => { const adapter = createInMemoryMigrationAdapter(); assert.equal(await adapter.acquireLock(), true); const runner = createMigrationRunner({ adapter, directory: await make() }); await assert.rejects(() => runner.apply(), (error) => error.code === 'MIGRATION_LOCKED'); await adapter.releaseLock(); });
  await t.test('rejects a missing applied migration', async () => { const storage = { applied: [{ version: 3, name: '003_missing.sql', checksum: 'a'.repeat(64) }] }, runner = createMigrationRunner({ adapter: createInMemoryMigrationAdapter(storage), directory: await make() }); await assert.rejects(() => runner.validate(), (error) => error.code === 'APPLIED_MIGRATION_MISSING'); });
  await t.test('preserves history across adapter restarts', async () => { const storage = {}, directory = await make(); await createMigrationRunner({ adapter: createInMemoryMigrationAdapter(storage), directory }).apply(); const restarted = createMigrationRunner({ adapter: createInMemoryMigrationAdapter(storage), directory }); assert.equal((await restarted.status()).pending.length, 0); });
  await t.test('validates the existing ordered schema including AI migrations', async () => { const directory = new URL('../schema', import.meta.url), migrations = await discoverMigrations(directory); assert.ok(migrations.some((item) => item.name === '018_ai_audit_logs.sql')); assert.ok(migrations.some((item) => item.name === '022_ai_human_controlled_actions.sql')); assert.equal(new Set(migrations.map((item) => item.version)).size, migrations.length); });
  await t.test('fails closed when database health is unavailable', async () => { const base = createInMemoryMigrationAdapter(), adapter = { ...base, healthCheck: async () => ({ healthy: false }) }, runner = createMigrationRunner({ adapter, directory: await make() }); await assert.rejects(() => runner.status(), (error) => error.code === 'DATABASE_UNAVAILABLE'); });
  await t.test('CLI status fails safely without a durable adapter', async () => { const run = promisify(execFile), script = fileURLToPath(new URL('../scripts/migrate.mjs', import.meta.url)); await assert.rejects(() => run(process.execPath, [script, 'status'], { env: { ...process.env, OSAAH_DATABASE_ADAPTER_MODULE: '' } }), (failure) => { const result = JSON.parse(failure.stderr.trim()); return result.error === 'DATABASE_ADAPTER_REQUIRED' && !failure.stderr.includes('at file:'); }); });
});
