import test from 'node:test';
import assert from 'node:assert/strict';
import { createOperationsService } from '../src/operations.js';
import { createResourceService } from '../src/resources.js';
import { createCommunicationService } from '../src/communication.js';
import { createAIToolRegistry, createOperationalAnalyticsRegistry, createOperationalIntelligence, createOperationalTools, createOSAAHModuleManifestRegistry, registerBuiltInOperationalProviders } from '../src/ai/index.js';

const schoolId = 'school-osaah-daylight';
const actor = (permissions = ['*']) => ({ id: 'manager', schoolId, roleKey: 'PROPRIETOR', portal: 'school', permissions: new Set(permissions) });
const modules = [
  { moduleKey: 'transport', enabled: true }, { moduleKey: 'hostel-residences', enabled: true }, { moduleKey: 'inventory', enabled: true },
  { moduleKey: 'assets', enabled: true }, { moduleKey: 'procurement', enabled: true }, { moduleKey: 'property', enabled: true }, { moduleKey: 'announcements', enabled: true }, { moduleKey: 'disabled', enabled: false }
];
function setup({ explain = null } = {}) { const operations = createOperationsService(), resources = createResourceService(), communication = createCommunicationService(), registry = createOperationalAnalyticsRegistry({ modules }); registerBuiltInOperationalProviders(registry, { operations, resources, communication }); return { operations, resources, communication, registry, service: createOperationalIntelligence({ registry, explain, now: () => '2026-09-04T12:00:00.000Z' }) }; }
function futureProvider(overrides = {}) { return { moduleId: 'future-test', capabilityId: 'future-test', requiredPermissions: ['future.read'], productionDataOnly: true, aiEnabled: true, health: 'ACTIVE', supportedMetrics: ['count'], dashboardMetrics: ['count'], dataQualityRules: ['PROVENANCE'], exceptionRules: [], calculate: async () => ({ records: [{ id: 'one', schoolId, provenance: 'PRODUCTION', createdAt: '2026-09-04T10:00:00Z' }] }), summarize: (records) => ({ metrics: { count: records.length }, warnings: [], indicators: [] }), ...overrides }; }

test('dynamic Operational Intelligence', async (t) => {
  await t.test('registers only existing operational capabilities', () => { const { registry } = setup(); assert.deepEqual(registry.list().map((item) => item.capabilityId), ['transport', 'hostel', 'inventory', 'assets', 'procurement', 'maintenance', 'communication']); });
  await t.test('preserves disabled capability health', async () => { const registry = createOperationalAnalyticsRegistry({ modules: [{ moduleKey: 'future-test', enabled: false }] }); registry.register(futureProvider()); const result = await createOperationalIntelligence({ registry }).snapshot({ actor: actor(['future.read']), capabilityId: 'future-test' }); assert.equal(result.status, 'DISABLED'); });
  await t.test('returns UNSUPPORTED for a module without a provider', async () => { const result = await setup().service.snapshot({ actor: actor(), capabilityId: 'library' }); assert.equal(result.status, 'UNSUPPORTED'); });
  await t.test('registers a test-only future capability without AI-core edits', async () => { const registry = createOperationalAnalyticsRegistry({ modules: [{ moduleKey: 'future-test', enabled: true }] }); registry.register(futureProvider()); const result = await createOperationalIntelligence({ registry }).snapshot({ actor: actor(['future.read']), capabilityId: 'future-test' }); assert.equal(result.metrics.count, 1); });
  await t.test('calculates transport metrics from real operations records', async () => { const system = setup(); const vehicle = system.operations.createVehicle({ registration: 'GS-10-26' }, actor()); const route = system.operations.createRoute({ name: 'Bogoso', vehicleId: vehicle.id }, actor()); system.operations.assignTransport({ studentId: 'student-1', routeId: route.id }, actor()); const result = await system.service.snapshot({ actor: actor(), capabilityId: 'transport' }); assert.deepEqual({ vehicles: result.metrics.activeVehicles, routes: result.metrics.activeRoutes, students: result.metrics.assignedStudents }, { vehicles: 1, routes: 1, students: 1 }); });
  await t.test('calculates configured hostel capacity and occupancy', async () => { const system = setup(); const space = system.operations.addHostelSpace({ type: 'DORMITORY', name: 'A', capacity: 2 }, actor()); system.operations.allocateBoarder({ studentId: 'student-1', spaceId: space.id }, actor()); const result = await system.service.snapshot({ actor: actor(), capabilityId: 'hostel' }); assert.equal(result.metrics.capacity, 2); assert.equal(result.metrics.availableSpace, 1); });
  await t.test('does not invent an inventory threshold', async () => { const system = setup(); system.resources.addInventory({ name: 'Chalk' }, actor()); const result = await system.service.snapshot({ actor: actor(), capabilityId: 'inventory' }); assert.equal(result.metrics.lowStockItems, null); assert.match(result.warnings.join(' '), /not configured/i); });
  await t.test('does not invent transport capacity', async () => { const result = await setup().service.snapshot({ actor: actor(), capabilityId: 'transport' }); assert.equal(result.metrics.capacity, null); assert.equal(result.metrics.occupancy, null); });
  await t.test('authorizes every capability independently', async () => { const system = setup(); await system.service.snapshot({ actor: actor(['transport.read']), capabilityId: 'transport' }); await assert.rejects(() => system.service.snapshot({ actor: actor(['transport.read']), capabilityId: 'hostel' }), (error) => error.code === 'PERMISSION_DENIED'); });
  await t.test('excludes TEST and DEMO records', async () => { const registry = createOperationalAnalyticsRegistry({ modules: [{ moduleKey: 'future-test', enabled: true }] }); registry.register(futureProvider({ calculate: async () => ({ records: [{ id: 'p', provenance: 'PRODUCTION' }, { id: 't', provenance: 'TEST' }, { id: 'd', provenance: 'DEMO' }] }) })); const result = await createOperationalIntelligence({ registry }).snapshot({ actor: actor(['future.read']), capabilityId: 'future-test' }); assert.equal(result.metrics.count, 1); assert.equal(result.dataQuality.status, 'PARTIAL'); });
  await t.test('creates neutral operational review indicators', async () => { const registry = createOperationalAnalyticsRegistry({ modules: [{ moduleKey: 'future-test', enabled: true }] }); registry.register(futureProvider({ summarize: (records) => ({ metrics: { count: records.length }, indicators: ['OPERATIONAL_REVIEW_REQUIRED'], warnings: [] }) })); const result = await createOperationalIntelligence({ registry }).snapshot({ actor: actor(['future.read']), capabilityId: 'future-test' }); assert.deepEqual(result.indicators, ['OPERATIONAL_REVIEW_REQUIRED']); });
  await t.test('builds dashboard cards dynamically from authorized providers', async () => { const result = await setup().service.dashboard({ actor: actor(['transport.read']) }); assert.deepEqual(result.cards.map((card) => card.capabilityId), ['transport']); });
  await t.test('denies unknown tools and metrics', async () => { const { registry, service } = setup(); const tools = createAIToolRegistry(createOperationalTools(service, registry)); assert.equal(tools.get('transport.arbitrary-sql'), null); await assert.rejects(() => service.snapshot({ actor: actor(), capabilityId: 'transport', metricIds: ['table.users'] }), (error) => error.code === 'INVALID_REQUEST'); });
  await t.test('exposes no WRITE operational tools', () => { const { registry, service } = setup(); assert.ok(createOperationalTools(service, registry).every((tool) => tool.operationType === 'READ' || tool.operationType === 'ANALYZE')); });
  await t.test('keeps deterministic cards when AI explanation fails', async () => { const system = setup({ explain: async () => { throw new Error('provider outage'); } }); const result = await system.service.dashboard({ actor: actor(['transport.read']) }); assert.equal(result.cards.length, 1); assert.equal(result.explanation, null); });
  await t.test('future manifest and analytics registration need no AI-core modification', async () => { const manifests = createOSAAHModuleManifestRegistry(); const manifest = manifests.register({ id: 'future-test', name: 'Future Test', version: '1.0.0', category: 'OPERATIONS', route: '/future-test', sidebarPlacement: { roles: ['SCHOOL_ADMIN'] }, permissions: ['future.read'], metrics: ['count'], audit: { required: true }, productionData: { classification: 'PRODUCTION' }, dependencies: [], regressionTests: ['future'], ai: { enabled: true, capabilityId: 'future-test', tools: ['future-test.status'], metrics: ['count'], dashboardMetrics: ['count'], health: 'ACTIVE', productionDataOnly: true, dataQualityAware: true } }); const registry = createOperationalAnalyticsRegistry({ modules: [{ moduleKey: manifest.id, enabled: true }] }); registry.register(futureProvider()); assert.equal((await createOperationalIntelligence({ registry }).dashboard({ actor: actor(['future.read']) })).cards[0].metrics.count, 1); });
});
