import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { CORE_LEVELS, createStudentService } from '../src/students.js';
import { createClassDatabaseService } from '../src/class-database.js';
import { SIDEBAR_MODULES, visibleSidebar } from '../src/sidebar-registry.js';

const schoolId = 'school-osaah-daylight';
const roles = ['PROPRIETOR', 'ACCOUNTANT_BURSAR', 'HEADTEACHER', 'ASSISTANT_HEADTEACHER', 'TEACHER'];
const actor = (roleKey, assignedClassIds = CORE_LEVELS) => ({ id: `qa-${roleKey}`, userId: `qa-${roleKey}`, roleKey, portal: 'school', schoolId, permissions: new Set(['students.read']), assignedClassIds: roleKey === 'TEACHER' ? assignedClassIds : [] });
function setup() { const students = createStudentService(); const database = createClassDatabaseService({ students }); return { students, database }; }
function admit(students, input) { return students.createStudent({ ...input, admissionType: 'NEW_ADMISSION', admissionDate: '2026-09-01', academicYearId: '2026/2027', termId: 'First Term' }); }

test('admission automatically appears in the selected current Class Database without manual registration', () => { const { students, database } = setup(); const cases = [{ firstName: 'Test', surname: 'A', classId: 'Nursery 1' }, { firstName: 'Test', surname: 'B', classId: 'Primary 4' }, { firstName: 'Test', surname: 'C', classId: 'JHS 1' }]; for (const input of cases) { const record = admit(students, input); const rows = database.list({ classId: input.classId }, actor('HEADTEACHER')); assert.equal(rows.filter((row) => row.studentId === record.id).length, 1); assert.equal(rows[0].permanentStudentId, record.permanentStudentId); } assert.throws(() => admit(students, { firstName: 'Duplicate', surname: 'Admission', classId: 'Nursery 1', admissionNumber: students.getStudent('STD-000001').admissionNumber }), /Admission number already exists/); });

test('all thirteen canonical classes select only their own current enrollment and support identity search', () => { const { students, database } = setup(); const records = CORE_LEVELS.map((classId, index) => { const record = admit(students, { firstName: 'Class', surname: `Student${index + 1}`, classId }); students.linkParent(record.id, { parentId: `parent-${index}`, fullName: `Parent ${index + 1}`, telephone: `024${String(index + 1).padStart(7, '0')}`, primary: true }); return { record, classId }; }); const staff = actor('HEADTEACHER'); for (const { record, classId } of records) { const rows = database.list({ classId }, staff); assert.equal(rows.length, 1, classId); assert.equal(rows[0].studentId, record.id); assert.equal(rows[0].studentName, `Class Student${CORE_LEVELS.indexOf(classId) + 1}`); assert.match(rows[0].parentGuardianName, /^Parent/); assert.ok(rows[0].registeredParentPhone); assert.equal(database.list({ classId, search: record.permanentStudentId }, staff).length, 1); assert.equal(database.list({ classId, search: 'wrong-name' }, staff).length, 0); } });

test('all authorized roles see the exact Class Database route and can read current and completed projections', () => { const { students, database } = setup(); const current = admit(students, { firstName: 'Role', surname: 'Visible', classId: 'Primary 1' }); const completed = admit(students, { firstName: 'Role', surname: 'Completed', classId: 'JHS 3' }); students.completeStudent(completed.id, { completionYear: '2029', academicYearId: '2028/2029', termId: 'Third Term' }); const module = SIDEBAR_MODULES.find((item) => item.moduleKey === 'class-database'); assert.equal(module.route, '/class-database.html'); for (const roleKey of roles) { const user = actor(roleKey); const group = visibleSidebar({ permissions: user.permissions, roleKey, portal: 'school' }).find((item) => item.category === 'STUDENTS MANAGEMENT' || item.category === 'STUDENT MANAGEMENT'); assert.equal(group.modules.find((item) => item.moduleKey === 'class-database')?.route, '/class-database.html', roleKey); assert.equal(database.list({ classId: 'Primary 1', search: current.permanentStudentId }, user).length, 1); assert.equal(database.listCompleted({ completionYear: '2029', search: completed.permanentStudentId }, user).length, 1); } assert.equal(SIDEBAR_MODULES.find((item) => item.moduleKey === 'completed-class-database')?.route, '/completed-class-database.html'); });

test('parent profile updates are reflected from the canonical relationship without changing student identity', () => { const { students, database } = setup(); const record = admit(students, { firstName: 'Parent', surname: 'Update', classId: 'Primary 3' }); const id = record.permanentStudentId; students.linkParent(record.id, { parentId: 'parent-update', fullName: 'Old Name', telephone: '0244000000', primary: true }); assert.equal(database.list({ classId: 'Primary 3' }, actor('HEADTEACHER'))[0].parentGuardianName, 'Old Name'); students.linkParent(record.id, { parentId: 'parent-update', fullName: 'New Name', telephone: '0205000000', primary: true }); const row = database.list({ classId: 'Primary 3' }, actor('HEADTEACHER'))[0]; assert.equal(row.parentGuardianName, 'New Name'); assert.match(row.registeredParentPhone, /233205|0205/); assert.equal(students.getStudent(record.id).permanentStudentId, id); });

test('security invariants reject parent/public access, cross-school access, and URL-independent API projection access', () => { const { students, database } = setup(); admit(students, { firstName: 'Private', surname: 'Directory', classId: 'Primary 1' }); assert.throws(() => database.list({ classId: 'Primary 1' }, { portal: 'parent', roleKey: 'PARENT', schoolId }), /Forbidden/); assert.throws(() => database.list({ classId: 'Primary 1' }, { roleKey: 'HEADTEACHER', schoolId: 'other-school', permissions: new Set(['students.read']) }), /Forbidden/); assert.throws(() => database.list({ classId: 'Not A Class' }, actor('HEADTEACHER')), /Invalid class/); assert.equal(database.listCompleted({}, actor('HEADTEACHER')).length, 0); });

test('Class Database and archive pages provide responsive safe-scrolling exact table contracts', () => { const current = fs.readFileSync(new URL('../public/class-database.html', import.meta.url), 'utf8'); const archive = fs.readFileSync(new URL('../public/completed-class-database.html', import.meta.url), 'utf8'); const client = fs.readFileSync(new URL('../public/class-database.js', import.meta.url), 'utf8'); assert.match(current, /viewport/); assert.match(current, /overflow-x:auto/); assert.match(current, /Permanent Student ID/); assert.match(current, /Name of Parent\/Guardian/); assert.match(current, /Registered Parent Phone Number/); assert.match(archive, /Completion Year/); assert.match(archive, /Search by ID, Student, Parent, Phone/); assert.match(archive, /Year of Completion/); assert.match(client, /KG 1/); assert.match(client, /KG 2/); assert.doesNotMatch(current, /Coming Soon|Student Profiles|Student Search/); });
