import test from 'node:test';
import assert from 'node:assert/strict';
import { createAdmissionProspectusService } from '../src/admission-prospectus.js';
import { createCommunicationService } from '../src/communication.js';
import { createReportingService } from '../src/reporting.js';
import { createOSAAHModuleManifestRegistry, createSchoolKnowledgeIntelligence, createSchoolKnowledgeTools, syncRepositoryKnowledgeSources } from '../src/ai/index.js';

const schoolId = 'school-osaah-daylight';
const actor = (permissions = ['documents.read'], overrides = {}) => ({ id: 'user-1', schoolId, roleKey: 'SCHOOL_ADMIN', portal: 'school', permissions: new Set(permissions), ...overrides });
const source = (overrides = {}) => ({ sourceId: 'policy-1', schoolId, title: 'Official Attendance Policy', sourceType: 'POLICY', status: 'ACTIVE', authoritative: true, content: 'Learners must attend school punctually every day.', permissionScope: { permissions: ['documents.read'] }, updatedAt: '2026-09-04T10:00:00Z', provenance: 'PRODUCTION', ...overrides });

test('School Knowledge Intelligence', async (t) => {
  await t.test('retrieves an active authoritative source', async () => { const service = createSchoolKnowledgeIntelligence(); assert.equal(service.indexSource(source()).indexed, true); assert.equal((await service.search({ actor: actor(), query: 'attendance punctually' })).answerStatus, 'SUPPORTED_BY_SOURCES'); });
  await t.test('excludes draft sources', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ status: 'DRAFT' })); assert.equal((await service.search({ actor: actor(), query: 'attendance' })).answerStatus, 'NO_AUTHORITATIVE_SOURCE'); });
  await t.test('excludes superseded sources by default', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ status: 'SUPERSEDED' })); assert.equal((await service.search({ actor: actor(), query: 'attendance' })).results.length, 0); });
  await t.test('excludes archived sources', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ status: 'ARCHIVED' })); assert.equal((await service.search({ actor: actor(), query: 'attendance' })).results.length, 0); });
  await t.test('enforces source permission scope', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ permissionScope: { roles: ['PROPRIETOR'] } })); assert.equal((await service.search({ actor: actor(), query: 'punctually' })).results.length, 0); assert.equal((await service.search({ actor: actor([], { roleKey: 'PROPRIETOR' }), query: 'punctually' })).results.length, 1); });
  await t.test('retrieves the published Admission Prospectus', async () => { const manager = actor(['admissions.read', 'admission.prospectus.manage'], { roleKey: 'HEADTEACHER' }); const prospectus = createAdmissionProspectusService({ academicYears: ['2026'] }); const created = prospectus.create({ classId: 'Basic 1', academicYearId: '2026', content: '<h2>Requirements</h2><p>Bring a birth certificate.</p>' }, manager); prospectus.publish(created.id, manager); const service = createSchoolKnowledgeIntelligence(); syncRepositoryKnowledgeSources(service, { actor: manager, admissionProspectus: prospectus }); const result = await service.search({ actor: manager, query: 'birth certificate', sourceTypes: ['ADMISSION_PROSPECTUS'] }); assert.equal(result.results[0].source.sourceType, 'ADMISSION_PROSPECTUS'); });
  await t.test('retrieves authorized academic calendar events', async () => { const user = actor(['communication.read']); const communication = createCommunicationService(); communication.addCalendarEvent({ type: 'REOPENING', title: 'Second term reopening', startsAt: '2026-09-10', audience: 'SCHOOL' }, user); const service = createSchoolKnowledgeIntelligence(); syncRepositoryKnowledgeSources(service, { actor: user, communication }); const result = await service.search({ actor: user, query: 'second term reopening', sourceTypes: ['ACADEMIC_CALENDAR'] }); assert.equal(result.results[0].source.effectiveDate, '2026-09-10'); });
  await t.test('retrieves only authorized official document content', async () => { const user = actor(['documents.read']); const reporting = createReportingService(); reporting.generateOfficialDocument({ type: 'GUIDANCE', title: 'Staff Assembly Guidance', body: 'Assembly begins at seven thirty.' }, user); const service = createSchoolKnowledgeIntelligence(); syncRepositoryKnowledgeSources(service, { actor: user, reporting }); const result = await service.search({ actor: user, query: 'assembly seven thirty', sourceTypes: ['OFFICIAL_DOCUMENT'] }); assert.equal(result.results[0].source.title, 'Staff Assembly Guidance'); });
  await t.test('returns the fixed missing-authority response', async () => { const result = await createSchoolKnowledgeIntelligence().search({ actor: actor(), query: 'What is the drone policy?' }); assert.equal(result.message, 'No current authoritative OSAAH source was found for this information.'); assert.equal(result.dataQuality.status, 'UNAVAILABLE'); });
  await t.test('marks unresolved active-source conflicts partial', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ sourceId: 'one', topicKey: 'uniform', content: 'Uniform colour is blue.' })); service.indexSource(source({ sourceId: 'two', topicKey: 'uniform', content: 'Uniform colour is green.' })); const result = await service.search({ actor: actor(), query: 'uniform colour' }); assert.equal(result.dataQuality.status, 'PARTIAL'); assert.equal(result.conflicts.length, 1); });
  await t.test('preserves citation metadata', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source({ version: '2', effectiveDate: '2026-09-01', section: 'Attendance', page: 4 })); const citation = (await service.search({ actor: actor(), query: 'punctually' })).results[0].source; assert.deepEqual({ title: citation.title, version: citation.version, section: citation.section, page: citation.page, chunk: citation.chunk }, { title: 'Official Attendance Policy', version: '2', section: 'Attendance', page: 4, chunk: 1 }); });
  await t.test('rejects secret-bearing and private authentication content', async () => { const service = createSchoolKnowledgeIntelligence(); const indexed = service.indexSource(source({ content: 'API_KEY=do-not-index' })); assert.equal(indexed.indexState, 'REJECTED_PRIVATE_CONTENT'); assert.equal((await service.search({ actor: actor(), query: 'index' })).results.length, 0); });
  await t.test('marks stale and incomplete evidence', async () => { const staleService = createSchoolKnowledgeIntelligence({ now: () => '2026-09-04T12:00:00Z' }); staleService.indexSource(source({ expiresAt: '2026-09-01', extractionComplete: false })); const result = await staleService.search({ actor: actor(), query: 'punctually' }); assert.equal(result.dataQuality.status, 'STALE'); assert.match(result.warnings.join(' '), /incomplete/i); });
  await t.test('re-indexes changed authoritative sources', async () => { const service = createSchoolKnowledgeIntelligence(); service.indexSource(source()); service.updateSource(source({ content: 'Learners assemble at seven thirty.', version: '2' })); assert.equal((await service.search({ actor: actor(), query: 'punctually' })).results.length, 0); assert.equal((await service.search({ actor: actor(), query: 'assemble' })).results[0].source.version, '2'); });
  await t.test('lets a future manifest declare optional knowledge sources', () => { const registry = createOSAAHModuleManifestRegistry(); const manifest = registry.register({ id: 'future-knowledge', name: 'Future Knowledge', version: '1.0.0', category: 'OPERATIONS', route: '/future-knowledge', sidebarPlacement: { roles: ['SCHOOL_ADMIN'] }, permissions: ['future.read'], metrics: ['count'], audit: { required: true }, productionData: { classification: 'PRODUCTION' }, dependencies: [], regressionTests: ['knowledge'], ai: { enabled: true, capabilityId: 'future-knowledge', tools: ['future-knowledge.search'], metrics: ['count'], knowledgeSources: ['future-policy'], productionDataOnly: true, dataQualityAware: true } }); assert.deepEqual(manifest.ai.knowledgeSources, ['future-policy']); });
  await t.test('exposes only controlled READ and ANALYZE retrieval tools', () => { const tools = createSchoolKnowledgeTools(createSchoolKnowledgeIntelligence()); assert.deepEqual(tools.map((tool) => tool.operationType), ['ANALYZE', 'READ', 'READ', 'READ']); assert.ok(tools.every((tool) => tool.operationType !== 'WRITE')); });
  await t.test('keeps deterministic evidence when the provider is unavailable', async () => { const service = createSchoolKnowledgeIntelligence({ explain: async () => { throw new Error('provider outage'); } }); service.indexSource(source()); const result = await service.search({ actor: actor(), query: 'punctually' }); assert.equal(result.results.length, 1); assert.equal(result.explanation, null); });
});
