const HEALTH = Object.freeze({ ACTIVE: 'HEALTHY', HEALTHY: 'HEALTHY', UNKNOWN: 'DEGRADED', DEGRADED: 'DEGRADED', DISABLED: 'UNAVAILABLE', UNAVAILABLE: 'UNAVAILABLE' });
const ERROR_LIMIT = 20;
const clone = (value) => structuredClone(value);
function permitted(actor) { return Boolean(actor?.id && actor?.schoolId && (actor.permissions?.has?.('*') || actor.permissions?.has?.('ai.admin.health.read'))); }
function state(value, fallback = 'UNAVAILABLE') { return HEALTH[String(value ?? '').toUpperCase()] ?? fallback; }
function component(value, fallback = 'HEALTHY') { try { const result = typeof value === 'function' ? value() : value; return Object.freeze({ state: state(result?.state ?? result?.health ?? result, fallback), reason: result?.reason ?? null }); } catch { return Object.freeze({ state: 'UNAVAILABLE', reason: 'HEALTH_CHECK_FAILED' }); } }
async function recentAudit(auditLogger, schoolId) { try { return auditLogger?.recentAsync ? await auditLogger.recentAsync({ schoolId, limit: 100 }) : auditLogger?.recent?.({ schoolId, limit: 100 }) ?? []; } catch { return []; } }
export function createAIAdministration({ enabled = String(process.env.OSAAH_AI_PROVIDER_ENABLED ?? 'false').toLowerCase() === 'true', providerRegistry = null, providerId = process.env.OSAAH_AI_PROVIDER_ID ?? 'openai', modelId = process.env.OSAAH_AI_MODEL_ID ?? 'unconfigured', capabilityRegistry = null, toolRegistry = null, auditLogger = null, components = {}, integrityConfigured = Boolean(process.env.OSAAH_AI_ACTION_INTEGRITY_KEY), cacheTtlMs = 15000, clock = () => Date.now() } = {}) {
  let cache = null;
  async function health({ actor } = {}) {
    if (!permitted(actor)) throw Object.assign(new Error('AI administration health is forbidden.'), { code: 'PERMISSION_DENIED', status: 403 });
    const now = clock(); if (cache && cache.schoolId === actor.schoolId && now - cache.at < cacheTtlMs) return clone(cache.value);
    const capabilities = (capabilityRegistry?.list?.() ?? []).slice(0, 100).map((item) => Object.freeze({ id: item.id, enabled: item.enabled, state: state(item.health, item.enabled === false ? 'UNAVAILABLE' : 'DEGRADED'), dataQualityAware: item.dataQualityAware === true, productionDataOnly: item.productionDataOnly === true }));
    const tools = (toolRegistry?.list?.() ?? []).slice(0, 200), events = await recentAudit(auditLogger, actor.schoolId), completed = events.filter((item) => item.eventType === 'AI_GATEWAY_COMPLETED'), latencies = events.map((item) => item.durationMs).filter(Number.isFinite), tokens = events.reduce((sum, item) => sum + (item.tokenUsage?.totalTokens ?? 0), 0), costs = events.reduce((sum, item) => sum + (Number.isFinite(item.estimatedCost) ? item.estimatedCost : 0), 0);
    let providerHealth = { state: enabled ? 'DEGRADED' : 'UNAVAILABLE', reason: enabled ? 'HEALTH_NOT_CHECKED' : 'PROVIDER_DISABLED' }; if (enabled && providerRegistry?.healthCheck) try { const checked = await providerRegistry.healthCheck(providerId); providerHealth = { state: checked.healthy ? 'HEALTHY' : 'UNAVAILABLE', reason: checked.reason ?? null }; } catch { providerHealth = { state: 'UNAVAILABLE', reason: 'PROVIDER_HEALTH_FAILED' }; }
    const recentErrors = events.filter((item) => item.errorCode).slice(0, ERROR_LIMIT).map((item) => Object.freeze({ timestamp: item.timestamp, code: item.errorCode, capabilityId: item.capabilityId, requestStatus: item.requestStatus }));
    let auditHealth = { healthy: false, durable: false }; try { auditHealth = await auditLogger?.healthCheck?.() ?? auditHealth; } catch {}
    let actionHealth = { healthy: false, durable: false }; try { actionHealth = await components.humanControlledActions?.healthCheck?.() ?? actionHealth; } catch {}
    const value = Object.freeze({ generatedAt: new Date(now).toISOString(), globalAI: Object.freeze({ enabled, state: enabled ? 'HEALTHY' : 'UNAVAILABLE' }), provider: Object.freeze({ providerId, modelId, ...providerHealth }), gateway: component(components.gateway), orchestrator: component(components.orchestrator, enabled ? 'HEALTHY' : 'DEGRADED'), capabilityRegistry: Object.freeze({ state: capabilityRegistry ? 'HEALTHY' : 'DEGRADED', registeredCount: capabilities.length, capabilities }), toolRegistry: Object.freeze({ state: toolRegistry ? 'HEALTHY' : 'DEGRADED', registeredCount: tools.length, enabledCount: tools.filter((item) => item.enabled !== false).length }), productionDataGuard: component(components.productionDataGuard), dataQualityGuard: component(components.dataQualityGuard), schoolContext: component(components.schoolContext), auditPersistence: Object.freeze({ state: auditHealth.healthy && auditHealth.durable ? 'HEALTHY' : 'DEGRADED', reason: auditHealth.durable ? (auditHealth.healthy ? null : 'PERSISTENCE_UNAVAILABLE') : 'DURABLE_PERSISTENCE_NOT_CONFIGURED' }), humanControlledActions: Object.freeze({ state: integrityConfigured && actionHealth.healthy && actionHealth.durable ? 'HEALTHY' : 'DEGRADED', reason: !integrityConfigured ? 'INTEGRITY_KEY_NOT_CONFIGURED' : actionHealth.durable ? (actionHealth.healthy ? null : 'PERSISTENCE_UNAVAILABLE') : 'DURABLE_PERSISTENCE_NOT_CONFIGURED' }), metrics: Object.freeze({ requestCount: completed.length, recentEventCount: events.length, averageLatencyMs: latencies.length ? Math.round(latencies.reduce((sum, value) => sum + value, 0) / latencies.length) : null, totalTokens: tokens || null, estimatedCost: costs || null }), recentErrors: Object.freeze(recentErrors) });
    cache = { schoolId: actor.schoolId, at: now, value }; return clone(value);
  }
  return Object.freeze({ health, cacheTtlMs, errorLimit: ERROR_LIMIT });
}
