import { createAIAuthorizationContext, createAIAuthorizationGuard, AIAuthorizationError } from './authorization-guard.js';

const DEFAULT_LIMITS = Object.freeze({ maxMessageChars: 1000, maxHistoryItems: 6, maxHistoryChars: 3000, maxTurns: 20, timeoutMs: 16000, maxCapabilities: 3 });
export const OSAAH_AI_CONVERSATION_ENV = Object.freeze({
  maxMessageChars: 'OSAAH_AI_MAX_MESSAGE_CHARS',
  maxHistoryItems: 'OSAAH_AI_MAX_HISTORY_ITEMS',
  maxHistoryChars: 'OSAAH_AI_MAX_HISTORY_CHARS',
  maxTurns: 'OSAAH_AI_MAX_CONVERSATION_TURNS',
  timeoutMs: 'OSAAH_AI_CONVERSATION_TIMEOUT_MS'
});
const INTENTS = Object.freeze({ academics: ['academic', 'score', 'scores', 'subject', 'result', 'results', 'class'], attendance: ['attendance', 'absent', 'present'], students: ['student', 'students', 'enrolment', 'enrollment'], admissions: ['admission', 'applicant'], finance: ['finance', 'financial', 'fee', 'fees', 'payment', 'debt'], staff: ['staff', 'teacher', 'workforce'], transport: ['transport', 'vehicle', 'route'], hostel: ['hostel', 'boarding'], communication: ['message', 'announcement', 'calendar'], documents: ['document', 'report'] });
const INJECTION = [/ignore (all|any|the|previous).*instruction/i, /bypass.*(permission|authorization|security|guard)/i, /(reveal|show|print|repeat).*(system prompt|system instruction|developer instruction)/i, /(reveal|show|print|give).*(api key|password|secret|access token|session token|database url)/i, /\b(select|insert|update|delete|drop|alter)\b[\s\S]*\b(from|into|table|set)\b/i];
const WRITE = /\b(delete|remove|edit|modify|approve|reject|enrol|enroll|record|save|change)\b[\s\S]*\b(student|score|attendance|payment|fee|staff|application|record|database)\b/i;

export class AIConversationError extends Error {
  constructor(code, message, status = 400, { cause } = {}) { super(message, cause ? { cause } : undefined); this.name = 'AIConversationError'; this.code = code; this.status = status; }
  toJSON() { return { error: this.code, message: this.message }; }
}
function limits(input = {}) { const result = { ...DEFAULT_LIMITS, ...input }; for (const [key, value] of Object.entries(result)) if (!Number.isInteger(value) || value < 1) throw new Error(`${key} must be a positive integer`); return Object.freeze(result); }
export function createAIConversationLimits(environment = process.env) {
  const configured = {};
  for (const [key, name] of Object.entries(OSAAH_AI_CONVERSATION_ENV)) {
    if (environment[name] !== undefined && environment[name] !== '') configured[key] = Number(environment[name]);
  }
  return limits(configured);
}
function authorizedCapabilities(user, capabilityRegistry, toolRegistry) { const context = createAIAuthorizationContext(user), guard = createAIAuthorizationGuard({ capabilityRegistry, toolRegistry }); return capabilityRegistry.list({ enabledOnly: true }).filter((capability) => { try { guard.authorizeCapability(context, capability.id); return true; } catch { return false; } }); }
function suggestionsFor(user, capabilities) { const ids = new Set(capabilities.map((item) => item.id)); const suggestions = []; if (['PROPRIETOR', 'SCHOOL_ADMIN', 'HEADTEACHER', 'ASSISTANT_HEADTEACHER'].includes(user.roleKey) && capabilities.length) suggestions.push('Give me the current school status.'); if (ids.has('finance')) suggestions.push('Summarize the current verified financial status.'); if (ids.has('academics')) suggestions.push(user.roleKey === 'TEACHER' ? 'Which scores in my assigned class are incomplete?' : 'Which academic results are incomplete?'); if (ids.has('attendance')) suggestions.push('Summarize attendance for the current reporting period.'); if (ids.has('admissions')) suggestions.push('Summarize the current admissions pipeline.'); return Object.freeze([...new Set(suggestions)].slice(0, 4)); }
function intentIds(message) { const lower = message.toLowerCase(); return Object.entries(INTENTS).filter(([, words]) => words.some((word) => new RegExp(`\\b${word}\\b`, 'i').test(lower))).map(([id]) => id); }
function publicResponse(result, conversationId, suggestions) { const quality = result.grounding?.quality ?? null; return Object.freeze({ conversationId, status: result.status, explanation: result.narrative ?? (quality?.status === 'UNAVAILABLE' ? 'The requested system data is currently unavailable.' : 'Verified system facts are shown below.'), facts: Object.freeze((result.grounding?.authoritativeToolResults ?? []).map((item) => Object.freeze({ status: item.status, data: item.data, source: item.sourceMetadata ?? null }))), quality: quality ? Object.freeze({ status: quality.status, verifiedComplete: quality.verifiedComplete, completenessPercent: quality.completenessPercent, reportingPeriods: quality.reportingPeriods ?? [], warnings: result.grounding.warnings ?? [] }) : null, unavailable: quality?.status === 'UNAVAILABLE', suggestions }); }

export function createAIConversationService({ gateway, capabilityRegistry, toolRegistry, inputLimits = createAIConversationLimits(), clock = () => new Date().toISOString() } = {}) {
  if (!gateway || !capabilityRegistry || !toolRegistry) throw new Error('AI conversation requires the Gateway and AI registries.'); const bounded = limits(inputLimits); const conversations = new Map();
  function validateMessage(message) { if (typeof message !== 'string' || !message.trim()) throw new AIConversationError('INVALID_MESSAGE', 'Enter a message for the OSAAH AI Assistant.'); if (message.length > bounded.maxMessageChars) throw new AIConversationError('MESSAGE_LIMIT', 'The message is too long.', 413); if (INJECTION.some((pattern) => pattern.test(message))) throw new AIConversationError('PROMPT_REJECTED', 'This request cannot be processed by the OSAAH AI Assistant.', 400); if (WRITE.test(message)) throw new AIConversationError('WRITE_DISABLED', 'AI write operations are disabled.', 403); return message.trim(); }
  function validateHistory(history = []) { if (!Array.isArray(history) || history.length > bounded.maxHistoryItems) throw new AIConversationError('HISTORY_LIMIT', 'Conversation history exceeds the allowed limit.', 413); let chars = 0; for (const item of history) { if (!item || !['user', 'assistant'].includes(item.role) || typeof item.content !== 'string') throw new AIConversationError('INVALID_HISTORY', 'Conversation history is invalid.'); chars += item.content.length; } if (chars > bounded.maxHistoryChars) throw new AIConversationError('HISTORY_LIMIT', 'Conversation history exceeds the allowed limit.', 413); }
  function currentConversation(user, conversationId) { if (!conversationId) { const id = crypto.randomUUID(); const state = { id, userId: user.id, schoolId: user.schoolId, turns: 0, createdAt: clock(), updatedAt: clock() }; conversations.set(id, state); return state; } if (typeof conversationId !== 'string' || !/^[A-Za-z0-9-]{1,80}$/.test(conversationId)) throw new AIConversationError('INVALID_CONVERSATION', 'Conversation reference is invalid.'); const state = conversations.get(conversationId); if (!state || state.userId !== user.id || state.schoolId !== user.schoolId) throw new AIConversationError('CONVERSATION_NOT_FOUND', 'Conversation is unavailable.', 404); return state; }
  function suggestions(authenticatedUser) { try { return suggestionsFor(authenticatedUser, authorizedCapabilities(authenticatedUser, capabilityRegistry, toolRegistry)); } catch (cause) { if (cause instanceof AIAuthorizationError) throw new AIConversationError('UNAUTHENTICATED', 'Authentication is required.', 401); throw cause; } }
  async function send({ authenticatedUser, message, conversationId = null, history = [] } = {}) {
    let authorized; try { authorized = authorizedCapabilities(authenticatedUser, capabilityRegistry, toolRegistry); } catch (cause) { throw new AIConversationError('UNAUTHENTICATED', 'Authentication is required.', 401, { cause }); }
    const clean = validateMessage(message); validateHistory(history); const state = currentConversation(authenticatedUser, conversationId); if (state.turns >= bounded.maxTurns) throw new AIConversationError('CONVERSATION_LIMIT', 'Start a new conversation to continue.', 429);
    const intended = intentIds(clean), known = intended.map((id) => capabilityRegistry.get(id)).filter(Boolean), allowedIds = new Set(authorized.map((item) => item.id)); if (known.some((capability) => !allowedIds.has(capability.id))) throw new AIConversationError('CAPABILITY_UNAVAILABLE', 'That information is not available for your current role.', 403);
    const selected = (known.length ? known.filter((item) => allowedIds.has(item.id)) : authorized.filter((item) => item.id !== 'finance')).slice(0, bounded.maxCapabilities); if (!selected.length) throw new AIConversationError('CAPABILITY_UNAVAILABLE', 'No AI capability is available for your current role.', 403);
    let timer; try { const result = await Promise.race([gateway.execute({ authenticatedUser, capabilityId: selected[0].id, capabilityIds: selected.slice(1).map((item) => item.id), query: clean }), new Promise((_, reject) => { timer = setTimeout(() => reject(new AIConversationError('AI_TIMEOUT', 'The OSAAH AI Assistant took too long to respond.', 504)), bounded.timeoutMs); })]); state.turns += 1; state.updatedAt = clock(); return publicResponse(result, state.id, suggestionsFor(authenticatedUser, authorized)); }
    catch (cause) { if (cause instanceof AIConversationError) throw cause; if (cause?.code === 'WRITE_DISABLED') throw new AIConversationError('WRITE_DISABLED', 'AI write operations are disabled.', 403); if (['PROVIDER_UNAVAILABLE', 'ORCHESTRATION_TIMEOUT'].includes(cause?.code)) throw new AIConversationError('AI_UNAVAILABLE', 'The OSAAH AI Assistant is temporarily unavailable.', 503); throw new AIConversationError(cause?.code === 'PERMISSION_DENIED' ? 'CAPABILITY_UNAVAILABLE' : 'AI_REQUEST_FAILED', cause?.code === 'PERMISSION_DENIED' ? 'That information is not available for your current role.' : 'The OSAAH AI Assistant could not complete the request.', cause?.status ?? 400); }
    finally { clearTimeout(timer); }
  }
  function reset({ authenticatedUser, conversationId } = {}) { if (!authenticatedUser?.id || !authenticatedUser?.schoolId) throw new AIConversationError('UNAUTHENTICATED', 'Authentication is required.', 401); if (!conversationId) throw new AIConversationError('INVALID_CONVERSATION', 'Conversation reference is required.'); const state = currentConversation(authenticatedUser, conversationId); conversations.delete(state.id); return Object.freeze({ reset: true }); }
  return Object.freeze({ send, reset, suggestions, limits: bounded });
}
