CREATE TABLE IF NOT EXISTS inventory_items (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), name TEXT NOT NULL, item_type TEXT NOT NULL, unit TEXT NOT NULL, supplier TEXT, reorder_level INTEGER NOT NULL, quantity INTEGER NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_movements (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), inventory_id TEXT NOT NULL REFERENCES inventory_items(id), movement_type TEXT NOT NULL, quantity INTEGER NOT NULL, delta INTEGER NOT NULL, destination TEXT, performed_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), asset_id TEXT NOT NULL, asset_type TEXT NOT NULL, description TEXT NOT NULL, serial_number TEXT, location TEXT, department TEXT, custodian TEXT, purchase_date TEXT, purchase_value NUMERIC, warranty TEXT, condition TEXT NOT NULL, qr_code TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(school_id, asset_id));
CREATE TABLE IF NOT EXISTS procurement_requests (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), request_number TEXT NOT NULL, item TEXT NOT NULL, quantity INTEGER NOT NULL, supplier TEXT, quotation TEXT, state TEXT NOT NULL, requested_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS school_property (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), name TEXT NOT NULL, property_type TEXT NOT NULL, location TEXT, responsible_officer TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS property_maintenance (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), property_id TEXT NOT NULL REFERENCES school_property(id), title TEXT NOT NULL, details TEXT, responsible_officer TEXT, status TEXT NOT NULL, requested_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_inventory_school ON inventory_items(school_id, item_type);
CREATE INDEX IF NOT EXISTS idx_assets_school ON assets(school_id, location, condition);
CREATE INDEX IF NOT EXISTS idx_procurement_school ON procurement_requests(school_id, state);
