PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS shep_activities (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), title TEXT NOT NULL, activity_type TEXT NOT NULL, academic_year TEXT, term TEXT, activity_date TEXT NOT NULL, start_time TEXT, end_time TEXT, venue TEXT, target_group TEXT, responsible_staff_id TEXT, facilitator TEXT, external_provider TEXT, objective TEXT, description TEXT, pupils_targeted INTEGER NOT NULL DEFAULT 0, number_participating INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'Planned', notes TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shep_activity_participants (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), activity_id TEXT NOT NULL REFERENCES shep_activities(id), student_id TEXT NOT NULL, pgsid TEXT, class_id TEXT, participated INTEGER NOT NULL DEFAULT 1, screening_participation TEXT, outcome_category TEXT, referral_required INTEGER NOT NULL DEFAULT 0, follow_up_status TEXT, remarks TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shep_referrals (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), activity_id TEXT NOT NULL REFERENCES shep_activities(id), student_id TEXT NOT NULL, pgsid TEXT, class_id TEXT, referral_date TEXT NOT NULL, category TEXT NOT NULL, destination TEXT, parent_notification_status TEXT, due_date TEXT, status TEXT NOT NULL DEFAULT 'Pending', outcome_summary TEXT, closed_date TEXT, responsible_staff_id TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shep_activity_attachments (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), activity_id TEXT NOT NULL REFERENCES shep_activities(id), storage_reference TEXT NOT NULL, file_name TEXT, mime_type TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shep_audit_history (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), entity TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, previous_value JSON, new_value JSON, actor_id TEXT REFERENCES users(id), occurred_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_shep_activity_school_context ON shep_activities(school_id, academic_year, term, activity_type, status, activity_date);
CREATE INDEX IF NOT EXISTS idx_shep_participant_school_activity ON shep_activity_participants(school_id, activity_id, student_id);
CREATE INDEX IF NOT EXISTS idx_shep_referral_school_status ON shep_referrals(school_id, status, due_date);
