CREATE TABLE IF NOT EXISTS communication_providers (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), provider_key TEXT NOT NULL, is_active INTEGER NOT NULL DEFAULT 0, is_default INTEGER NOT NULL DEFAULT 0, endpoint TEXT, credentials_secret_ref TEXT, sender_id TEXT, priority INTEGER NOT NULL DEFAULT 100, fallback_provider_id TEXT REFERENCES communication_providers(id), webhook_url TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(school_id, provider_key));
CREATE TABLE IF NOT EXISTS communication_templates (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), template_key TEXT NOT NULL, channel TEXT NOT NULL, body_template TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(school_id, template_key));
CREATE TABLE IF NOT EXISTS communication_trigger_settings (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), trigger_key TEXT NOT NULL, channel TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, template_id TEXT REFERENCES communication_templates(id), provider_id TEXT REFERENCES communication_providers(id), updated_by TEXT REFERENCES users(id), updated_at TEXT NOT NULL, UNIQUE(school_id, trigger_key, channel));
CREATE TABLE IF NOT EXISTS communication_outbox (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), channel TEXT NOT NULL, recipient TEXT NOT NULL, payload_json TEXT NOT NULL, idempotency_key TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT, provider_id TEXT, provider_message_id TEXT, last_error TEXT, created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(school_id, idempotency_key));
CREATE TABLE IF NOT EXISTS communication_messages (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), outbox_id TEXT NOT NULL REFERENCES communication_outbox(id), channel TEXT NOT NULL, provider_id TEXT, provider_message_id TEXT, status TEXT NOT NULL, sent_at TEXT, delivered_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS communication_delivery_logs (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), message_id TEXT NOT NULL REFERENCES communication_messages(id), provider_id TEXT, status TEXT NOT NULL, response_code TEXT, safe_error TEXT, occurred_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_communication_outbox_status ON communication_outbox(school_id, status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_communication_messages_provider ON communication_messages(school_id, provider_message_id);
CREATE INDEX IF NOT EXISTS idx_communication_delivery_logs_message ON communication_delivery_logs(message_id, occurred_at);
