import { randomUUID } from 'node:crypto';

export const STUDENT_STATUSES = ['PRESENT', 'ABSENT', 'LATE', 'EARLY_DEPARTURE', 'EXCUSED_ABSENCE', 'UNEXCUSED_ABSENCE', 'SICK_ABSENCE'];
export const ATTENDANCE_METHODS = ['MANUAL', 'STUDENT_ID', 'QR_CODE', 'BIOMETRIC'];
export function createAttendanceService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', notify = () => {} } = {}) {
  const studentRecords = new Map(); const staffRecords = new Map(); const notificationSettings = new Map();
  function key(entry) { return `${entry.date}:${entry.studentId}:${entry.subjectId ?? 'daily'}`; }
  function saveStudentAttendance(entry, actor, { correction = false, expectedVersion = null } = {}) { if (!STUDENT_STATUSES.includes(entry.status)) throw new Error('Invalid attendance status'); if (!ATTENDANCE_METHODS.includes(entry.method ?? 'MANUAL')) throw new Error('Invalid attendance method'); const recordKey = key(entry); const current = studentRecords.get(recordKey); if (current && !correction) throw new Error('Attendance already recorded'); if (current && expectedVersion !== null && current.version !== expectedVersion) throw new Error('Attendance conflict: server record is newer'); const record = { id: current?.id ?? randomUUID(), schoolId, date: entry.date, classId: entry.classId ?? null, studentId: entry.studentId, subjectId: entry.subjectId ?? null, status: entry.status, method: entry.method ?? 'MANUAL', arrivalTime: entry.arrivalTime ?? null, departureTime: entry.departureTime ?? null, reason: entry.reason ?? null, version: (current?.version ?? 0) + 1, enteredBy: actor.userId, enteredAt: current?.enteredAt ?? now(), updatedAt: now() }; studentRecords.set(recordKey, record); if (record.status === 'ABSENT' || record.status === 'LATE') notify({ type: record.status, studentId: record.studentId, date: record.date }); return { ...record }; }
  function saveBatch(entries, actor, options = {}) { return entries.map((entry) => saveStudentAttendance(entry, actor, options)); }
  function saveStaffAttendance(entry, actor) { const record = { id: randomUUID(), schoolId, staffId: entry.staffId, date: entry.date, type: entry.type, time: entry.time ?? now(), enteredBy: actor.userId, createdAt: now() }; if (!['CHECK_IN', 'CHECK_OUT', 'LATE', 'ABSENT'].includes(record.type)) throw new Error('Invalid staff attendance type'); staffRecords.set(`${record.date}:${record.staffId}:${record.type}`, record); return { ...record }; }
  function summary({ date, classId, subjectId, studentIds } = {}) { const rows = [...studentRecords.values()].filter((record) => record.schoolId === schoolId && (!date || record.date === date) && (!classId || record.classId === classId) && (!subjectId || record.subjectId === subjectId) && (!studentIds || studentIds.includes(record.studentId))); const counts = Object.fromEntries(STUDENT_STATUSES.map((status) => [status, rows.filter((row) => row.status === status).length])); const presentLike = counts.PRESENT + counts.LATE; return { date, total: rows.length, counts, attendancePercentage: rows.length ? Math.round((presentLike / rows.length) * 10000) / 100 : 0, records: rows.map((row) => ({ ...row })) }; }
  function setNotificationSettings(userId, settings) { notificationSettings.set(userId, { absence: Boolean(settings.absence), lateness: Boolean(settings.lateness) }); return { ...notificationSettings.get(userId) }; }
  function getRecord(entry) { return studentRecords.get(key(entry)) ? { ...studentRecords.get(key(entry)) } : null; }
  return { saveStudentAttendance, saveBatch, saveStaffAttendance, summary, setNotificationSettings, getRecord, counts: () => ({ student: studentRecords.size, staff: staffRecords.size }) };
}
