import { randomUUID } from 'node:crypto';
import { STAFF_ATTENDANCE_STATUSES, statusFromStaffAttendanceType } from './staff-leave-reconciliation.js';

export const STUDENT_STATUSES = ['PRESENT', 'ABSENT', 'LATE', 'EARLY_DEPARTURE', 'EXCUSED_ABSENCE', 'UNEXCUSED_ABSENCE', 'SICK_ABSENCE'];
export const ATTENDANCE_METHODS = ['MANUAL', 'STUDENT_ID', 'QR_CODE', 'BIOMETRIC'];
export const ACADEMIC_YEAR_OPTIONS = ['2024/2025', '2025/2026', '2026/2027', '2027/2028', '2028/2029', '2029/2030', '2030/2031'];
export const TERM_OPTIONS = ['1st Term', '2nd Term', '3rd Term'];

function required(value, label) { const result = String(value ?? '').trim(); if (!result) throw new Error(`${label} is required`); return result; }

export function createAttendanceService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', notify = () => {} } = {}) {
  const studentRecords = new Map(); const staffRecords = new Map(); const notificationSettings = new Map(); const listeners = new Set(); let revision = 0;
  function scope(entry) { return { academicYear: String(entry.academicYear ?? 'UNSPECIFIED').trim() || 'UNSPECIFIED', term: String(entry.term ?? 'UNSPECIFIED').trim() || 'UNSPECIFIED' }; }
  function key(entry) { const { academicYear, term } = scope(entry); return `${schoolId}:${academicYear}:${term}:${entry.date}:${entry.classId ?? ''}:${entry.studentId}:${entry.subjectId ?? 'daily'}`; }
  function saveStudentAttendance(entry, actor, { correction = false, expectedVersion = null } = {}) { if (!STUDENT_STATUSES.includes(entry.status)) throw new Error('Invalid attendance status'); if (!ATTENDANCE_METHODS.includes(entry.method ?? 'MANUAL')) throw new Error('Invalid attendance method'); const { academicYear, term } = scope(entry); const recordKey = key({ ...entry, academicYear, term }); const current = studentRecords.get(recordKey); if (current && !correction) throw new Error('Attendance already recorded'); if (current && expectedVersion !== null && current.version !== expectedVersion) throw new Error('Attendance conflict: server record is newer'); const record = { id: current?.id ?? randomUUID(), schoolId, provenance: entry.isTestRecord ? 'TEST' : 'PRODUCTION', isTestRecord: Boolean(entry.isTestRecord), academicYear, term, date: required(entry.date, 'Attendance Date'), classId: entry.classId ?? null, studentId: required(entry.studentId, 'Student'), subjectId: entry.subjectId ?? null, status: entry.status, method: entry.method ?? 'MANUAL', arrivalTime: entry.arrivalTime ?? null, departureTime: entry.departureTime ?? null, reason: entry.reason ?? null, version: (current?.version ?? 0) + 1, enteredBy: actor.userId, enteredAt: current?.enteredAt ?? now(), updatedAt: now() }; studentRecords.set(recordKey, record); if (record.status === 'ABSENT' || record.status === 'LATE') notify({ type: record.status, studentId: record.studentId, date: record.date }); revision += 1; for (const listener of listeners) listener({ type: 'STUDENT_ATTENDANCE_CHANGED', revision, recordId: record.id }); return { ...record }; }
  function saveBatch(entries, actor, options = {}) { return entries.map((entry) => saveStudentAttendance(entry, actor, options)); }
  function staffScope(entry) { const scoped = scope(entry); return { ...scoped, staffId: required(entry.staffId, 'Staff member'), date: required(entry.date, 'Attendance Date') }; }
  function staffKey(entry) { const scoped = staffScope(entry); return `${schoolId}:${scoped.academicYear}:${scoped.term}:${scoped.date}:${scoped.staffId}:${required(entry.type ?? entry.status, 'Attendance status')}`; }
  function saveStaffAttendance(entry, actor, { allowExisting = false } = {}) { const scoped = staffScope(entry); const type = required(entry.type ?? entry.status, 'Attendance status').toUpperCase(); const status = String(entry.status ?? statusFromStaffAttendanceType(type) ?? '').toUpperCase(); if (!STAFF_ATTENDANCE_STATUSES.includes(status)) throw new Error('Invalid staff attendance status'); const recordKey = staffKey({ ...entry, type }); const current = staffRecords.get(recordKey); if (current && !allowExisting) throw new Error('Staff attendance already recorded'); const record = { id: current?.id ?? randomUUID(), schoolId, provenance: 'PRODUCTION', academicYear: scoped.academicYear, term: scoped.term, staffId: scoped.staffId, date: scoped.date, type, status, source: entry.source ?? 'MANUAL', leaveRequestId: entry.leaveRequestId ?? current?.leaveRequestId ?? null, note: entry.note ?? current?.note ?? null, previousStatus: entry.previousStatus ?? current?.previousStatus ?? null, time: entry.time ?? now(), enteredBy: actor.userId, createdAt: current?.createdAt ?? now(), updatedAt: now() }; staffRecords.set(recordKey, record); revision += 1; for (const listener of listeners) listener({ type: 'STAFF_ATTENDANCE_CHANGED', revision, recordId: record.id }); return { ...record }; }
  function upsertStaffAttendance(entry, actor, { forceStatus = false } = {}) { const scoped = staffScope(entry); const status = String(entry.status ?? statusFromStaffAttendanceType(entry.type) ?? '').toUpperCase(); const current = findStaffAttendance({ ...scoped }); const type = String(entry.type ?? status).toUpperCase(); const exact = staffRecords.get(staffKey({ ...entry, ...scoped, type })); if (exact || (forceStatus && current)) { const target = exact ?? current; const previousKey = [...staffRecords.entries()].find(([, row]) => row.id === target.id)?.[0]; const merged = { ...target, ...entry, academicYear: scoped.academicYear, term: scoped.term, staffId: scoped.staffId, date: scoped.date, type, status, source: entry.source ?? target.source, leaveRequestId: entry.leaveRequestId === undefined ? target.leaveRequestId : entry.leaveRequestId, note: entry.note ?? target.note, previousStatus: entry.previousStatus ?? target.previousStatus, updatedAt: now() }; const nextKey = staffKey(merged); if (previousKey && previousKey !== nextKey) staffRecords.delete(previousKey); staffRecords.set(nextKey, merged); return { ...merged }; } return saveStaffAttendance({ ...entry, ...scoped, type, status }, actor); }
  function findStaffAttendance(entry) { const scoped = staffScope(entry); const rows = [...staffRecords.values()].filter((record) => record.schoolId === schoolId && record.academicYear === scoped.academicYear && record.term === scoped.term && record.staffId === scoped.staffId && record.date === scoped.date); const priority = ['PRESENT', 'CHECKED_IN', 'LATE', 'ABSENT', 'ON_LEAVE', 'EXCUSED', 'CHECKED_OUT']; return rows.sort((a, b) => priority.indexOf(a.status) - priority.indexOf(b.status))[0] ?? null; }
  function listStaffRecords(filters = {}) { return [...staffRecords.values()].filter((record) => record.schoolId === schoolId && (!filters.academicYear || record.academicYear === filters.academicYear) && (!filters.term || record.term === filters.term) && (!filters.date || record.date === filters.date) && (!filters.staffId || record.staffId === filters.staffId)).map((record) => ({ ...record })); }
  function staffSummary(filters = {}) { const rows = listStaffRecords(filters); const statuses = Object.fromEntries(STAFF_ATTENDANCE_STATUSES.map((status) => [status, rows.filter((row) => row.status === status).length])); return { ...filters, total: rows.length, counts: statuses, records: rows }; }
  function summary({ academicYear, term, date, classId, subjectId, studentIds } = {}) { const rows = [...studentRecords.values()].filter((record) => record.schoolId === schoolId && (!academicYear || record.academicYear === academicYear) && (!term || record.term === term) && (!date || record.date === date) && (!classId || record.classId === classId) && (!subjectId || record.subjectId === subjectId) && (!studentIds || studentIds.includes(record.studentId))); const counts = Object.fromEntries(STUDENT_STATUSES.map((status) => [status, rows.filter((row) => row.status === status).length])); const presentLike = counts.PRESENT + counts.LATE; return { academicYear, term, date, total: rows.length, counts, attendancePercentage: rows.length ? Math.round((presentLike / rows.length) * 10000) / 100 : 0, records: rows.map((row) => ({ ...row })) }; }
  function setNotificationSettings(userId, settings) { notificationSettings.set(userId, { absence: Boolean(settings.absence), lateness: Boolean(settings.lateness) }); return { ...notificationSettings.get(userId) }; }
  function getRecord(entry) { const record = studentRecords.get(key(entry)); return record ? { ...record } : null; }
  return { saveStudentAttendance, saveBatch, saveStaffAttendance, upsertStaffAttendance, findStaffAttendance, summary, staffSummary, setNotificationSettings, getRecord, listStudentRecords: () => [...studentRecords.values()].map((record) => ({ ...record })), listStaffRecords, subscribe: (listener) => { listeners.add(listener); return () => listeners.delete(listener); }, revision: () => revision, counts: () => ({ student: studentRecords.size, staff: staffRecords.size }) };
}

export default createAttendanceService;
