import { randomUUID } from 'node:crypto';
import { STAFF_ATTENDANCE_STATUSES, statusFromStaffAttendanceType } from './staff-leave-reconciliation.js';

export const STUDENT_STATUSES = ['PRESENT', 'ABSENT', 'LATE', 'EARLY_DEPARTURE', 'EXCUSED_ABSENCE', 'UNEXCUSED_ABSENCE', 'SICK_ABSENCE'];
export const ATTENDANCE_METHODS = ['MANUAL', 'STUDENT_ID', 'QR_CODE', 'BIOMETRIC'];
export const ATTENDANCE_SOURCES = ['MANUAL', 'IMPORT', 'LEAVE_RECONCILIATION', 'SYSTEM', 'SYNC', 'API'];
export const ACADEMIC_YEAR_OPTIONS = ['2024/2025', '2025/2026', '2026/2027', '2027/2028', '2028/2029', '2029/2030', '2030/2031'];
export const TERM_OPTIONS = ['1st Term', '2nd Term', '3rd Term'];
export const STUDENT_REASON_STATUSES = ['ABSENT', 'LATE', 'EARLY_DEPARTURE', 'EXCUSED_ABSENCE', 'UNEXCUSED_ABSENCE', 'SICK_ABSENCE'];
function required(value, label) { const result = String(value ?? '').trim(); if (!result) throw new Error(`${label} is required`); return result; }
function actorId(actor) { return required(actor?.userId ?? actor?.id, 'Authenticated user'); }
function assertSchool(actor, schoolId) { if (actor?.schoolId && actor.schoolId !== schoolId) throw new Error('Forbidden.'); }
function validDate(value) { const result = required(value, 'Attendance Date'); if (!/^\d{4}-\d{2}-\d{2}$/.test(result) || Number.isNaN(Date.parse(`${result}T00:00:00Z`))) throw new Error('Invalid attendance date'); return result; }
function source(value) { const result = String(value ?? 'MANUAL').trim().toUpperCase(); if (!ATTENDANCE_SOURCES.includes(result)) throw new Error('Invalid attendance source'); return result; }
function time(value, label) { if (value == null || value === '') return null; const result = String(value).trim(); if (!/^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/.test(result)) throw new Error(`Invalid ${label}`); return result; }
function staffTime(value) { if (value == null || value === '') return null; const result = String(value).trim(); if (/^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/.test(result)) return result; if (!Number.isNaN(Date.parse(result))) return result; throw new Error('Invalid attendance time'); }
function reason(value, status, requireReasons) { const result = value == null ? '' : String(value).trim(); if (requireReasons && STUDENT_REASON_STATUSES.includes(status) && !result) throw new Error(`Reason is required for ${status}`); return result || null; }
function changed(previous, next) { return previous && ['status', 'reason', 'arrivalTime', 'departureTime'].some((field) => previous[field] !== next[field]); }
export function createAttendanceService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', notify = () => {}, audit = () => {}, requireReasons = false } = {}) {
  const studentRecords = new Map(); const staffRecords = new Map(); const notificationSettings = new Map(); const auditHistory = []; const listeners = new Set(); let revision = 0;
  function scope(entry) { return { academicYear: String(entry.academicYear ?? 'UNSPECIFIED').trim() || 'UNSPECIFIED', term: String(entry.term ?? 'UNSPECIFIED').trim() || 'UNSPECIFIED' }; }
  function key(entry) { const { academicYear, term } = scope(entry); return `${schoolId}:${academicYear}:${term}:${entry.date}:${entry.classId ?? ''}:${entry.studentId}:${entry.subjectId ?? 'daily'}`; }
  function recordAudit(record, previous, actor, action = previous ? 'UPDATE' : 'CREATE') { if (action === 'CREATE' || changed(previous, record)) { const event = { id: randomUUID(), schoolId, attendanceRecordId: record.id, studentOrStaffId: record.studentId ?? record.staffId, previousStatus: previous?.status ?? null, newStatus: record.status, previousReason: previous?.reason ?? null, newReason: record.reason ?? null, changedBy: actorId(actor), changedAt: record.updatedAt, source: record.source, action }; auditHistory.push(event); audit(event); } }
  function saveStudentAttendance(entry, actor, { correction = false, expectedVersion = null } = {}) { assertSchool(actor, schoolId); const id = actorId(actor); const status = required(entry?.status, 'Attendance status').toUpperCase(); if (!STUDENT_STATUSES.includes(status)) throw new Error('Invalid attendance status'); const method = String(entry.method ?? 'MANUAL').toUpperCase(); if (!ATTENDANCE_METHODS.includes(method)) throw new Error('Invalid attendance method'); const { academicYear, term } = scope(entry); const date = validDate(entry.date); const recordKey = key({ ...entry, academicYear, term, date }); const current = studentRecords.get(recordKey); if (current && !correction) throw new Error('Attendance already recorded'); if (current && expectedVersion !== null && current.version !== expectedVersion) throw new Error('Attendance conflict: server record is newer'); const timestamp = now(); const record = { id: current?.id ?? randomUUID(), schoolId, provenance: entry.isTestRecord ? 'TEST' : 'PRODUCTION', isTestRecord: Boolean(entry.isTestRecord), academicYear, term, date, classId: entry.classId ?? null, studentId: required(entry.studentId, 'Student'), subjectId: entry.subjectId ?? null, status, method, arrivalTime: time(entry.arrivalTime, 'arrival time'), departureTime: time(entry.departureTime, 'departure time'), reason: reason(entry.reason, status, requireReasons), version: (current?.version ?? 0) + 1, recordedBy: current?.recordedBy ?? id, recordedAt: current?.recordedAt ?? timestamp, updatedBy: id, updatedAt: timestamp, source: source(entry.source) }; studentRecords.set(recordKey, record); recordAudit(record, current, actor, current ? 'UPDATE' : 'CREATE'); if (status === 'ABSENT' || status === 'LATE') notify({ type: status, studentId: record.studentId, date: record.date }); revision += 1; for (const listener of listeners) listener({ type: 'STUDENT_ATTENDANCE_CHANGED', revision, recordId: record.id }); return { ...record, enteredBy: record.recordedBy, enteredAt: record.recordedAt }; }
  function saveBatch(entries, actor, options = {}) { return entries.map((entry) => saveStudentAttendance(entry, actor, options)); }
  function staffScope(entry) { const scoped = scope(entry); return { ...scoped, staffId: required(entry.staffId, 'Staff member'), date: validDate(entry.date) }; }
  function staffKey(entry) { const scoped = staffScope(entry); return `${schoolId}:${scoped.academicYear}:${scoped.term}:${scoped.date}:${scoped.staffId}:${required(entry.type ?? entry.status, 'Attendance status')}`; }
  function saveStaffAttendance(entry, actor, { allowExisting = false } = {}) { assertSchool(actor, schoolId); const id = actorId(actor); const scoped = staffScope(entry); const type = required(entry.type ?? entry.status, 'Attendance status').toUpperCase(); const status = String(entry.status ?? statusFromStaffAttendanceType(type) ?? '').toUpperCase(); if (!STAFF_ATTENDANCE_STATUSES.includes(status)) throw new Error('Invalid staff attendance status'); const recordKey = staffKey({ ...entry, type, ...scoped }); const current = staffRecords.get(recordKey); if (current && !allowExisting) throw new Error('Staff attendance already recorded'); const timestamp = now(); const record = { id: current?.id ?? randomUUID(), schoolId, provenance: 'PRODUCTION', academicYear: scoped.academicYear, term: scoped.term, staffId: scoped.staffId, date: scoped.date, type, status, source: source(entry.source), leaveRequestId: entry.leaveRequestId ?? current?.leaveRequestId ?? null, note: entry.note ?? current?.note ?? null, previousStatus: entry.previousStatus ?? current?.previousStatus ?? null, time: staffTime(entry.time) ?? timestamp, recordedBy: current?.recordedBy ?? id, recordedAt: current?.recordedAt ?? timestamp, updatedBy: id, updatedAt: timestamp }; staffRecords.set(recordKey, record); recordAudit(record, current, actor, current ? 'UPDATE' : 'CREATE'); revision += 1; for (const listener of listeners) listener({ type: 'STAFF_ATTENDANCE_CHANGED', revision, recordId: record.id }); return { ...record, enteredBy: record.recordedBy, createdAt: record.recordedAt }; }
  function upsertStaffAttendance(entry, actor, { forceStatus = false } = {}) { const scoped = staffScope(entry); const status = String(entry.status ?? statusFromStaffAttendanceType(entry.type) ?? '').toUpperCase(); const current = findStaffAttendance({ ...scoped }); const type = String(entry.type ?? status).toUpperCase(); const exact = staffRecords.get(staffKey({ ...entry, ...scoped, type })); if (exact || (forceStatus && current)) { const target = exact ?? current; const previousKey = [...staffRecords.entries()].find(([, row]) => row.id === target.id)?.[0]; const merged = saveStaffAttendance({ ...target, ...entry, ...scoped, type, status }, actor, { allowExisting: true }); const nextKey = staffKey(merged); if (previousKey && previousKey !== nextKey) staffRecords.delete(previousKey); return merged; } return saveStaffAttendance({ ...entry, ...scoped, type, status }, actor); }
  function findStaffAttendance(entry) { const scoped = staffScope(entry); const rows = [...staffRecords.values()].filter((record) => record.schoolId === schoolId && record.academicYear === scoped.academicYear && record.term === scoped.term && record.staffId === scoped.staffId && record.date === scoped.date); const priority = ['PRESENT', 'CHECKED_IN', 'LATE', 'ABSENT', 'ON_LEAVE', 'EXCUSED', 'CHECKED_OUT']; return rows.sort((a, b) => priority.indexOf(a.status) - priority.indexOf(b.status))[0] ?? null; }
  function listStaffRecords(filters = {}) { return [...staffRecords.values()].filter((record) => record.schoolId === schoolId && (!filters.academicYear || record.academicYear === filters.academicYear) && (!filters.term || record.term === filters.term) && (!filters.date || record.date === filters.date) && (!filters.staffId || record.staffId === filters.staffId)).map((record) => ({ ...record })); }
  function staffSummary(filters = {}) { const rows = listStaffRecords(filters); const statuses = Object.fromEntries(STAFF_ATTENDANCE_STATUSES.map((status) => [status, rows.filter((row) => row.status === status).length])); return { ...filters, total: rows.length, counts: statuses, records: rows }; }
  function summary({ academicYear, term, date, classId, subjectId, studentIds } = {}) { const rows = [...studentRecords.values()].filter((record) => record.schoolId === schoolId && (!academicYear || record.academicYear === academicYear) && (!term || record.term === term) && (!date || record.date === date) && (!classId || record.classId === classId) && (!subjectId || record.subjectId === subjectId) && (!studentIds || studentIds.includes(record.studentId))); const counts = Object.fromEntries(STUDENT_STATUSES.map((status) => [status, rows.filter((row) => row.status === status).length])); const presentLike = counts.PRESENT + counts.LATE; return { academicYear, term, date, total: rows.length, counts, attendancePercentage: rows.length ? Math.round((presentLike / rows.length) * 10000) / 100 : 0, records: rows.map((row) => ({ ...row })) }; }
  function setNotificationSettings(userId, settings) { notificationSettings.set(userId, { absence: Boolean(settings.absence), lateness: Boolean(settings.lateness) }); return { ...notificationSettings.get(userId) }; }
  function getRecord(entry) { const record = studentRecords.get(key(entry)); return record ? { ...record } : null; }
  function listAuditHistory(filters = {}, actor = null) { if (actor) assertSchool(actor, schoolId); return auditHistory.filter((event) => (!filters.attendanceRecordId || event.attendanceRecordId === filters.attendanceRecordId) && (!filters.studentOrStaffId || event.studentOrStaffId === filters.studentOrStaffId)).map((event) => ({ ...event })); }
  return { saveStudentAttendance, saveBatch, saveStaffAttendance, upsertStaffAttendance, findStaffAttendance, summary, staffSummary, setNotificationSettings, getRecord, listStudentRecords: () => [...studentRecords.values()].map((record) => ({ ...record })), listStaffRecords, listAuditHistory, subscribe: (listener) => { listeners.add(listener); return () => listeners.delete(listener); }, revision: () => revision, counts: () => ({ student: studentRecords.size, staff: staffRecords.size }) };
}
export default createAttendanceService;
