import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';

const SESSION_TTL_MS = 30 * 60 * 1000;
const RESET_TTL_MS = 15 * 60 * 1000;
const MAX_ATTEMPTS = 5;
const LOCKOUT_MS = 15 * 60 * 1000;
const GENERIC_LOGIN_ERROR = 'Incorrect username or password.';
export const SCHOOL_PORTAL_ROLE_ALIASES = Object.freeze({ SCHOOL_ADMINISTRATOR: 'SCHOOL_ADMIN', ACCOUNTANT: 'ACCOUNTANT_BURSAR', CLASSROOM_TEACHER: 'TEACHER', PROPRIETOR: 'PROPRIETOR' });
export const SCHOOL_PORTAL_DASHBOARDS = Object.freeze({ PROPRIETOR: '/reports', SCHOOL_ADMIN: '/settings', HEADTEACHER: '/academics', ASSISTANT_HEADTEACHER: '/academics', ACCOUNTANT_BURSAR: '/fees', TEACHER: '/academics' });
export function canonicalRoleKey(roleKey) { return SCHOOL_PORTAL_ROLE_ALIASES[roleKey] ?? roleKey; }

function passwordHash(password, salt = randomBytes(16).toString('hex')) { return `${salt}:${scryptSync(password, salt, 32).toString('hex')}`; }
function passwordMatches(password, stored) { const [salt, expected] = stored.split(':'); const actual = scryptSync(password, salt, 32); return timingSafeEqual(actual, Buffer.from(expected, 'hex')); }

export const DEMO_USERS = [
  { id: 'user-parent-1', username: 'parent@example.com', passwordHash: passwordHash('Parent123!', 'parent-salt'), portal: 'parent', roleKey: 'PARENT', schoolId: 'school-osaah-daylight', permissions: new Set(['children.read', 'communication.read', 'messages.read', 'messages.write', 'calendar.read', 'library.read', 'transport.read', 'hostel.read', 'discipline.read']), children: [{ id: 'student-1', name: 'Ama Mensah', className: 'Primary 4' }, { id: 'student-2', name: 'Kojo Mensah', className: 'Primary 2' }], authorizedStaffIds: ['user-teacher-1'] },
  { id: 'user-proprietor-1', username: 'proprietor@osaah.edu.gh', passwordHash: passwordHash('Proprietor123!', 'proprietor-salt'), portal: 'school', roleKey: 'PROPRIETOR', schoolId: 'school-osaah-daylight', permissions: new Set(['*']) },
  { id: 'user-teacher-1', username: 'teacher@osaah.edu.gh', passwordHash: passwordHash('Teacher123!', 'teacher-salt'), portal: 'school', roleKey: 'TEACHER', schoolId: 'school-osaah-daylight', permissions: new Set(['students.read', 'academics.read', 'attendance.read', 'attendance.write', 'examinations.read', 'marks.write', 'results.read', 'leave.read', 'leave.write', 'staff.professional-development.view', 'communication.read', 'messages.read', 'messages.write', 'discipline.read', 'discipline.write', 'property.request']), assignedStudentIds: ['student-1'], assignedParentIds: ['user-parent-1'] },
  { id: 'user-hr-1', username: 'hr@osaah.edu.gh', passwordHash: passwordHash('HumanResources123!', 'hr-salt'), portal: 'school', roleKey: 'HR_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['staff.read', 'staff.write', 'hr.read', 'hr.write', 'hr.confidential.read', 'leave.read', 'leave.write', 'staff.attendance.read', 'staff.attendance.write']) },
  { id: 'user-examination-1', username: 'exams@osaah.edu.gh', passwordHash: passwordHash('Examination123!', 'examination-salt'), portal: 'school', roleKey: 'EXAMINATION_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['examinations.read', 'examinations.write', 'marks.write', 'results.read', 'results.approve', 'promotion.write']) },
  { id: 'user-admissions-1', username: 'admissions@osaah.edu.gh', passwordHash: passwordHash('Admissions123!', 'admissions-salt'), portal: 'school', roleKey: 'ADMISSIONS_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['students.read', 'admissions.read', 'admissions.write']) },
  { id: 'user-bursar-1', username: 'bursar@osaah.edu.gh', passwordHash: passwordHash('Bursar123!', 'bursar-salt'), portal: 'school', roleKey: 'ACCOUNTANT_BURSAR', schoolId: 'school-osaah-daylight', permissions: new Set(['fees.read', 'fees.write', 'fee.scholarships.view', 'finance.read', 'hr.confidential.read']) },
  { id: 'user-librarian-1', username: 'librarian@osaah.edu.gh', passwordHash: passwordHash('Librarian123!', 'librarian-salt'), portal: 'school', roleKey: 'LIBRARIAN', schoolId: 'school-osaah-daylight', permissions: new Set(['library.read', 'library.write']) },
  { id: 'user-transport-1', username: 'transport@osaah.edu.gh', passwordHash: passwordHash('Transport123!', 'transport-salt'), portal: 'school', roleKey: 'TRANSPORT_MANAGER', schoolId: 'school-osaah-daylight', permissions: new Set(['transport.read', 'transport.write', 'transport.gps.view']) },
  { id: 'user-matron-1', username: 'matron@osaah.edu.gh', passwordHash: passwordHash('Matron12345!', 'matron-salt'), portal: 'school', roleKey: 'HOSTEL_MANAGER_MATRON', schoolId: 'school-osaah-daylight', permissions: new Set(['hostel.read', 'hostel.write', 'hostel.attendance.read']) },
  { id: 'user-health-1', username: 'health@osaah.edu.gh', passwordHash: passwordHash('HealthOfficer123!', 'health-salt'), portal: 'school', roleKey: 'HEALTH_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['health.read', 'health.write']) },
  { id: 'user-counsellor-1', username: 'counsellor@osaah.edu.gh', passwordHash: passwordHash('Counsellor123!', 'counsellor-salt'), portal: 'school', roleKey: 'COUNSELLOR', schoolId: 'school-osaah-daylight', permissions: new Set(['counselling.read', 'counselling.write']) },
  { id: 'user-storekeeper-1', username: 'storekeeper@osaah.edu.gh', passwordHash: passwordHash('Storekeeper123!', 'storekeeper-salt'), portal: 'school', roleKey: 'STOREKEEPER', schoolId: 'school-osaah-daylight', permissions: new Set(['inventory.read', 'inventory.write']) },
  { id: 'user-procurement-1', username: 'procurement@osaah.edu.gh', passwordHash: passwordHash('Procurement123!', 'procurement-salt'), portal: 'school', roleKey: 'PROCUREMENT_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['procurement.read', 'procurement.write']) },
  { id: 'user-property-1', username: 'property@osaah.edu.gh', passwordHash: passwordHash('PropertyManager123!', 'property-salt'), portal: 'school', roleKey: 'PROPERTY_MANAGER', schoolId: 'school-osaah-daylight', permissions: new Set(['assets.read', 'assets.write', 'property.read', 'property.write']) },
  { id: 'user-compliance-1', username: 'compliance@osaah.edu.gh', passwordHash: passwordHash('Compliance123!', 'compliance-salt'), portal: 'school', roleKey: 'COMPLIANCE_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['compliance.read', 'compliance.write', 'documents.read', 'documents.write']) },
  { id: 'user-dpo-1', username: 'dpo@osaah.edu.gh', passwordHash: passwordHash('DataProtection123!', 'dpo-salt'), portal: 'school', roleKey: 'DATA_PROTECTION_OFFICER', schoolId: 'school-osaah-daylight', permissions: new Set(['privacy.read', 'privacy.write', 'documents.read']) }
];

export function createAuthService({ users = DEMO_USERS, now = () => Date.now(), audit = () => {} } = {}) {
  users = users.map((user) => ({ ...user, permissions: new Set(user.permissions), children: user.children?.map((child) => ({ ...child })) }));
  const sessions = new Map(); const attempts = new Map(); const resetTokens = new Map();
  function isActive(user) { return user.is_active !== false && user.isActive !== false && !['DISABLED', 'REVOKED', 'REMOVED', 'SUSPENDED', 'DEACTIVATED'].includes(String(user.accountStatus ?? '').toUpperCase()); }
  function securityEvent(action, user, sessionId = null) { audit({ action, entity: 'Authentication', entityId: user?.id ?? null, userId: user?.id ?? null, roleId: canonicalRoleKey(user?.roleKey), sessionId }); }
  function sanitize(user, sessionId = null) { const roleKey = canonicalRoleKey(user.roleKey); return { id: user.id, username: user.username, portal: user.portal, roleKey, role: roleKey, accountStatus: isActive(user) ? 'ACTIVE' : String(user.accountStatus ?? 'DISABLED').toUpperCase(), schoolId: user.schoolId, sessionId, dashboard: SCHOOL_PORTAL_DASHBOARDS[roleKey] ?? '/', schoolType: user.schoolType, subscription: user.subscription, entitlements: user.entitlements ?? [], featureAvailability: user.featureAvailability ?? [], children: user.children ?? [], authorizedStaffIds: user.authorizedStaffIds ?? [], assignedStudentIds: user.assignedStudentIds ?? [], assignedParentIds: user.assignedParentIds ?? [], assignedClassIds: user.assignedClassIds ?? [], assignedSubjectIds: user.assignedSubjectIds ?? [], assignedDepartmentIds: user.assignedDepartmentIds ?? [] }; }
  function login({ username, password, portal }) {
    const key = String(username ?? '').trim().toLowerCase(); const throttle = attempts.get(key); if (throttle?.lockedUntil > now()) return { ok: false, status: 429, error: 'Too many failed attempts. Try again later.' };
    const user = users.find((candidate) => candidate.username.toLowerCase() === key && candidate.portal === portal);
    if (!user || typeof password !== 'string' || !passwordMatches(password, user.passwordHash) || !isActive(user)) { const next = throttle ?? { count: 0 }; next.count += 1; if (next.count >= MAX_ATTEMPTS) next.lockedUntil = now() + LOCKOUT_MS; attempts.set(key, next); securityEvent('LOGIN_FAILED', user); return { ok: false, status: 401, error: GENERIC_LOGIN_ERROR }; }
    attempts.delete(key); const token = randomBytes(32).toString('hex'); const sessionId = randomUUID(); sessions.set(token, { userId: user.id, sessionId, expiresAt: now() + SESSION_TTL_MS }); securityEvent('LOGIN_SUCCESS', user, sessionId); return { ok: true, token, user: sanitize(user, sessionId), redirectTo: SCHOOL_PORTAL_DASHBOARDS[canonicalRoleKey(user.roleKey)] ?? '/', expiresAt: now() + SESSION_TTL_MS };
  }
  function authenticate(token) { const session = sessions.get(token); if (!session || session.expiresAt <= now()) { if (token) sessions.delete(token); return null; } const user = users.find((candidate) => candidate.id === session.userId); if (!user || !isActive(user)) { sessions.delete(token); if (user) securityEvent('SESSION_REVOKED', user, session.sessionId); return null; } return { ...sanitize(user, session.sessionId), permissions: user.permissions }; }
  function logout(token) { const session = sessions.get(token); if (session) { const user = users.find((candidate) => candidate.id === session.userId); sessions.delete(token); if (user) securityEvent('SESSION_REVOKED', user, session.sessionId); } }
  function setAccountStatus(userId, status) { const user = users.find((candidate) => candidate.id === userId); if (!user) return false; user.is_active = status === true; user.accountStatus = status === true ? 'ACTIVE' : 'DISABLED'; if (!status) for (const [token, session] of sessions) if (session.userId === userId) { sessions.delete(token); securityEvent('ACCOUNT_DISABLED', user, session.sessionId); } return true; }
  function revokeAccount(userId) { return setAccountStatus(userId, false); }
  function requestPasswordReset(username) { const user = users.find((candidate) => candidate.username.toLowerCase() === username.trim().toLowerCase()); if (!user) return { ok: true }; const token = randomUUID(); resetTokens.set(token, { userId: user.id, expiresAt: now() + RESET_TTL_MS }); return { ok: true, token }; }
  function completePasswordReset(token, newPassword) { const reset = resetTokens.get(token); if (!reset || reset.expiresAt <= now() || typeof newPassword !== 'string' || newPassword.length < 10) return { ok: false, error: 'Invalid or expired reset request.' }; const user = users.find((candidate) => candidate.id === reset.userId); if (!user) return { ok: false, error: 'Invalid or expired reset request.' }; user.passwordHash = passwordHash(newPassword); resetTokens.delete(token); for (const [sessionToken, session] of sessions) if (session.userId === user.id) sessions.delete(sessionToken); return { ok: true }; }
  return { login, authenticate, logout, requestPasswordReset, completePasswordReset, setAccountStatus, revokeAccount, sessionTtlMs: SESSION_TTL_MS, genericLoginError: GENERIC_LOGIN_ERROR };
}

export function canAccess(user, permission) { return Boolean(user && (user.permissions.has('*') || user.permissions.has(permission))); }
