import { authorizeFinancial } from './financial-authorization.js';

const PAYMENT_STATUSES = new Set(['COMPLETED', 'POSTED', 'VALID', 'PAID']);
const SOURCE_TYPES = Object.freeze(['FEE_PAYMENT', 'GENERAL_INCOME', 'GENERAL_EXPENSE']);
const cents = (value) => { const raw = String(value ?? '0').trim(); if (!/^\d+(?:\.\d{1,2})?$/.test(raw)) return 0; const [whole, fraction = ''] = raw.split('.'); return Number(whole) * 100 + Number((fraction + '00').slice(0, 2)); };
const amount = (value) => cents(value) / 100;
const sourceRank = { FEE_PAYMENT: 1, GENERAL_INCOME: 2, GENERAL_EXPENSE: 3 };

function asDate(value) { return String(value ?? '').slice(0, 19); }
function normalizeFee(row) { return { transactionId: row.id, sourceType: 'FEE_PAYMENT', sourceId: row.id, date: asDate(row.payment_date ?? row.paymentDate ?? row.created_at), reference: row.payment_reference ?? row.reference_number ?? row.receipt_number ?? row.receiptNumber ?? row.id, description: row.description ?? `${row.fee_type ?? 'Fee'} payment`, category: row.fee_type ?? 'FEE_PAYMENT', studentPermanentId: row.permanent_student_id ?? row.permanentStudentId ?? row.student_id ?? null, studentName: row.student_name ?? row.studentName ?? null, payerOrPayee: row.student_name ?? row.studentName ?? 'Fee payment', paymentMethod: row.payment_method ?? row.method ?? null, moneyIn: amount(row.amount ?? row.amount_paid), moneyOut: 0, academicYear: row.academic_year_id ?? row.academic_year ?? row.academicYear ?? null, term: row.term_id ?? row.term ?? null, status: row.status ?? 'COMPLETED', recordedBy: row.received_by ?? row.entered_by ?? row.enteredBy ?? null, createdAt: row.created_at ?? row.createdAt ?? row.payment_date }; }
function normalizeIncome(row) { return { transactionId: row.id, sourceType: 'GENERAL_INCOME', sourceId: row.id, date: asDate(row.transaction_date ?? row.transactionDate), reference: row.reference_number ?? row.referenceNumber, description: row.description, category: row.custom_category ?? row.customCategory ?? row.income_category ?? row.category, studentPermanentId: null, studentName: null, payerOrPayee: row.payer_or_source ?? row.payerOrSource, paymentMethod: row.payment_method ?? row.paymentMethod, moneyIn: amount(row.amount), moneyOut: 0, academicYear: row.academic_year ?? row.academicYear, term: row.term, status: row.status, recordedBy: row.created_by ?? row.createdBy, createdAt: row.created_at ?? row.createdAt }; }
function normalizeExpense(row) { return { transactionId: row.id, sourceType: 'GENERAL_EXPENSE', sourceId: row.id, date: asDate(row.transaction_date ?? row.transactionDate), reference: row.reference_number ?? row.referenceNumber, description: row.description, category: row.custom_category ?? row.customCategory ?? row.expense_category ?? row.category, studentPermanentId: null, studentName: null, payerOrPayee: row.payee, paymentMethod: row.payment_method ?? row.paymentMethod, moneyIn: 0, moneyOut: amount(row.amount), academicYear: row.academic_year ?? row.academicYear, term: row.term, status: row.status, recordedBy: row.created_by ?? row.createdBy, createdAt: row.created_at ?? row.createdAt }; }

export function createCashbookService({ adapter, fees = null, students = null } = {}) {
  if (!adapter?.query) throw new Error('A durable database adapter is required for Cashbook.');
  async function sourceRows(actor) {
    authorizeFinancial(actor, 'READ', 'cashbook');
    const [feeRows, incomeRows, expenseRows] = await Promise.all([
      adapter.query('SELECT * FROM fee_payments WHERE school_id=?', [actor.schoolId]),
      adapter.query('SELECT * FROM general_income WHERE school_id=?', [actor.schoolId]),
      adapter.query('SELECT * FROM general_expenses WHERE school_id=?', [actor.schoolId])
    ]);
    const studentMap = new Map((students?.listStudents?.({ requestedSchoolId: actor.schoolId, includeTestRecords: true }) ?? []).map((student) => [student.permanentStudentId, [student.firstName, student.middleName, student.surname].filter(Boolean).join(' ')]));
    const entries = [...feeRows.map(normalizeFee), ...incomeRows.filter((row) => String(row.status).toUpperCase() === 'POSTED').map(normalizeIncome), ...expenseRows.filter((row) => String(row.status).toUpperCase() === 'POSTED').map(normalizeExpense)];
    for (const entry of entries) if (entry.sourceType === 'FEE_PAYMENT' && !entry.studentName) entry.studentName = studentMap.get(entry.studentPermanentId) ?? null;
    return entries;
  }
  function matchesBase(entry, filters) { const source = filters.sourceType ? String(filters.sourceType).toUpperCase() : null; const method = filters.paymentMethod ? String(filters.paymentMethod).toUpperCase() : null; const search = String(filters.search ?? '').trim().toLowerCase(); if (filters.academicYear && entry.academicYear !== filters.academicYear) return false; if (filters.term && entry.term !== filters.term) return false; if (source && entry.sourceType !== source) return false; if (method && String(entry.paymentMethod ?? '').toUpperCase() !== method) return false; if (search && ![entry.reference, entry.description, entry.studentPermanentId, entry.studentName, entry.payerOrPayee].some((value) => String(value ?? '').toLowerCase().includes(search))) return false; return true; }
  function order(entries) { return entries.sort((a, b) => asDate(a.date).localeCompare(asDate(b.date)) || (sourceRank[a.sourceType] - sourceRank[b.sourceType]) || String(a.sourceId).localeCompare(String(b.sourceId))); }
  function project(entries, filters = {}) { const base = entries.filter((entry) => matchesBase(entry, filters)); const dateOnly = (entry) => String(entry.date).slice(0, 10); const prior = filters.dateFrom ? base.filter((entry) => dateOnly(entry) < filters.dateFrom) : []; const selected = base.filter((entry) => (!filters.dateFrom || dateOnly(entry) >= filters.dateFrom) && (!filters.dateTo || dateOnly(entry) <= filters.dateTo)); const openingCents = prior.reduce((sum, entry) => sum + Math.round(entry.moneyIn * 100) - Math.round(entry.moneyOut * 100), 0); const ordered = order(selected); let balance = openingCents; const projected = ordered.map((entry) => { balance += Math.round(entry.moneyIn * 100) - Math.round(entry.moneyOut * 100); return { ...entry, runningBalance: balance / 100 }; }); const totalInCents = ordered.reduce((sum, entry) => sum + Math.round(entry.moneyIn * 100), 0); const totalOutCents = ordered.reduce((sum, entry) => sum + Math.round(entry.moneyOut * 100), 0); return { entries: projected, summary: { openingBalance: openingCents / 100, totalMoneyIn: totalInCents / 100, totalMoneyOut: totalOutCents / 100, closingBalance: (openingCents + totalInCents - totalOutCents) / 100 } }; }
  async function getCashbookEntries(filters = {}, actor) { const projection = project(await sourceRows(actor), filters); const pageSize = Math.max(1, Math.min(Number(filters.pageSize) || 50, 100)); const page = Math.max(1, Number(filters.page) || 1); const offset = (page - 1) * pageSize; return { entries: projection.entries.slice(offset, offset + pageSize), summary: projection.summary, page, pageSize, total: projection.entries.length, hasNext: offset + pageSize < projection.entries.length, sourceTypes: [...SOURCE_TYPES] }; }
  async function getCashbookSummary(filters = {}, actor) { return project(await sourceRows(actor), filters).summary; }
  async function getCashbookEntryDetails(sourceType, sourceId, actor) { if (!SOURCE_TYPES.includes(String(sourceType).toUpperCase())) throw Object.assign(new Error('Invalid Cashbook source type.'), { status: 400 }); const entries = (await sourceRows(actor)).filter((entry) => entry.sourceType === String(sourceType).toUpperCase() && entry.sourceId === sourceId); if (!entries.length) throw Object.assign(new Error('Cashbook source not found.'), { status: 404 }); return { source: entries[0], sourceType: entries[0].sourceType, sourceId }; }
  return { getCashbookEntries, getCashbookSummary, getCashbookEntryDetails, sourceTypes: () => [...SOURCE_TYPES] };
}
