import { randomUUID } from 'node:crypto';
export const CALENDAR_TYPES = ['REOPENING', 'VACATION', 'EXAMINATION', 'PTA', 'MEETING', 'EVENT', 'SCHOOL_TRIP', 'HOLIDAY'];
export function createCommunicationService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const announcements = []; const notifications = []; const messages = []; const calendar = []; const preferences = new Map();
  function actorId(actor) { return actor.userId ?? actor.id; }
  function announce(input, actor) { const item = { id: randomUUID(), schoolId, title: input.title, body: input.body, audience: input.audience ?? 'SCHOOL', classId: input.classId ?? null, studentIds: input.studentIds ?? [], emergency: Boolean(input.emergency), senderId: actorId(actor), createdAt: now() }; announcements.push(item); return { ...item }; }
  function listAnnouncements(user) { return announcements.filter((item) => item.schoolId === schoolId && (item.audience === 'SCHOOL' || item.audience === user.roleKey || (item.audience === 'CLASS' && user.assignedClassIds?.includes(item.classId)) || item.studentIds.some((id) => user.children?.some((child) => child.id === id) || user.assignedStudentIds?.includes(id)))).map((item) => ({ ...item })); }
  function notify(input, actor = { userId: 'system' }) { const item = { id: randomUUID(), schoolId, type: input.type, recipientId: input.recipientId, studentId: input.studentId ?? null, title: input.title, body: input.body, status: 'UNREAD', createdAt: now(), createdBy: actorId(actor) }; notifications.push(item); return { ...item }; }
  function listNotifications(user) { return notifications.filter((item) => item.schoolId === schoolId && item.recipientId === user.id && (!item.studentId || user.children?.some((child) => child.id === item.studentId))).map((item) => ({ ...item })); }
  function sendMessage(input, actor, { authorizedStudentIds = [], authorizedParentIds = [], authorizedRecipientIds = [] } = {}) { if (!input.recipientId || !input.studentId || !authorizedStudentIds.includes(input.studentId)) throw new Error('Message is outside the authorized student relationship'); if (actor.roleKey === 'TEACHER' && !authorizedParentIds.includes(input.recipientId)) throw new Error('Recipient is not an authorized parent'); if (actor.roleKey === 'PARENT' && !authorizedRecipientIds.includes(input.recipientId)) throw new Error('Recipient is not an authorized teacher or staff member'); const message = { id: randomUUID(), schoolId, senderId: actorId(actor), recipientId: input.recipientId, studentId: input.studentId, body: input.body, status: 'SENT', createdAt: now() }; messages.push(message); return { ...message }; }
  function listMessages(user, childIds = []) { return messages.filter((item) => item.schoolId === schoolId && (item.senderId === user.id || item.recipientId === user.id) && (!childIds.length || childIds.includes(item.studentId))).map((item) => ({ ...item })); }
  function addCalendarEvent(input, actor) { if (!CALENDAR_TYPES.includes(input.type)) throw new Error('Invalid calendar event type'); const event = { id: randomUUID(), schoolId, type: input.type, title: input.title, startsAt: input.startsAt, endsAt: input.endsAt ?? null, audience: input.audience ?? 'SCHOOL', createdBy: actorId(actor), createdAt: now() }; calendar.push(event); return { ...event }; }
  function listCalendar(user) { return calendar.filter((item) => item.schoolId === schoolId && (item.audience === 'SCHOOL' || item.audience === user.roleKey)).map((item) => ({ ...item })); }
  function setPreferences(userId, settings) { const result = { absence: Boolean(settings.absence), lateness: Boolean(settings.lateness), resultsPublished: Boolean(settings.resultsPublished), feePayment: Boolean(settings.feePayment), outstandingFees: Boolean(settings.outstandingFees), announcements: Boolean(settings.announcements), events: Boolean(settings.events) }; preferences.set(userId, result); return { ...result }; }
  return { announce, listAnnouncements, notify, listNotifications, sendMessage, listMessages, addCalendarEvent, listCalendar, setPreferences, counts: () => ({ announcements: announcements.length, notifications: notifications.length, messages: messages.length, calendar: calendar.length }) };
}
