import { randomUUID } from 'node:crypto';

export const COMMUNICATION_STATUSES = Object.freeze(['QUEUED', 'PENDING', 'SENT', 'DELIVERED', 'FAILED', 'RETRYING', 'CANCELLED']);
const PROVIDERS = new Set(['ARKESel', 'HUBTEL', 'FUTURE']);
const clone = (value) => JSON.parse(JSON.stringify(value));

export function createCommunicationEngine({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', audit = () => {}, fetchImpl = globalThis.fetch } = {}) {
  const providers = new Map(); const outbox = new Map(); const messages = new Map(); const deliveries = [];
  const assertDeveloper = (actor) => { if (actor?.schoolId !== schoolId || actor.roleKey !== 'DEVELOPER') throw Object.assign(new Error('Developer authorization required.'), { status: 403 }); };
  function configure(input, actor) { assertDeveloper(actor); const key = String(input.provider ?? '').toUpperCase(); if (!['ARKESEL', 'HUBTEL', 'FUTURE'].includes(key)) throw new Error('Unsupported provider.'); const id = input.id ?? randomUUID(); const record = { id, schoolId, provider: key, active: Boolean(input.active), isDefault: Boolean(input.isDefault), endpoint: input.endpoint ?? null, credentials: input.credentials ?? null, senderId: input.senderId ?? null, priority: Number(input.priority ?? 100), fallbackProviderId: input.fallbackProviderId ?? null, webhookUrl: input.webhookUrl ?? null, createdAt: now(), updatedAt: now() }; for (const item of providers.values()) if (item.schoolId === schoolId && item.id !== id && record.isDefault) item.isDefault = false; providers.set(id, record); audit({ action: 'COMMUNICATION_PROVIDER_CONFIGURED', actorId: actor.id, provider: key, providerId: id, occurredAt: record.updatedAt }); return safeProvider(record); }
  function safeProvider(record) { const { credentials, ...safe } = record; return { ...safe, credentialsConfigured: Boolean(credentials) }; }
  function listProviders(actor) { if (actor?.schoolId !== schoolId || !['DEVELOPER', 'PROPRIETOR'].includes(actor?.roleKey)) throw Object.assign(new Error('Developer authorization required.'), { status: 403 }); return [...providers.values()].sort((a, b) => a.priority - b.priority).map(safeProvider); }
  async function testConnection(id, actor, { testRecipient = null } = {}) { assertDeveloper(actor); const provider = providers.get(id); if (!provider?.active) throw new Error('Provider is inactive.'); if (!provider.credentials || !provider.endpoint) throw new Error('Provider endpoint and credentials are required.'); if (!fetchImpl) throw new Error('HTTP provider client unavailable.'); const response = await fetchImpl(provider.endpoint, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${provider.credentials}` }, body: JSON.stringify({ to: testRecipient, sender: provider.senderId, text: 'OSAAH communication provider test' }) }); return { ok: response.ok, status: response.status, provider: provider.provider }; }
  function enqueue(input, actor = { id: 'system', schoolId }) { if (actor.schoolId !== schoolId) throw new Error('School scope denied.'); const key = String(input.idempotencyKey ?? '').trim(); if (!key) throw new Error('Idempotency key is required.'); const existing = [...outbox.values()].find((item) => item.schoolId === schoolId && item.idempotencyKey === key); if (existing) return clone(existing); const item = { id: randomUUID(), schoolId, channel: input.channel ?? 'SMS', recipient: input.recipient, payload: input.payload ?? {}, idempotencyKey: key, status: 'QUEUED', attempts: 0, nextAttemptAt: now(), providerId: input.providerId ?? null, providerMessageId: null, lastError: null, createdBy: actor.id, createdAt: now(), updatedAt: now() }; outbox.set(item.id, item); return clone(item); }
  function chooseProvider(preferredId) { const active = [...providers.values()].filter((p) => p.schoolId === schoolId && p.active).sort((a, b) => a.priority - b.priority); return (preferredId && providers.get(preferredId)?.active ? providers.get(preferredId) : active[0]) ?? null; }
  async function process(id, actor = { id: 'system', schoolId }) { const item = outbox.get(id); if (!item) throw new Error('Outbox item not found.'); if (item.status === 'SENT' || item.status === 'DELIVERED' || item.status === 'CANCELLED') return clone(item); const provider = chooseProvider(item.providerId); if (!provider) { item.status = 'FAILED'; item.lastError = 'No active communication provider.'; return clone(item); } item.status = 'PENDING'; item.attempts += 1; try { if (!fetchImpl) throw new Error('Provider client unavailable.'); const response = await fetchImpl(provider.endpoint, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${provider.credentials}` }, body: JSON.stringify({ to: item.recipient, sender: provider.senderId, message: item.payload.body ?? item.payload.text }) }); if (!response.ok) throw new Error(`Provider returned ${response.status}`); const body = await response.json().catch(() => ({})); item.status = 'SENT'; item.providerId = provider.id; item.providerMessageId = body.messageId ?? body.id ?? randomUUID(); item.updatedAt = now(); messages.set(item.id, { id: randomUUID(), schoolId, outboxId: item.id, channel: item.channel, providerId: provider.id, providerMessageId: item.providerMessageId, status: item.status, sentAt: item.updatedAt, deliveredAt: null, createdAt: item.createdAt }); audit({ action: 'COMMUNICATION_SENT', actorId: actor.id, outboxId: item.id, provider: provider.provider, occurredAt: item.updatedAt }); return clone(item); } catch (error) { const fallback = provider.fallbackProviderId && providers.get(provider.fallbackProviderId)?.active; item.status = fallback ? 'RETRYING' : 'FAILED'; item.providerId = fallback ? provider.fallbackProviderId : provider.id; item.lastError = String(error.message).slice(0, 200); item.updatedAt = now(); return clone(item); } }
  function webhook(input) { const message = [...messages.values()].find((item) => item.providerMessageId === input.providerMessageId); if (!message) return { accepted: false }; if (!['SENT', 'DELIVERED', 'FAILED'].includes(input.status)) return { accepted: false }; message.status = input.status; message.deliveredAt = input.status === 'DELIVERED' ? now() : message.deliveredAt; deliveries.push({ id: randomUUID(), schoolId, messageId: message.id, providerId: message.providerId, status: message.status, occurredAt: now() }); const item = outbox.get(message.outboxId); if (item) item.status = message.status; return { accepted: true, status: message.status }; }
  return { configure, listProviders, testConnection, enqueue, process, webhook, listOutbox: (actor) => actor?.roleKey === 'DEVELOPER' ? [...outbox.values()].map(clone) : [], statuses: () => [...COMMUNICATION_STATUSES] };
}
