import { createHash, randomUUID } from 'node:crypto';

export const DOCUMENT_CATEGORIES = ['STUDENT', 'STAFF', 'SCHOOL', 'FINANCIAL', 'EXAMINATION', 'COMPLIANCE', 'POLICY', 'MEETING', 'DEVELOPMENT', 'INSPECTION'];
export const COMPLIANCE_TYPES = ['NASIA_LICENCE', 'NTC_REGISTRATION', 'FIRE_SAFETY', 'CORPORATE_LEGAL', 'SCHOOL_DEVELOPMENT', 'EMIS_CENSUS'];
export const PRIVACY_REQUEST_TYPES = ['ACCESS', 'CORRECTION'];
export function createComplianceService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) {
  const records = []; const inspections = []; const documents = []; const consents = []; const requests = []; const retention = []; const officers = []; const breaches = [];
  const clone = (value) => JSON.parse(JSON.stringify(value)); const scoped = (item) => item.schoolId === schoolId; const actorId = (actor) => actor.id ?? actor.userId;
  function addCompliance(input, actor) { if (!COMPLIANCE_TYPES.includes(input.type)) throw new Error('Invalid compliance type'); const record = { id: randomUUID(), schoolId, type: input.type, licenceNumber: input.licenceNumber ?? null, licenceType: input.licenceType ?? null, issueDate: input.issueDate ?? null, expiryDate: input.expiryDate ?? null, status: input.status ?? 'ACTIVE', recommendations: input.recommendations ?? [], correctiveActions: input.correctiveActions ?? [], createdBy: actorId(actor), createdAt: now() }; records.push(record); return clone(record); }
  function addInspection(input, actor) { const record = { id: randomUUID(), schoolId, complianceId: input.complianceId, inspectedAt: input.inspectedAt ?? now(), rating: input.rating ?? null, recommendations: input.recommendations ?? [], correctiveActions: input.correctiveActions ?? [], inspector: input.inspector ?? null, createdBy: actorId(actor), createdAt: now() }; inspections.push(record); return clone(record); }
  function uploadDocument(input, actor) { if (!DOCUMENT_CATEGORIES.includes(input.category)) throw new Error('Invalid document category'); const content = typeof input.content === 'string' ? input.content : ''; const document = { id: randomUUID(), schoolId, documentNumber: `DOC-${String(documents.length + 1).padStart(6, '0')}`, category: input.category, title: input.title, entityId: input.entityId ?? null, storageKey: `secure/${randomUUID()}`, checksum: createHash('sha256').update(content).digest('hex'), version: 1, expiresAt: input.expiresAt ?? null, accessRoles: input.accessRoles ?? [], verificationCode: randomUUID(), createdBy: actorId(actor), createdAt: now() }; documents.push(document); return clone({ ...document, content: undefined }); }
  function addVersion(documentId, input, actor) { const document = documents.find((item) => item.id === documentId && scoped(item)); if (!document) throw new Error('Document not found'); const content = typeof input.content === 'string' ? input.content : ''; document.version += 1; document.checksum = createHash('sha256').update(content).digest('hex'); document.expiresAt = input.expiresAt ?? document.expiresAt; document.updatedBy = actorId(actor); document.updatedAt = now(); return clone(document); }
  function verifyDocument(code) { const document = documents.find((item) => scoped(item) && item.verificationCode === code); return document ? { authentic: true, documentNumber: document.documentNumber, title: document.title, category: document.category, version: document.version, expiresAt: document.expiresAt } : { authentic: false }; }
  function addConsent(input, actor) { const consent = { id: randomUUID(), schoolId, subjectId: input.subjectId, purpose: input.purpose, granted: Boolean(input.granted), recordedBy: actorId(actor), recordedAt: now() }; consents.push(consent); return clone(consent); }
  function addPrivacyRequest(input, actor) { if (!PRIVACY_REQUEST_TYPES.includes(input.type)) throw new Error('Invalid privacy request type'); const request = { id: randomUUID(), schoolId, type: input.type, subjectId: input.subjectId ?? actorId(actor), details: input.details ?? '', status: 'OPEN', createdBy: actorId(actor), createdAt: now() }; requests.push(request); return clone(request); }
  function addRetention(input, actor) { const policy = { id: randomUUID(), schoolId, dataCategory: input.dataCategory, retentionPeriod: input.retentionPeriod, actionAfterExpiry: input.actionAfterExpiry ?? 'REVIEW', createdBy: actorId(actor), createdAt: now() }; retention.push(policy); return clone(policy); }
  function addOfficer(input, actor) { const officer = { id: randomUUID(), schoolId, userId: input.userId, designation: input.designation ?? 'DATA_PROTECTION_OFFICER', appointedBy: actorId(actor), createdAt: now() }; officers.push(officer); return clone(officer); }
  function addBreach(input, actor) { const breach = { id: randomUUID(), schoolId, discoveredAt: input.discoveredAt ?? now(), description: input.description, severity: input.severity ?? 'MEDIUM', containment: input.containment ?? null, status: 'OPEN', reportedBy: actorId(actor), createdAt: now() }; breaches.push(breach); return clone(breach); }
  function allowedDocument(item, user = {}) { return !item.accessRoles.length || item.accessRoles.includes(user.roleKey) || user.roleKey === 'PROPRIETOR'; }
  function getDocument(id, user = {}) { const document = documents.find((item) => item.id === id && scoped(item) && allowedDocument(item, user)); if (!document) return null; const { verificationCode, ...safe } = document; return clone(safe); }
  function exportCensus(input = {}, format = 'json') { const data = { schoolName: 'OSAAH DAYLIGHT SCH. COM.', location: 'BOGOSO', academicYear: input.academicYear ?? null, learnerCount: Number(input.learnerCount ?? 0), staffCount: Number(input.staffCount ?? 0), classes: input.classes ?? [], generatedAt: now(), note: 'Prepared for school reporting workflows; not an official government portal.' }; if (format === 'csv') return Object.entries(data).map(([key, value]) => `${key},${JSON.stringify(value)}`).join('\n'); return clone(data); }
  function privacyNotice() { return { title: 'OsaaH Daylight School Privacy Notice', school: 'OSAAH DAYLIGHT SCH. COM., BOGOSO', purposes: ['School administration', 'Student welfare', 'Communication', 'Legal and regulatory reporting'], rights: ['Access', 'Correction', 'Privacy complaint'], contact: 'Authorized Data Protection Officer' }; }
  function list(section, user = {}) { const data = { compliance: records, inspections, documents: documents.filter((item) => allowedDocument(item, user)).map(({ verificationCode, ...safe }) => safe), consents, requests, retention, officers, breaches }; return clone(data[section] ?? data); }
  return { addCompliance, addInspection, uploadDocument, addVersion, getDocument, verifyDocument, exportCensus, privacyNotice, addConsent, addPrivacyRequest, addRetention, addOfficer, addBreach, list, counts: () => ({ records: records.length, inspections: inspections.length, documents: documents.length, requests: requests.length, breaches: breaches.length }) };
}
