import { randomUUID } from 'node:crypto';
export const RESULT_STATES = ['DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED', 'PUBLISHED', 'LOCKED'];
export const PROMOTION_DECISIONS = ['PROMOTED', 'REPEAT', 'HOLD', 'TRANSFER', 'GRADUATED'];
export const TIMETABLE_CREATOR_ROLES = Object.freeze(['HEADTEACHER', 'ASSISTANT_HEADTEACHER', 'SCHOOL_ADMIN']);
export const DEFAULT_GRADING = [{ min: 80, grade: 'A', remark: 'Excellent' }, { min: 70, grade: 'B', remark: 'Very good' }, { min: 60, grade: 'C', remark: 'Good' }, { min: 50, grade: 'D', remark: 'Pass' }, { min: 0, grade: 'F', remark: 'Needs support' }];
export function createExaminationService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', students = null, classes = [] } = {}) { const exams = new Map(); const marks = new Map(); const promotions = new Map(); const grading = new Map(); const timetables = new Map();
  function createExamination(input) { const id = `EXAM-${String(exams.size + 1).padStart(4, '0')}`; const exam = { id, schoolId, name: input.name, type: input.type ?? 'TEST', academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, subjects: [], candidates: [], timetable: [], rooms: [], invigilators: [], createdAt: now() }; exams.set(id, exam); return clone(exam); }
  function addExamItem(examId, type, item) { const exam = exams.get(examId); if (!exam || !['subjects', 'candidates', 'timetable', 'rooms', 'invigilators'].includes(type)) throw new Error('Examination item not found'); exam[type].push({ id: randomUUID(), ...item }); return clone(exam); }
  function setGradingSystem(key, boundaries = DEFAULT_GRADING) { if (!boundaries.length || boundaries.some((boundary) => boundary.min < 0 || boundary.min > 100)) throw new Error('Invalid grade boundaries'); grading.set(key, boundaries.sort((a, b) => b.min - a.min)); return clone(boundaries); }
  function calculateMarks(rawMarks, weight = 100, systemKey = 'default') { if (rawMarks < 0 || rawMarks > 100 || weight < 0 || weight > 100) throw new Error('Marks must be between 0 and 100'); const weightedMarks = Math.round(rawMarks * weight) / 100; const boundary = (grading.get(systemKey) ?? DEFAULT_GRADING).find((item) => weightedMarks >= item.min); return { rawMarks, weight, weightedMarks, grade: boundary.grade, comment: boundary.remark }; }
  function enterMarks(input, actor, { correction = false } = {}) { const exam = exams.get(input.examId); if (!exam) throw new Error('Examination not found'); const key = `${input.examId}:${input.studentId}:${input.subjectId}`; const current = marks.get(key); if (current?.state === 'PUBLISHED' || current?.state === 'LOCKED') { if (!correction) throw new Error('Published result is locked'); if (!actor.canCorrect) throw new Error('Authorized correction required'); } const result = { id: current?.id ?? randomUUID(), schoolId, examId: input.examId, studentId: input.studentId, subjectId: input.subjectId, ...calculateMarks(input.rawMarks, input.weight ?? 100, input.gradingSystem), teacherComment: input.teacherComment ?? current?.teacherComment ?? null, state: correction ? 'DRAFT' : current?.state ?? 'DRAFT', version: (current?.version ?? 0) + 1, enteredBy: actor.userId, updatedAt: now() }; marks.set(key, result); return clone(result); }
  function transitionResult(examId, studentId, subjectId, state, actor) { const key = `${examId}:${studentId}:${subjectId}`; const result = marks.get(key); if (!result || !RESULT_STATES.includes(state)) throw new Error('Result not found'); if (RESULT_STATES.indexOf(state) !== RESULT_STATES.indexOf(result.state) + 1) throw new Error(`Invalid result transition from ${result.state} to ${state}`); if ((state === 'APPROVED' || state === 'PUBLISHED') && !actor.canApprove) throw new Error('Approval permission required'); result.state = state; result.updatedAt = now(); return clone(result); }
  function promotionKey(studentId, academicYearId, classId, termId) { return `${studentId}:${academicYearId}:${classId ?? ''}:${termId ?? ''}`; }
  function validatePromotionStudent(studentId, academicYearId, context = {}) { if (!students || !studentId || !academicYearId || !context.termId || !context.classId) throw new Error('Academic year, term, class, and student are required.'); const student = students.getStudent(studentId, { requestedSchoolId: schoolId }); if (!student) throw new Error('Student is not enrolled in this school.'); if (student.isTestRecord && !context.isSample) throw new Error('Sample students cannot be promoted into real enrollment.'); const eligible = students.listEligibleStudents({ requestedSchoolId: schoolId, academicYearId, classId: context.classId, termId: context.termId, includeTestRecords: Boolean(context.isSample) }).some((item) => item.id === studentId); if (!eligible) throw new Error('Student is not enrolled in the selected academic year, class, and term.'); return student; }
  function promote(studentId, academicYearId, decision, actor, comment = null, context = {}) { if (!PROMOTION_DECISIONS.includes(decision)) throw new Error('Invalid promotion decision'); if (actor?.schoolId && actor.schoolId !== schoolId) throw new Error('Forbidden.'); const student = students ? validatePromotionStudent(studentId, academicYearId, context) : null; const key = promotionKey(studentId, academicYearId, context.classId, context.termId); const existing = students ? promotions.get(key) : null; if (existing) { if (existing.decision === decision) return clone(existing); throw new Error('A different promotion decision already exists for this enrollment.'); } const id = randomUUID(); const record = { id, schoolId, studentId, ...(student?.permanentStudentId ? { permanentStudentId: student.permanentStudentId } : {}), academicYearId, classId: context.classId ?? null, termId: context.termId ?? null, decision, comment, isSample: Boolean(context.isSample), decidedBy: actor.userId ?? actor.id, decidedAt: now() }; if (students && decision === 'PROMOTED') { const nextIndex = classes.indexOf(context.classId); const target = context.toClassId ?? context.nextClassId ?? classes[nextIndex + 1]; if (!target || !classes.includes(target) || context.classId === 'JHS 3') throw new Error('Promotion beyond the terminal class is not allowed.'); students.assignClass(studentId, { classId: target, academicYearId: context.nextAcademicYearId ?? academicYearId, termId: context.nextTermId ?? context.termId, reason: 'PROMOTED', promotionId: id }); record.toClassId = target; } else if (students && decision === 'REPEAT') { students.assignClass(studentId, { classId: context.classId, academicYearId: context.nextAcademicYearId ?? academicYearId, termId: context.nextTermId ?? context.termId, reason: 'REPEAT', promotionId: id }); record.toClassId = context.classId; } else if (students && decision === 'GRADUATED') { if (context.classId !== 'JHS 3') throw new Error('Only JHS 3 can be completed.'); students.completeStudent(studentId, { completionYear: context.completionYear ?? context.nextAcademicYearId ?? academicYearId, academicYearId, termId: context.termId }); record.completionYear = String(context.completionYear ?? context.nextAcademicYearId ?? academicYearId); } promotions.set(key, record); return clone(record); }
  function bulkPromote(input = {}, actor) { const decisions = input.decisions ?? []; if (!Array.isArray(decisions) || !decisions.length) throw new Error('Promotion decisions are required.'); const contextFor = (item) => ({ classId: item.classId ?? input.classId, termId: item.termId ?? input.termId, toClassId: item.toClassId ?? input.toClassId, nextClassId: item.nextClassId ?? input.nextClassId, nextAcademicYearId: item.nextAcademicYearId ?? input.nextAcademicYearId, nextTermId: item.nextTermId ?? input.nextTermId, completionYear: item.completionYear ?? input.completionYear, isSample: Boolean(item.isSample ?? input.isSample) }); const prepared = decisions.map((item) => ({ item, context: contextFor(item) })); prepared.forEach(({ item, context }) => { if (!item.studentId) throw new Error('Student is required.'); validatePromotionStudent(item.studentId, item.academicYearId ?? input.academicYearId, context); const existing = promotions.get(promotionKey(item.studentId, item.academicYearId ?? input.academicYearId, context.classId, context.termId)); if (existing && existing.decision !== item.decision) throw new Error('A different promotion decision already exists for this enrollment.'); }); const snapshot = new Map([...promotions.entries()].map(([key, value]) => [key, clone(value)])); try { return students?.withTransaction ? students.withTransaction(() => prepared.map(({ item, context }) => promote(item.studentId, item.academicYearId ?? input.academicYearId, item.decision, actor, item.comment ?? input.comment ?? null, context))) : prepared.map(({ item, context }) => promote(item.studentId, item.academicYearId ?? input.academicYearId, item.decision, actor, item.comment ?? input.comment ?? null, context)); } catch (error) { promotions.clear(); snapshot.forEach((value, key) => promotions.set(key, value)); throw error; } }
  function complete(studentId, input = {}, actor) { if (actor?.schoolId && actor.schoolId !== schoolId) throw new Error('Forbidden.'); const student = students.getStudent(studentId, { requestedSchoolId: schoolId }); if (!student) throw new Error('Student is not enrolled in this school.'); const completed = students.completeStudent(studentId, input); return { studentId, permanentStudentId: completed.permanentStudentId, completionYear: completed.completionYear, status: completed.status }; }
  function report(examId, studentId = null) { return [...marks.values()].filter((result) => result.examId === examId && (!studentId || result.studentId === studentId)).map(clone); }
  function assertTimetableCreator(actor) { if (!TIMETABLE_CREATOR_ROLES.includes(actor?.roleKey)) throw Object.assign(new Error('Timetable management permission required.'), { status: 403 }); }
  function validateTimetable(input, ignoredId = null) { const required = ['academicYearId', 'termId', 'classId', 'examination', 'subjectId', 'date', 'startTime', 'endTime']; for (const field of required) if (!input?.[field]) throw new Error(`${field} is required.`); if (input.startTime >= input.endTime) throw new Error('End time must be after start time.'); const conflict = [...timetables.values()].find((item) => item.id !== ignoredId && item.status !== 'ARCHIVED' && item.academicYearId === input.academicYearId && item.termId === input.termId && item.date === input.date && item.startTime < input.endTime && input.startTime < item.endTime && (item.classId === input.classId || item.venue && input.venue && item.venue === input.venue)); if (conflict) throw Object.assign(new Error('The class or venue already has an examination in this time period.'), { code: 'TIMETABLE_CONFLICT', status: 409 }); }
  function saveTimetable(input, actor) { assertTimetableCreator(actor); validateTimetable(input, input.id); const current = input.id ? timetables.get(input.id) : null; if (input.id && !current) throw new Error('Examination timetable not found.'); if (current?.status === 'PUBLISHED') throw new Error('Published timetables cannot be edited.'); const record = { ...current, ...input, id: current?.id ?? randomUUID(), schoolId, status: 'DRAFT', createdBy: current?.createdBy ?? actor.id ?? actor.userId, updatedBy: actor.id ?? actor.userId, createdAt: current?.createdAt ?? now(), updatedAt: now(), publishedAt: null, publishedBy: null }; timetables.set(record.id, record); return clone(record); }
  function publishTimetable(id, actor) { assertTimetableCreator(actor); const record = timetables.get(id); if (!record) throw new Error('Examination timetable not found.'); record.status = 'PUBLISHED'; record.publishedAt = now(); record.publishedBy = actor.id ?? actor.userId; record.updatedAt = now(); return clone(record); }
  function listTimetables(filters = {}, actor = null) { const creator = TIMETABLE_CREATOR_ROLES.includes(actor?.roleKey); const proprietor = actor?.roleKey === 'PROPRIETOR'; const teacherClasses = actor?.roleKey === 'TEACHER' ? new Set(actor.assignedClassIds ?? []) : null; const parentClasses = actor?.portal === 'parent' ? new Set((actor.children ?? []).flatMap((child) => [child.classId, child.className]).filter(Boolean)) : null; return [...timetables.values()].filter((item) => item.schoolId === (actor?.schoolId ?? schoolId) && (!filters.academicYearId || item.academicYearId === filters.academicYearId) && (!filters.termId || item.termId === filters.termId) && (!filters.classId || item.classId === filters.classId) && (creator || proprietor ? (creator || item.status === 'PUBLISHED') : teacherClasses ? item.status === 'PUBLISHED' && teacherClasses.has(item.classId) : parentClasses ? item.status === 'PUBLISHED' && parentClasses.has(item.classId) : false)).map(clone); }
  function dashboard() { return { examinations: exams.size, marks: marks.size, published: [...marks.values()].filter((mark) => mark.state === 'PUBLISHED').length, promotions: promotions.size }; }
  function promotionOptions(filters = {}, actor = {}) { if (actor?.schoolId && actor.schoolId !== schoolId) throw new Error('Forbidden.'); const academicYearId = String(filters.academicYearId ?? '').trim(); const termId = String(filters.termId ?? '').trim(); const classId = String(filters.classId ?? '').trim(); const allowedClasses = classes.length ? [...classes] : [...new Set(students?.listStudents({ requestedSchoolId: schoolId, includeTestRecords: Boolean(filters.isSample) }).map((item) => item.classId).filter(Boolean))]; const eligible = students?.listEligibleStudents?.({ requestedSchoolId: schoolId, academicYearId, classId, termId, includeTestRecords: Boolean(filters.isSample) }) ?? []; return { classes: allowedClasses, terms: ['First Term', 'Second Term', 'Third Term'], students: eligible.map((item) => ({ id: item.id, name: [item.firstName, item.middleName, item.surname].filter(Boolean).join(' '), permanentStudentId: item.permanentStudentId, classId: item.classId, schoolId: item.schoolId, isTestRecord: Boolean(item.isTestRecord) })) }; }
  return { createExamination, addExamItem, setGradingSystem, calculateMarks, enterMarks, transitionResult, promote, bulkPromote, complete, promotionOptions, report, saveTimetable, publishTimetable, listTimetables, dashboard };
}
function clone(value) { return JSON.parse(JSON.stringify(value)); }
