import { randomUUID } from 'node:crypto';
export const RESULT_STATES = ['DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED', 'PUBLISHED', 'LOCKED'];
export const PROMOTION_DECISIONS = ['PROMOTED', 'REPEAT', 'HOLD', 'TRANSFER', 'GRADUATED'];
export const DEFAULT_GRADING = [{ min: 80, grade: 'A', remark: 'Excellent' }, { min: 70, grade: 'B', remark: 'Very good' }, { min: 60, grade: 'C', remark: 'Good' }, { min: 50, grade: 'D', remark: 'Pass' }, { min: 0, grade: 'F', remark: 'Needs support' }];
export function createExaminationService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const exams = new Map(); const marks = new Map(); const promotions = new Map(); const grading = new Map();
  function createExamination(input) { const id = `EXAM-${String(exams.size + 1).padStart(4, '0')}`; const exam = { id, schoolId, name: input.name, type: input.type ?? 'TEST', academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, subjects: [], candidates: [], timetable: [], rooms: [], invigilators: [], createdAt: now() }; exams.set(id, exam); return clone(exam); }
  function addExamItem(examId, type, item) { const exam = exams.get(examId); if (!exam || !['subjects', 'candidates', 'timetable', 'rooms', 'invigilators'].includes(type)) throw new Error('Examination item not found'); exam[type].push({ id: randomUUID(), ...item }); return clone(exam); }
  function setGradingSystem(key, boundaries = DEFAULT_GRADING) { if (!boundaries.length || boundaries.some((boundary) => boundary.min < 0 || boundary.min > 100)) throw new Error('Invalid grade boundaries'); grading.set(key, boundaries.sort((a, b) => b.min - a.min)); return clone(boundaries); }
  function calculateMarks(rawMarks, weight = 100, systemKey = 'default') { if (rawMarks < 0 || rawMarks > 100 || weight < 0 || weight > 100) throw new Error('Marks must be between 0 and 100'); const weightedMarks = Math.round(rawMarks * weight) / 100; const boundary = (grading.get(systemKey) ?? DEFAULT_GRADING).find((item) => weightedMarks >= item.min); return { rawMarks, weight, weightedMarks, grade: boundary.grade, comment: boundary.remark }; }
  function enterMarks(input, actor, { correction = false } = {}) { const exam = exams.get(input.examId); if (!exam) throw new Error('Examination not found'); const key = `${input.examId}:${input.studentId}:${input.subjectId}`; const current = marks.get(key); if (current?.state === 'PUBLISHED' || current?.state === 'LOCKED') { if (!correction) throw new Error('Published result is locked'); if (!actor.canCorrect) throw new Error('Authorized correction required'); } const result = { id: current?.id ?? randomUUID(), schoolId, examId: input.examId, studentId: input.studentId, subjectId: input.subjectId, ...calculateMarks(input.rawMarks, input.weight ?? 100, input.gradingSystem), teacherComment: input.teacherComment ?? current?.teacherComment ?? null, state: correction ? 'DRAFT' : current?.state ?? 'DRAFT', version: (current?.version ?? 0) + 1, enteredBy: actor.userId, updatedAt: now() }; marks.set(key, result); return clone(result); }
  function transitionResult(examId, studentId, subjectId, state, actor) { const key = `${examId}:${studentId}:${subjectId}`; const result = marks.get(key); if (!result || !RESULT_STATES.includes(state)) throw new Error('Result not found'); if (RESULT_STATES.indexOf(state) !== RESULT_STATES.indexOf(result.state) + 1) throw new Error(`Invalid result transition from ${result.state} to ${state}`); if ((state === 'APPROVED' || state === 'PUBLISHED') && !actor.canApprove) throw new Error('Approval permission required'); result.state = state; result.updatedAt = now(); return clone(result); }
  function promote(studentId, academicYearId, decision, actor, comment = null) { if (!PROMOTION_DECISIONS.includes(decision)) throw new Error('Invalid promotion decision'); const record = { id: randomUUID(), schoolId, studentId, academicYearId, decision, comment, decidedBy: actor.userId, decidedAt: now() }; promotions.set(`${studentId}:${academicYearId}`, record); return clone(record); }
  function report(examId, studentId = null) { return [...marks.values()].filter((result) => result.examId === examId && (!studentId || result.studentId === studentId)).map(clone); }
  function dashboard() { return { examinations: exams.size, marks: marks.size, published: [...marks.values()].filter((mark) => mark.state === 'PUBLISHED').length, promotions: promotions.size }; }
  return { createExamination, addExamItem, setGradingSystem, calculateMarks, enterMarks, transitionResult, promote, report, dashboard };
}
function clone(value) { return JSON.parse(JSON.stringify(value)); }
