import { randomUUID } from 'node:crypto';
export const FEE_TYPES = ['TUITION', 'ADMISSION', 'DEVELOPMENT_LEVY', 'ICT', 'EXAMINATION', 'FEEDING', 'TRANSPORT', 'HOSTEL', 'BOOKS', 'UNIFORM', 'OTHER'];
export const PAYMENT_METHODS = ['CASH', 'MOBILE_MONEY', 'BANK', 'CARD', 'PAYMENT_GATEWAY'];
export function createFeeService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const structures = []; const invoices = new Map(); const payments = new Map(); const adjustments = []; const gateway = new Map();
  function addFee(input) { if (!FEE_TYPES.includes(input.type)) throw new Error('Invalid fee type'); if (input.amount < 0) throw new Error('Fee amount cannot be negative'); const fee = { id: randomUUID(), schoolId, type: input.type, amount: Number(input.amount), academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, classId: input.classId ?? null, studentId: input.studentId ?? null, boardingType: input.boardingType ?? null, optionalService: input.optionalService ?? null }; structures.push(fee); return { ...fee }; }
  function invoice(input) { const lineItems = (input.lineItems ?? []).map((line) => ({ ...line, amount: Number(line.amount) })); const total = lineItems.reduce((sum, line) => sum + line.amount, 0); const record = { id: randomUUID(), invoiceNumber: `INV-${String(invoices.size + 1).padStart(6, '0')}`, schoolId, studentId: input.studentId, parentUserId: input.parentUserId ?? null, lineItems, discount: Number(input.discount ?? 0), total: Math.max(0, total - Number(input.discount ?? 0)), paid: 0, balance: Math.max(0, total - Number(input.discount ?? 0)), status: 'ISSUED', createdAt: now() }; invoices.set(record.invoiceNumber, record); return { ...record }; }
  function pay(input, actor) { if (!PAYMENT_METHODS.includes(input.method)) throw new Error('Invalid payment method'); const record = invoices.get(input.invoiceNumber); if (!record || record.schoolId !== schoolId) throw new Error('Invoice not found'); const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0 || amount > record.balance) throw new Error('Invalid payment amount'); const payment = { id: randomUUID(), receiptNumber: `RCT-${String(payments.size + 1).padStart(6, '0')}`, invoiceNumber: record.invoiceNumber, schoolId, studentId: record.studentId, amount, method: input.method, status: 'VALID', enteredBy: actor.userId, createdAt: now() }; payments.set(payment.receiptNumber, payment); record.paid += amount; record.balance -= amount; record.status = record.balance === 0 ? 'PAID' : 'PART_PAID'; return { ...payment, balance: record.balance }; }
  function changeReceipt(receiptNumber, action, actor, reason) { const payment = payments.get(receiptNumber); if (!payment) throw new Error('Receipt not found'); if (!['CANCEL', 'REVERSE', 'REFUND'].includes(action)) throw new Error('Invalid receipt action'); if (payment.status !== 'VALID') throw new Error('Receipt already changed'); payment.status = action === 'REFUND' ? 'REFUNDED' : action === 'REVERSE' ? 'REVERSED' : 'CANCELLED'; payment.changedBy = actor.userId; payment.changeReason = reason ?? null; payment.changedAt = now(); const record = invoices.get(payment.invoiceNumber); if (record) { record.paid -= payment.amount; record.balance += payment.amount; record.status = record.paid ? 'PART_PAID' : 'ISSUED'; } return { ...payment }; }
  function statement(studentId, parentUserId = null) { const visibleInvoices = [...invoices.values()].filter((item) => item.studentId === studentId && (!parentUserId || item.parentUserId === parentUserId)); const visibleInvoiceNumbers = new Set(visibleInvoices.map((item) => item.invoiceNumber)); return { invoices: visibleInvoices.map((item) => ({ ...item })), payments: [...payments.values()].filter((item) => item.studentId === studentId && (!parentUserId || visibleInvoiceNumbers.has(item.invoiceNumber))).map((item) => ({ ...item })) }; }
  function configureGateway(name, publicConfig) { gateway.set(name, { name, publicConfig: { ...publicConfig } }); return { name, publicConfig: { ...publicConfig } }; }
  return { addFee, invoice, pay, changeReceipt, statement, configureGateway, structures, counts: () => ({ invoices: invoices.size, payments: payments.size }) };
}
