import { randomUUID } from 'node:crypto';
import { assertInputSchool, assertSchoolScope, authorizeFinancial, financialAudit } from './financial-authorization.js';

export const FEE_TYPES = ['TUITION', 'ADMISSION', 'DEVELOPMENT_LEVY', 'ICT', 'EXAMINATION', 'FEEDING', 'TRANSPORT', 'HOSTEL', 'BOOKS', 'UNIFORM', 'OTHER'];
export const PAYMENT_METHODS = ['CASH', 'MOBILE_MONEY', 'BANK', 'CARD', 'PAYMENT_GATEWAY'];

export function createFeeService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', audit = () => {} } = {}) {
  const structures = []; const invoices = new Map(); const payments = new Map(); const gateway = new Map(); const incomes = []; const expenses = []; const listeners = new Set(); let revision = 0;
  const scope = (actor, requested = null) => { if (actor?.schoolId) { assertSchoolScope(actor, requested); if (actor.schoolId !== schoolId) throw Object.assign(new Error('Cross-school financial access is forbidden.'), { status: 403 }); } return schoolId; };
  const changed = (type, record) => { revision += 1; for (const listener of listeners) listener(Object.freeze({ type, revision, schoolId, recordId: record?.id ?? record?.invoiceNumber ?? record?.receiptNumber ?? null })); };
  const inputScope = (actor, input) => { if (actor?.schoolId) assertInputSchool(actor, input); return scope(actor); };

  function addFee(input, actor = null) {
    inputScope(actor, input); if (actor?.schoolId) authorizeFinancial(actor, 'CREATE', 'feeStructures');
    if (!FEE_TYPES.includes(input.type)) throw new Error('Invalid fee type'); if (input.amount < 0) throw new Error('Fee amount cannot be negative');
    const fee = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', type: input.type, amount: Number(input.amount), academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, classId: input.classId ?? null, studentId: input.studentId ?? null, boardingType: input.boardingType ?? null, optionalService: input.optionalService ?? null, status: 'DRAFT' };
    structures.push(fee); changed('FEE_STRUCTURE_CHANGED', fee); if (actor?.schoolId) financialAudit({ audit, actor, action: 'CREATE', entity: 'FeeStructure', entityId: fee.id, transactionReference: fee.id, newValue: fee }); return { ...fee };
  }
  function publishFee(id, actor = null) {
    scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'PUBLISH', 'feeStructures'); const fee = structures.find((item) => item.id === id && item.schoolId === schoolId); if (!fee) throw new Error('Fee structure not found');
    const previous = { ...fee }; fee.status = 'PUBLISHED'; fee.publishedAt = now(); changed('FEE_STRUCTURE_PUBLISHED', fee); if (actor?.schoolId) financialAudit({ audit, actor, action: 'PUBLISH', entity: 'FeeStructure', entityId: fee.id, transactionReference: fee.id, previousValue: previous, newValue: fee }); return { ...fee };
  }
  function invoice(input, actor = null) {
    inputScope(actor, input); if (actor?.schoolId) authorizeFinancial(actor, 'CREATE', 'invoices');
    if (!input?.studentId) throw new Error('Student is required');
    const lineItems = (input.lineItems ?? []).map((line) => ({ ...line, amount: Number(line.amount) })); const total = lineItems.reduce((sum, line) => sum + line.amount, 0);
    const record = { id: randomUUID(), invoiceNumber: `INV-${String(invoices.size + 1).padStart(6, '0')}`, schoolId, provenance: 'PRODUCTION', studentId: input.studentId, parentUserId: input.parentUserId ?? null, academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, lineItems, discount: Number(input.discount ?? 0), total: Math.max(0, total - Number(input.discount ?? 0)), paid: 0, balance: Math.max(0, total - Number(input.discount ?? 0)), status: 'ISSUED', createdAt: now() };
    invoices.set(record.invoiceNumber, record); changed('FEE_LIABILITY_CHANGED', record); if (actor?.schoolId) financialAudit({ audit, actor, action: 'CREATE', entity: 'Invoice', entityId: record.id, transactionReference: record.invoiceNumber, newValue: record }); return { ...record };
  }
  function pay(input, actor) {
    inputScope(actor, input); if (actor?.schoolId) authorizeFinancial(actor, 'CREATE', 'payments'); if (!PAYMENT_METHODS.includes(input.method)) throw new Error('Invalid payment method');
    const record = invoices.get(input.invoiceNumber); if (!record || record.schoolId !== schoolId) throw new Error('Invoice not found'); if (record.lineItems.some((line) => line.type === 'ADMISSION') && input.method === 'CASH') throw new Error('Administrative-desk cash is not permitted for admission fees');
    const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0 || amount > record.balance) throw new Error('Invalid payment amount');
    const payment = { id: randomUUID(), receiptNumber: `RCT-${String(payments.size + 1).padStart(6, '0')}`, invoiceNumber: record.invoiceNumber, schoolId, provenance: 'PRODUCTION', studentId: record.studentId, academicYearId: record.academicYearId, termId: record.termId, amount, method: input.method, status: 'VALID', enteredBy: actor?.id ?? actor?.userId ?? null, createdAt: now() };
    payments.set(payment.receiptNumber, payment); record.paid += amount; record.balance -= amount; record.status = record.balance === 0 ? 'PAID' : 'PART_PAID'; changed('PAYMENT_CONFIRMED', payment); if (actor?.schoolId) financialAudit({ audit, actor, action: 'CREATE', entity: 'Payment', entityId: payment.id, transactionReference: payment.receiptNumber, newValue: payment }); return { ...payment, balance: record.balance };
  }
  function changeReceipt(receiptNumber, action, actor, reason) {
    scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'VOID_REVERSE', 'receipts'); const payment = payments.get(receiptNumber); if (!payment || (actor?.schoolId && payment.schoolId !== actor.schoolId)) throw new Error('Receipt not found'); if (!['CANCEL', 'REVERSE', 'REFUND'].includes(action)) throw new Error('Invalid receipt action'); if (payment.status !== 'VALID') throw new Error('Receipt already changed');
    const previous = { ...payment }; payment.status = action === 'REFUND' ? 'REFUNDED' : action === 'REVERSE' ? 'REVERSED' : 'CANCELLED'; payment.changedBy = actor.id; payment.changeReason = reason ?? null; payment.changedAt = now(); const record = invoices.get(payment.invoiceNumber); if (record) { record.paid -= payment.amount; record.balance += payment.amount; record.status = record.paid ? 'PART_PAID' : 'ISSUED'; }
    changed(action === 'REFUND' ? 'PAYMENT_REFUNDED' : 'PAYMENT_REVERSED', payment); if (actor?.schoolId) financialAudit({ audit, actor, action: 'VOID_REVERSE', entity: 'Receipt', entityId: payment.id, transactionReference: receiptNumber, previousValue: previous, newValue: payment }); return { ...payment };
  }
  function statement(studentId, parentUserId = null, actor = null) { scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'READ', 'studentFees'); const visibleInvoices = [...invoices.values()].filter((item) => item.schoolId === schoolId && item.studentId === studentId && (!parentUserId || item.parentUserId === parentUserId)); const visibleInvoiceNumbers = new Set(visibleInvoices.map((item) => item.invoiceNumber)); return { invoices: visibleInvoices.map((item) => ({ ...item })), payments: [...payments.values()].filter((item) => item.schoolId === schoolId && item.studentId === studentId && (!parentUserId || visibleInvoiceNumbers.has(item.invoiceNumber))).map((item) => ({ ...item })) }; }
  function configureGateway(name, publicConfig, actor = null) { scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'UPDATE', 'fees'); gateway.set(name, { name, publicConfig: { ...publicConfig } }); return { name, publicConfig: { ...publicConfig } }; }
  function recordIncome(input, actor) { inputScope(actor, input); if (actor?.schoolId) authorizeFinancial(actor, 'CREATE', 'fees'); const transaction = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', category: input.category ?? 'OTHER', amount: Number(input.amount), note: input.note ?? null, academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, date: input.date ?? now().slice(0, 10), status: input.status ?? 'VALID', createdBy: actor?.id ?? actor?.userId ?? null, createdAt: now() }; if (!Number.isFinite(transaction.amount) || transaction.amount < 0) throw new Error('Invalid income amount'); incomes.push(transaction); changed('INCOME_RECORDED', transaction); return { ...transaction }; }
  function recordExpense(input, actor) { inputScope(actor, input); if (actor?.schoolId) authorizeFinancial(actor, 'CREATE', 'fees'); const transaction = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', category: input.category ?? 'OTHER', amount: Number(input.amount), note: input.note ?? null, academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, date: input.date ?? now().slice(0, 10), status: input.status ?? 'VALID', createdBy: actor?.id ?? actor?.userId ?? null, createdAt: now() }; if (!Number.isFinite(transaction.amount) || transaction.amount < 0) throw new Error('Invalid expense amount'); expenses.push(transaction); changed('EXPENSE_RECORDED', transaction); return { ...transaction }; }
  function listIncomes({ requestedSchoolId = schoolId } = {}, actor = null) { scope(actor, requestedSchoolId); if (actor?.schoolId) authorizeFinancial(actor, 'READ', 'fees', requestedSchoolId); return incomes.filter((item) => item.schoolId === schoolId).map((item) => ({ ...item })); }
  function listExpenses({ requestedSchoolId = schoolId } = {}, actor = null) { scope(actor, requestedSchoolId); if (actor?.schoolId) authorizeFinancial(actor, 'READ', 'fees', requestedSchoolId); return expenses.filter((item) => item.schoolId === schoolId).map((item) => ({ ...item })); }
  function listInvoices(actor = null) { scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'READ', 'invoices'); return [...invoices.values()].filter((item) => item.schoolId === schoolId).map((item) => ({ ...item, lineItems: item.lineItems.map((line) => ({ ...line })) })); }
  function listPayments(actor = null) { scope(actor); if (actor?.schoolId) authorizeFinancial(actor, 'READ', 'payments'); return [...payments.values()].filter((item) => item.schoolId === schoolId).map((item) => ({ ...item })); }
  function subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); }
  return { addFee, publishFee, invoice, pay, changeReceipt, statement, configureGateway, recordIncome, recordExpense, listIncomes, listExpenses, listInvoices, listPayments, structures, subscribe, revision: () => revision, counts: () => ({ invoices: invoices.size, payments: payments.size, incomes: incomes.length, expenses: expenses.length }) };
}
