import { randomUUID } from 'node:crypto';
import { BUDGET_CATEGORIES } from './budgets.js';
import { assertInputSchool, authorizeFinancial, financialAudit } from './financial-authorization.js';

export const INCOME_CATEGORIES = Object.freeze(['Donations','Grants','Sponsorship','Fundraising','Facility Rental','Sale of Materials','Interest Income','Investment Income','Alumni Support','PTA/Community Support','Government Support','Other']);
export const EXPENSE_CATEGORIES = BUDGET_CATEGORIES;
export const GENERAL_PAYMENT_METHODS = Object.freeze(['CASH','BANK','MOBILE_MONEY','CHEQUE','OTHER']);
export const TRANSACTION_STATUSES = Object.freeze(['POSTED','VOIDED']);
const COPY = (value) => structuredClone(value);
const ROLE = (actor) => String(actor?.roleKey ?? '').toUpperCase() === 'ACCOUNTANT' ? 'ACCOUNTANT_BURSAR' : String(actor?.roleKey ?? '').toUpperCase();
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const DECIMAL = /^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/;

function text(value, field, { optional = false } = {}) { const result = String(value ?? '').trim(); if (!result && !optional) throw Object.assign(new Error(`${field} is required.`), { code: 'INVALID_TRANSACTION' }); return result || null; }
function amount(value) { const raw = String(value ?? '').trim(); if (!DECIMAL.test(raw) || Number(raw) <= 0 || !Number.isSafeInteger(Math.round(Number(raw) * 100))) throw Object.assign(new Error('Amount must be a positive amount with at most two decimal places.'), { code: 'INVALID_TRANSACTION_AMOUNT' }); return Math.round(Number(raw) * 100) / 100; }
function date(value, now) { const result = String(value ?? now().slice(0, 10)).trim(); if (!ISO_DATE.test(result)) throw Object.assign(new Error('Transaction date must use YYYY-MM-DD.'), { code: 'INVALID_TRANSACTION_DATE' }); const parsed = new Date(`${result}T00:00:00Z`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== result) throw Object.assign(new Error('Transaction date is invalid.'), { code: 'INVALID_TRANSACTION_DATE' }); return result; }
function status(value) { const result = String(value ?? 'POSTED').trim().toUpperCase(); if (!TRANSACTION_STATUSES.includes(result)) throw Object.assign(new Error('Invalid transaction status.'), { code: 'INVALID_TRANSACTION_STATUS' }); return result; }

export function createGeneralFinanceService({ adapter, budgets = null, audit = () => {}, now = () => new Date().toISOString() } = {}) {
  if (!adapter?.query || !adapter?.execute || !adapter?.transaction) throw new Error('A durable database adapter is required for general finance.');
  const config = { income: { table: 'general_income', categoryColumn: 'income_category', partyColumn: 'payer_or_source', resource: 'income', categories: INCOME_CATEGORIES }, expenses: { table: 'general_expenses', categoryColumn: 'expense_category', partyColumn: 'payee', resource: 'expenses', categories: EXPENSE_CATEGORIES } };
  const authorize = (actor, action, resource) => authorizeFinancial(actor, action, resource);
  async function validatePeriod(input, actor) {
    const academicYear = text(input.academicYear, 'Academic year'); const term = text(input.term, 'Term');
    const years = await adapter.query('SELECT id FROM academic_years WHERE id=? AND school_id=?', [academicYear, actor.schoolId]); if (!years.length) throw Object.assign(new Error('Academic year not found for the authenticated school.'), { code: 'INVALID_ACADEMIC_YEAR' });
    if (term === 'FULL_YEAR') return { academicYear, term }; const terms = await adapter.query('SELECT t.id FROM terms t JOIN academic_years y ON y.id=t.academic_year_id WHERE t.id=? AND y.id=? AND y.school_id=?', [term, academicYear, actor.schoolId]); if (!terms.length) throw Object.assign(new Error('Term not found for the selected academic year.'), { code: 'INVALID_TERM' }); return { academicYear, term };
  }
  function normalize(input, actor, kind) { const item = config[kind]; const category = text(input.category, `${kind === 'income' ? 'Income' : 'Expense'} category`); if (!item.categories.includes(category)) throw Object.assign(new Error('Invalid controlled category.'), { code: 'INVALID_TRANSACTION_CATEGORY' }); const customCategory = category === 'Other' ? text(input.customCategory, 'Specify Category') : null; if (category !== 'Other' && input.customCategory) throw Object.assign(new Error('Custom category is only allowed for Other.'), { code: 'INVALID_TRANSACTION_CATEGORY' }); const referenceNumber = text(input.referenceNumber, 'Reference number'); const paymentMethod = text(input.paymentMethod, 'Payment method').toUpperCase(); if (!GENERAL_PAYMENT_METHODS.includes(paymentMethod)) throw Object.assign(new Error('Invalid payment method.'), { code: 'INVALID_PAYMENT_METHOD' }); return { category, customCategory, description: text(input.description, 'Description'), referenceNumber, amount: amount(input.amount), paymentMethod, party: text(input[kind === 'income' ? 'payerOrSource' : 'payee'], kind === 'income' ? 'Source/Payer' : 'Payee'), notes: text(input.notes, 'Notes', { optional: true }), transactionDate: date(input.transactionDate, now), status: status(input.status), academicYear: input.academicYear, term: input.term, schoolId: actor.schoolId };
  }
  async function assertDuplicate(kind, referenceNumber, actor, id = null) { const item = config[kind]; const rows = await adapter.query(`SELECT id FROM ${item.table} WHERE school_id=? AND reference_number=? AND status <> 'VOIDED'`, [actor.schoolId, referenceNumber]); if (rows.some((row) => row.id !== id)) throw Object.assign(new Error('Reference number already exists for this school.'), { code: 'DUPLICATE_REFERENCE', status: 409 }); }
  async function budgetLink(input, actor) {
    if (input.budgetId == null && input.budgetItemId == null) return { budgetId: null, budgetItemId: null };
    if (!input.budgetId || !input.budgetItemId) throw Object.assign(new Error('Budget and Budget Item must be selected together.'), { code: 'INVALID_BUDGET_LINK' });
    const budgetsRows = await adapter.query('SELECT * FROM budgets WHERE school_id=? AND id=?', [actor.schoolId, input.budgetId]); const budget = budgetsRows[0]; if (!budget) throw Object.assign(new Error('Budget not found for the authenticated school.'), { code: 'INVALID_BUDGET_LINK', status: 403 }); if (!['APPROVED','ACTIVE'].includes(String(budget.status).toUpperCase())) throw Object.assign(new Error('Expense can only link to an approved or active budget.'), { code: 'INVALID_BUDGET_LINK' }); const itemRows = await adapter.query('SELECT * FROM budget_items WHERE school_id=? AND budget_id=? AND id=?', [actor.schoolId, input.budgetId, input.budgetItemId]); if (!itemRows.length) throw Object.assign(new Error('Budget item does not belong to the selected budget.'), { code: 'INVALID_BUDGET_LINK', status: 403 }); return { budgetId: input.budgetId, budgetItemId: input.budgetItemId };
  }
  function present(row, kind) { const item = config[kind]; return { id: row.id, schoolId: row.school_id, transactionDate: row.transaction_date, academicYear: row.academic_year, term: row.term, category: row[item.categoryColumn], customCategory: row.custom_category, description: row.description, referenceNumber: row.reference_number, amount: Number(row.amount), paymentMethod: row.payment_method, [kind === 'income' ? 'payerOrSource' : 'payee']: row[item.partyColumn], notes: row.notes, status: row.status, budgetId: row.budget_id ?? null, budgetItemId: row.budget_item_id ?? null, createdBy: row.created_by, createdAt: row.created_at, updatedBy: row.updated_by, updatedAt: row.updated_at, voidedBy: row.voided_by ?? null, voidedAt: row.voided_at ?? null, voidReason: row.void_reason ?? null };
  }
  async function get(id, actor, kind) { const item = config[kind]; authorize(actor, 'READ', item.resource); const rows = await adapter.query(`SELECT * FROM ${item.table} WHERE school_id=? AND id=?`, [actor.schoolId, id]); return rows[0] ? present(rows[0], kind) : null; }
  async function list(filters = {}, actor, kind) { const item = config[kind]; authorize(actor, 'READ', item.resource); const where = ['school_id=?']; const params = [actor.schoolId]; const add = (sql, value) => { if (value) { where.push(sql); params.push(value); } }; add('academic_year=?', filters.academicYear); add('term=?', filters.term); add(`${item.categoryColumn}=?`, filters.category); add('payment_method=?', filters.paymentMethod ? String(filters.paymentMethod).toUpperCase() : null); if (filters.status) add('status=?', status(filters.status)); add('transaction_date>=?', filters.dateFrom); add('transaction_date<=?', filters.dateTo); if (filters.search) { where.push(`(reference_number LIKE ? OR description LIKE ? OR ${item.partyColumn} LIKE ?)`); const search = `%${String(filters.search).trim()}%`; params.push(search, search, search); } const rows = await adapter.query(`SELECT * FROM ${item.table} WHERE ${where.join(' AND ')} ORDER BY transaction_date DESC,created_at DESC,id DESC`, params); return rows.map((row) => present(row, kind)); }
  async function create(input, actor, kind) { const item = config[kind]; authorize(actor, 'CREATE', item.resource); assertInputSchool(actor, input); const normalized = normalize(input, actor, kind); const period = await validatePeriod(normalized, actor); await assertDuplicate(kind, normalized.referenceNumber, actor); const link = kind === 'expenses' ? await budgetLink(input, actor) : { budgetId: null, budgetItemId: null }; const id = randomUUID(); const stamp = now(); const columns = kind === 'income' ? `id,school_id,transaction_date,academic_year,term,income_category,custom_category,description,reference_number,amount,payment_method,payer_or_source,notes,status,created_by,created_at,updated_by,updated_at` : `id,school_id,transaction_date,academic_year,term,expense_category,custom_category,description,reference_number,amount,payment_method,payee,notes,status,budget_id,budget_item_id,created_by,created_at,updated_by,updated_at`; const values = kind === 'income' ? [id, actor.schoolId, normalized.transactionDate, period.academicYear, period.term, normalized.category, normalized.customCategory, normalized.description, normalized.referenceNumber, normalized.amount, normalized.paymentMethod, normalized.party, normalized.notes, 'POSTED', actor.id, stamp, actor.id, stamp] : [id, actor.schoolId, normalized.transactionDate, period.academicYear, period.term, normalized.category, normalized.customCategory, normalized.description, normalized.referenceNumber, normalized.amount, normalized.paymentMethod, normalized.party, normalized.notes, 'POSTED', link.budgetId, link.budgetItemId, actor.id, stamp, actor.id, stamp]; await adapter.execute(`INSERT INTO ${item.table} (${columns}) VALUES (${values.map(() => '?').join(',')})`, values); const action = kind === 'income' ? 'INCOME_CREATED' : 'EXPENSE_CREATED'; await persistAudit(actor, action, id, null, normalized); financialAudit({ audit, actor, action, entity: kind === 'income' ? 'GeneralIncome' : 'GeneralExpense', entityId: id, transactionReference: normalized.referenceNumber, newValue: normalized }); return get(id, actor, kind); }
  async function update(id, input, actor, kind) { const item = config[kind]; authorize(actor, 'UPDATE', item.resource); const existing = await get(id, actor, kind); if (!existing) throw Object.assign(new Error('Transaction not found.'), { status: 404 }); if (existing.status !== 'POSTED') throw Object.assign(new Error('Only posted transactions can be edited.'), { code: 'INVALID_TRANSACTION_STATUS' }); const description = text(input.description ?? existing.description, 'Description'); const notes = text(input.notes ?? existing.notes, 'Notes', { optional: true }); const party = text(input[kind === 'income' ? 'payerOrSource' : 'payee'] ?? existing[kind === 'income' ? 'payerOrSource' : 'payee'], kind === 'income' ? 'Source/Payer' : 'Payee'); const stamp = now(); await adapter.execute(`UPDATE ${item.table} SET description=?,notes=?,${item.partyColumn}=?,updated_by=?,updated_at=? WHERE school_id=? AND id=? AND status='POSTED'`, [description, notes, party, actor.id, stamp, actor.schoolId, id]); await persistAudit(actor, kind === 'income' ? 'INCOME_UPDATED' : 'EXPENSE_UPDATED', id, existing, { description, notes, party }); financialAudit({ audit, actor, action: kind === 'income' ? 'INCOME_UPDATED' : 'EXPENSE_UPDATED', entity: kind === 'income' ? 'GeneralIncome' : 'GeneralExpense', entityId: id, transactionReference: existing.referenceNumber, previousValue: existing, newValue: { description, notes, party } }); return get(id, actor, kind); }
  async function voidTransaction(id, reason, actor, kind) { const item = config[kind]; authorize(actor, 'VOID_REVERSE', item.resource); const existing = await get(id, actor, kind); if (!existing) throw Object.assign(new Error('Transaction not found.'), { status: 404 }); if (existing.status !== 'POSTED') throw Object.assign(new Error('Transaction is already voided.'), { code: 'INVALID_TRANSACTION_STATUS' }); const voidReason = text(reason, 'Void reason'); const stamp = now(); await adapter.execute(`UPDATE ${item.table} SET status='VOIDED',voided_by=?,voided_at=?,void_reason=?,updated_by=?,updated_at=? WHERE school_id=? AND id=? AND status='POSTED'`, [actor.id, stamp, voidReason, actor.id, stamp, actor.schoolId, id]); await persistAudit(actor, kind === 'income' ? 'INCOME_VOIDED' : 'EXPENSE_VOIDED', id, existing, { status: 'VOIDED', voidReason }); financialAudit({ audit, actor, action: kind === 'income' ? 'INCOME_VOIDED' : 'EXPENSE_VOIDED', entity: kind === 'income' ? 'GeneralIncome' : 'GeneralExpense', entityId: id, transactionReference: existing.referenceNumber, previousValue: existing, newValue: { status: 'VOIDED', voidReason } }); return get(id, actor, kind); }
  async function persistAudit(actor, action, id, previousValue, newValue) { await adapter.execute('INSERT INTO financial_audit_history (id,school_id,entity_type,entity_id,action,previous_values,new_values,changed_by,changed_at,source) VALUES (?,?,?,?,?,?,?,?,?,?)', [randomUUID(), actor.schoolId, 'GeneralFinance', id, action, previousValue == null ? null : JSON.stringify(previousValue), newValue == null ? null : JSON.stringify(newValue), actor.id, now(), 'MANUAL']); }
  const bind = (kind) => ({ create: (input, actor) => create(input, actor, kind), list: (filters, actor) => list(filters, actor, kind), get: (id, actor) => get(id, actor, kind), update: (id, input, actor) => update(id, input, actor, kind), void: (id, reason, actor) => voidTransaction(id, reason, actor, kind), categories: () => [...config[kind].categories], methods: () => [...GENERAL_PAYMENT_METHODS], statuses: () => [...TRANSACTION_STATUSES] });
  return { income: bind('income'), expenses: bind('expenses') };
}
