import { randomUUID } from 'node:crypto';

export const OPERATIONS_SECTIONS = ['LIBRARY', 'TRANSPORT', 'HOSTEL', 'HEALTH', 'DISCIPLINE', 'COUNSELLING'];
export function createOperationsService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) {
  const books = []; const loans = []; const vehicles = []; const routes = []; const transportAssignments = []; const hostelSpaces = []; const hostelAllocations = []; const healthRecords = []; const healthVisits = []; const incidents = []; const counsellingRecords = [];
  const copy = (value) => JSON.parse(JSON.stringify(value));
  const scoped = (item) => item.schoolId === schoolId;
  function createBook(input, actor) { const book = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', isbn: input.isbn, title: input.title, authors: input.authors ?? [], category: input.category ?? null, shelf: input.shelf ?? null, copies: Number(input.copies ?? 1), availableCopies: Number(input.copies ?? 1), createdBy: actor.id ?? actor.userId, createdAt: now() }; if (book.copies < 1) throw new Error('Book copies must be positive'); books.push(book); return copy(book); }
  function borrowBook(input, actor) { const book = books.find((item) => item.id === input.bookId && scoped(item)); if (!book || book.availableCopies < 1) throw new Error('No available copy'); const loan = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', bookId: book.id, borrowerId: input.borrowerId, borrowerType: input.borrowerType, dueAt: input.dueAt, status: 'BORROWED', borrowedBy: actor.id ?? actor.userId, borrowedAt: now(), returnedAt: null }; book.availableCopies -= 1; loans.push(loan); return copy(loan); }
  function returnBook(loanId, actor, condition = 'GOOD') { const loan = loans.find((item) => item.id === loanId && scoped(item) && item.status === 'BORROWED'); if (!loan) throw new Error('Active loan not found'); const book = books.find((item) => item.id === loan.bookId); loan.status = condition === 'LOST' ? 'LOST' : condition === 'DAMAGED' ? 'DAMAGED' : 'RETURNED'; loan.returnedAt = now(); loan.returnedBy = actor.id ?? actor.userId; loan.condition = condition; if (book && condition === 'GOOD') book.availableCopies += 1; return copy(loan); }
  function createVehicle(input, actor) { const vehicle = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', registration: input.registration, insuranceExpiresAt: input.insuranceExpiresAt ?? null, roadworthinessExpiresAt: input.roadworthinessExpiresAt ?? null, driverId: input.driverId ?? null, attendantIds: input.attendantIds ?? [], emergencyContact: input.emergencyContact ?? null, status: 'ACTIVE', createdBy: actor.id ?? actor.userId, createdAt: now() }; if (vehicles.some((item) => scoped(item) && item.registration === vehicle.registration)) throw new Error('Vehicle registration already exists'); vehicles.push(vehicle); return copy(vehicle); }
  function createRoute(input, actor) { const route = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', name: input.name, stops: input.stops ?? [], vehicleId: input.vehicleId ?? null, studentIds: input.studentIds ?? [], boarding: input.boarding ?? {}, dropOff: input.dropOff ?? {}, createdBy: actor.id ?? actor.userId, createdAt: now() }; routes.push(route); return copy(route); }
  function assignTransport(input, actor) { const assignment = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, routeId: input.routeId, stopId: input.stopId ?? null, feeReference: input.feeReference ?? null, assignedBy: actor.id ?? actor.userId, createdAt: now() }; transportAssignments.push(assignment); return copy(assignment); }
  function addHostelSpace(input, actor) { const space = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', type: input.type, name: input.name, capacity: Number(input.capacity ?? 1), wardenId: input.wardenId ?? null, matronId: input.matronId ?? null, createdBy: actor.id ?? actor.userId, createdAt: now() }; hostelSpaces.push(space); return copy(space); }
  function allocateBoarder(input, actor) { const space = hostelSpaces.find((item) => item.id === input.spaceId && scoped(item)); if (!space) throw new Error('Hostel space not found'); const used = hostelAllocations.filter((item) => scoped(item) && item.spaceId === space.id && item.active).length; if (used >= space.capacity) throw new Error('Hostel space is full'); const allocation = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, spaceId: space.id, bed: input.bed ?? null, active: true, allocatedBy: actor.id ?? actor.userId, createdAt: now() }; hostelAllocations.push(allocation); return copy(allocation); }
  function recordHealth(input, actor) { const record = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, allergies: input.allergies ?? [], medicalAlerts: input.medicalAlerts ?? [], emergencyContact: input.emergencyContact ?? null, medication: input.medication ?? [], confidential: true, recordedBy: actor.id ?? actor.userId, createdAt: now() }; healthRecords.push(record); return copy(record); }
  function recordHealthVisit(input, actor) { const visit = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, type: input.type ?? 'VISIT', notes: input.notes ?? '', firstAid: input.firstAid ?? null, referral: input.referral ?? null, parentNotified: Boolean(input.parentNotified), recordedBy: actor.id ?? actor.userId, createdAt: now() }; healthVisits.push(visit); return copy(visit); }
  function recordIncident(input, actor) { const incident = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, kind: input.kind ?? 'DISCIPLINE', title: input.title, details: input.details ?? '', action: input.action ?? null, resolution: input.resolution ?? null, followUpAt: input.followUpAt ?? null, parentNotified: Boolean(input.parentNotified), recordedBy: actor.id ?? actor.userId, createdAt: now() }; incidents.push(incident); return copy(incident); }
  function recordCounselling(input, actor) { const record = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', studentId: input.studentId, type: input.type ?? 'ACADEMIC', appointmentAt: input.appointmentAt ?? null, referral: input.referral ?? null, confidentialNotes: input.confidentialNotes ?? '', confidential: true, recordedBy: actor.id ?? actor.userId, createdAt: now() }; counsellingRecords.push(record); return copy(record); }
  function list(section, user, studentId) { const own = (id) => user.portal === 'parent' ? user.children?.some((child) => child.id === id) : user.roleKey === 'TEACHER' ? user.assignedStudentIds?.includes(id) : true; const filter = (item) => scoped(item) && (!studentId || item.studentId === studentId) && (!item.studentId || own(item.studentId)); if (section === 'LIBRARY') return { books: books.filter(scoped).map(copy), loans: loans.filter((item) => scoped(item) && (!studentId || item.borrowerId === studentId) && (item.borrowerType !== 'STUDENT' || own(item.borrowerId))).map(copy) }; if (section === 'TRANSPORT') return { vehicles: vehicles.filter(scoped).map(copy), routes: routes.filter(scoped).map(copy), assignments: transportAssignments.filter(filter).map(copy) }; if (section === 'HOSTEL') return { spaces: hostelSpaces.filter(scoped).map(copy), allocations: hostelAllocations.filter(filter).map(copy) }; if (section === 'HEALTH') return { profiles: healthRecords.filter(filter).map(copy), visits: healthVisits.filter(filter).map(copy) }; if (section === 'DISCIPLINE') return { incidents: incidents.filter(filter).map(copy) }; if (section === 'COUNSELLING') return { records: counsellingRecords.filter(filter).map(copy) }; throw new Error('Unknown operations section'); }
  return { createBook, borrowBook, returnBook, createVehicle, createRoute, assignTransport, addHostelSpace, allocateBoarder, recordHealth, recordHealthVisit, recordIncident, recordCounselling, list, counts: () => ({ books: books.length, loans: loans.length, vehicles: vehicles.length, routes: routes.length, hostelSpaces: hostelSpaces.length, healthRecords: healthRecords.length, incidents: incidents.length, counsellingRecords: counsellingRecords.length }) };
}
