import { randomUUID } from 'node:crypto';

export const REPORT_TYPES = ['STUDENT_PERFORMANCE', 'CLASS_PERFORMANCE', 'SUBJECT_PERFORMANCE', 'TEACHER_PERFORMANCE', 'ATTENDANCE_PERFORMANCE', 'ENROLLMENT', 'ADMISSIONS', 'PROMOTION', 'REVENUE', 'FEES', 'ARREARS', 'COLLECTIONS', 'OPERATIONS', 'COMPLIANCE'];
export const OFFICIAL_DOCUMENT_TYPES = ['ADMISSION_LETTER', 'REPORT_CARD', 'RESULT_SLIP', 'TRANSCRIPT', 'CERTIFICATE', 'RECEIPT', 'INVOICE', 'STATEMENT', 'OFFICIAL_LETTER', 'ATTENDANCE_REPORT', 'STAFF_DOCUMENT'];
const BRAND = { schoolName: 'OSAAH DAYLIGHT SCH. COM.', location: 'BOGOSO', motto: 'AIM HIGH, ACADEMIC IS OUR CORE VALUE' };
function pdfEscape(value) { return String(value).replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)'); }
function makePdf(lines) { const content = ['BT', '/F1 14 Tf', '72 760 Td', ...lines.flatMap((line, index) => [`(${pdfEscape(line)}) Tj`, index < lines.length - 1 ? '0 -22 Td' : '']), 'ET'].join('\n'); const objects = [`<< /Type /Catalog /Pages 2 0 R >>`, `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`, `<< /Length ${content.length} >>\nstream\n${content}\nendstream`]; let output = '%PDF-1.4\n'; const offsets = [0]; for (let index = 0; index < objects.length; index += 1) { offsets.push(output.length); output += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`; } const xref = output.length; output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return output; }
export function createReportingService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const documents = [];
  function buildReport(type, filters = {}, user = {}) { if (!REPORT_TYPES.includes(type)) throw new Error('Invalid report type'); return { schoolId, reportType: type, filters: { academicYear: filters.academicYear ?? null, term: filters.term ?? null, classId: filters.classId ?? null, streamId: filters.streamId ?? null, subjectId: filters.subjectId ?? null, dateFrom: filters.dateFrom ?? null, dateTo: filters.dateTo ?? null, studentId: filters.studentId ?? null, staffId: filters.staffId ?? null }, generatedAt: now(), generatedBy: user.id ?? user.userId ?? null, rows: filters.rows ?? [], summary: filters.summary ?? {} }; }
  function exportReport(report, format = 'csv') { const safeFormat = format.toLowerCase(); if (!['csv', 'excel', 'pdf'].includes(safeFormat)) throw new Error('Unsupported export format'); const rows = report.rows ?? []; if (safeFormat === 'pdf') return { format: 'pdf', mimeType: 'application/pdf', filename: `${report.reportType.toLowerCase()}.pdf`, content: makePdf([BRAND.schoolName, report.reportType, `Generated: ${report.generatedAt}`, ...rows.map((row) => Object.values(row).join(' | '))]) }; const csv = [Object.keys(rows[0] ?? report.summary).join(','), ...rows.map((row) => Object.values(row).map((value) => JSON.stringify(value ?? '')).join(','))].join('\n'); return { format: safeFormat, mimeType: safeFormat === 'excel' ? 'application/vnd.ms-excel' : 'text/csv', filename: `${report.reportType.toLowerCase()}.${safeFormat === 'excel' ? 'xls' : 'csv'}`, content: csv }; }
  function generateOfficialDocument(input, actor) { if (!OFFICIAL_DOCUMENT_TYPES.includes(input.type)) throw new Error('Invalid official document type'); const document = { id: randomUUID(), schoolId, documentNumber: `OFF-${String(documents.length + 1).padStart(6, '0')}`, type: input.type, recipientId: input.recipientId ?? null, studentId: input.studentId ?? null, date: input.date ?? now().slice(0, 10), title: input.title ?? input.type.replaceAll('_', ' '), body: input.body ?? '', signatures: input.signatures ?? [], stamp: input.stamp ?? null, verificationCode: randomUUID(), createdBy: actor.id ?? actor.userId, createdAt: now() }; document.pdf = makePdf([BRAND.schoolName, BRAND.location, BRAND.motto, document.title, `Document No: ${document.documentNumber}`, `Date: ${document.date}`, document.body, 'Official school document']); documents.push(document); return { ...document }; }
  function verifyOfficialDocument(code) { const document = documents.find((item) => item.schoolId === schoolId && item.verificationCode === code); return document ? { authentic: true, documentNumber: document.documentNumber, type: document.type, title: document.title, date: document.date } : { authentic: false }; }
  function listDocuments(user = {}) { return documents.filter((document) => document.schoolId === schoolId && (document.recipientId === user.id || document.studentId === user.studentId || user.roleKey === 'PROPRIETOR' || user.roleKey === 'SCHOOL_ADMIN')).map(({ verificationCode, pdf, ...safe }) => safe); }
  return { buildReport, exportReport, generateOfficialDocument, verifyOfficialDocument, listDocuments, counts: () => ({ documents: documents.length }) };
}
