import { randomUUID } from 'node:crypto';

export const PROCUREMENT_STATES = ['REQUESTED', 'APPROVED', 'ORDERED', 'RECEIVED', 'INVOICED', 'PAID', 'REJECTED'];
export const PROPERTY_STATUSES = ['REQUESTED', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
export function createResourceService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) {
  const inventory = []; const stockMoves = []; const assets = []; const procurement = []; const property = []; const maintenance = [];
  const clone = (value) => JSON.parse(JSON.stringify(value)); const scoped = (item) => item.schoolId === schoolId; const actorId = (actor) => actor.id ?? actor.userId;
  function addInventory(input, actor) { const item = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', name: input.name, type: input.type ?? 'CONSUMABLE', unit: input.unit ?? 'unit', supplier: input.supplier ?? null, reorderLevel: Number(input.reorderLevel ?? 0), quantity: 0, createdBy: actorId(actor), createdAt: now() }; inventory.push(item); return clone(item); }
  function moveStock(input, actor) { const item = inventory.find((record) => record.id === input.inventoryId && scoped(record)); if (!item) throw new Error('Inventory item not found'); const quantity = Number(input.quantity); if (!Number.isInteger(quantity) || quantity <= 0) throw new Error('Stock quantity must be a positive whole number'); if (input.type === 'OUT' && item.quantity < quantity) throw new Error('Insufficient stock'); if (!['IN', 'OUT', 'TRANSFER', 'ADJUSTMENT'].includes(input.type)) throw new Error('Invalid stock movement'); item.quantity += input.type === 'OUT' ? -quantity : input.type === 'ADJUSTMENT' ? Number(input.delta ?? 0) : input.type === 'TRANSFER' ? 0 : quantity; if (item.quantity < 0) throw new Error('Stock cannot be negative'); const movement = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', inventoryId: item.id, type: input.type, quantity, delta: input.type === 'ADJUSTMENT' ? Number(input.delta ?? 0) : input.type === 'OUT' ? -quantity : input.type === 'IN' ? quantity : 0, destination: input.destination ?? null, performedBy: actorId(actor), createdAt: now() }; stockMoves.push(movement); return clone({ item, movement }); }
  function addAsset(input, actor) { const asset = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', assetId: `AST-${String(assets.length + 1).padStart(6, '0')}`, type: input.type, description: input.description, serialNumber: input.serialNumber ?? null, location: input.location ?? null, department: input.department ?? null, custodian: input.custodian ?? null, purchaseDate: input.purchaseDate ?? null, purchaseValue: input.purchaseValue ?? null, warranty: input.warranty ?? null, condition: input.condition ?? 'GOOD', qrCode: `osaah:asset:${assets.length + 1}`, status: 'ACTIVE', createdBy: actorId(actor), createdAt: now() }; if (input.serialNumber && assets.some((record) => scoped(record) && record.serialNumber === input.serialNumber)) throw new Error('Asset serial number already exists'); assets.push(asset); return clone(asset); }
  function requestPurchase(input, actor) { const request = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', requestNumber: `PR-${String(procurement.length + 1).padStart(6, '0')}`, item: input.item, quantity: Number(input.quantity), supplier: input.supplier ?? null, quotation: input.quotation ?? null, state: 'REQUESTED', requestedBy: actorId(actor), createdAt: now(), history: [{ state: 'REQUESTED', by: actorId(actor), at: now() }] }; if (request.quantity < 1) throw new Error('Purchase quantity must be positive'); procurement.push(request); return clone(request); }
  function advancePurchase(id, state, actor) { if (!PROCUREMENT_STATES.includes(state)) throw new Error('Invalid procurement state'); const request = procurement.find((record) => record.id === id && scoped(record)); if (!request) throw new Error('Purchase request not found'); const order = PROCUREMENT_STATES.indexOf(request.state); const next = PROCUREMENT_STATES.indexOf(state); if (state !== 'REJECTED' && next !== order + 1) throw new Error('Procurement state must advance in order'); request.state = state; request.history.push({ state, by: actorId(actor), at: now() }); return clone(request); }
  function addProperty(input, actor) { const item = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', name: input.name, type: input.type, location: input.location ?? null, responsibleOfficer: input.responsibleOfficer ?? null, status: 'ACTIVE', createdBy: actorId(actor), createdAt: now() }; property.push(item); return clone(item); }
  function requestMaintenance(input, actor) { const item = property.find((record) => record.id === input.propertyId && scoped(record)); if (!item) throw new Error('Property record not found'); const request = { id: randomUUID(), schoolId, provenance: 'PRODUCTION', propertyId: item.id, title: input.title, details: input.details ?? '', responsibleOfficer: input.responsibleOfficer ?? item.responsibleOfficer, status: 'REQUESTED', requestedBy: actorId(actor), createdAt: now(), history: [{ status: 'REQUESTED', by: actorId(actor), at: now() }] }; maintenance.push(request); return clone(request); }
  function updateMaintenance(id, status, actor) { if (!PROPERTY_STATUSES.includes(status)) throw new Error('Invalid maintenance status'); const request = maintenance.find((record) => record.id === id && scoped(record)); if (!request) throw new Error('Maintenance request not found'); request.status = status; request.history.push({ status, by: actorId(actor), at: now() }); return clone(request); }
  function list(section, user) { const own = (id) => user.portal === 'parent' ? user.children?.some((child) => child.id === id) : user.roleKey === 'TEACHER' ? user.assignedStudentIds?.includes(id) : true; if (section === 'INVENTORY') return { inventory: inventory.filter(scoped).map(clone), movements: stockMoves.filter(scoped).map(clone) }; if (section === 'ASSETS') return { assets: assets.filter(scoped).map(clone) }; if (section === 'PROCUREMENT') return { requests: procurement.filter(scoped).map(clone) }; if (section === 'PROPERTY') return { property: property.filter(scoped).map(clone), maintenance: maintenance.filter(scoped).map(clone) }; return { own: Boolean(own) }; }
  return { addInventory, moveStock, addAsset, requestPurchase, advancePurchase, addProperty, requestMaintenance, updateMaintenance, list, counts: () => ({ inventory: inventory.length, assets: assets.length, procurement: procurement.length, property: property.length, maintenance: maintenance.length }) };
}
