import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { visibleSidebar } from './sidebar-registry.js';
import { canAccess, createAuthService } from './auth.js';
import { createAuditLog } from './audit.js';
import { createStudentService } from './students.js';
import { createAttendanceService } from './attendance.js';
import { createExaminationService } from './examinations.js';
import { createFeeService } from './fees.js';
import { createStaffService } from './staff.js';
import { createCommunicationService } from './communication.js';
import './module-registry.js';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..', 'public');
const mime = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.png': 'image/png', '.svg': 'image/svg+xml' };
const branding = { schoolName: 'OSAAH DAYLIGHT SCH. COM.', location: 'BOGOSO', motto: 'AIM HIGH, ACADEMIC IS OUR CORE VALUE', logoPath: '/assets/osaah-daylight-logo.png', colours: { navy: '#102a43', royalBlue: '#1769aa', gold: '#d4a72c', white: '#ffffff' } };

export function createApp({ auth = createAuthService(), students = createStudentService(), attendance = createAttendanceService(), examinations = createExaminationService(), fees = createFeeService(), staff = createStaffService(), communication = createCommunicationService(), audit = () => {} } = {}) {
  return async function handle(request, response) {
    const pathname = new URL(request.url, 'http://localhost').pathname;
    if (pathname === '/api/branding') return json(response, branding);
    if (pathname === '/api/auth/login' && request.method === 'POST') return login(request, response, auth);
    if (pathname === '/api/auth/logout' && request.method === 'POST') { auth.logout(readCookie(request, 'osaah_session')); return json(response, { ok: true }, 204); }
    if (pathname === '/api/auth/password-reset' && request.method === 'POST') { const body = await readJson(request); return json(response, auth.requestPasswordReset(body.username ?? '')); }
    if (pathname === '/api/auth/password-reset/complete' && request.method === 'POST') { const body = await readJson(request); const result = auth.completePasswordReset(body.token ?? '', body.newPassword ?? ''); return json(response, result, result.ok ? 200 : 400); }
    if (pathname.startsWith('/api/')) {
      const user = auth.authenticate(readCookie(request, 'osaah_session') ?? bearer(request));
      if (!user) return json(response, { error: 'Authentication required.' }, 401);
      if (pathname === '/api/sidebar') return json(response, { user: publicUser(user), categories: visibleSidebar({ permissions: user.permissions, roleKey: user.roleKey }) });
      if (pathname === '/api/students' && request.method === 'POST') { if (!canAccess(user, 'students.write')) return json(response, { error: 'Forbidden.' }, 403); const student = students.createStudent({ ...(await readJson(request)), schoolId: user.schoolId }); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'Student', entityId: student.id, newValue: student })); return json(response, student, 201); }
      if (pathname === '/api/students/search') { if (!canAccess(user, 'students.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { students: students.search(new URL(request.url, 'http://localhost').searchParams.get('q'), { ...user, requestedSchoolId: user.schoolId }) }); }
      if (pathname === '/api/attendance/students' && request.method === 'POST') { if (user.portal === 'parent' || !canAccess(user, 'attendance.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); const correction = Boolean(body.correction); if (correction && !canAccess(user, 'attendance.correct')) return json(response, { error: 'Attendance corrections require authorization.' }, 403); const record = attendance.saveStudentAttendance({ ...body, schoolId: user.schoolId }, user, { correction, expectedVersion: body.expectedVersion ?? null }); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: correction ? 'CORRECT' : 'CREATE', entity: 'StudentAttendance', entityId: record.id, newValue: record })); return json(response, record, 201); }
      if (pathname === '/api/attendance/students/sync' && request.method === 'POST') { if (user.portal === 'parent' || !canAccess(user, 'attendance.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); try { const records = attendance.saveBatch(body.entries ?? [], user, { correction: false, expectedVersion: body.expectedVersion ?? null }); return json(response, { synced: records }); } catch (error) { return json(response, { error: error.message, conflict: error.message.includes('conflict') }, 409); } }
      if (pathname === '/api/attendance/students' && request.method === 'GET') { const query = new URL(request.url, 'http://localhost').searchParams; if (user.portal === 'parent') { const ids = (user.children ?? []).map((child) => child.id); return json(response, attendance.summary({ date: query.get('date') ?? undefined, classId: query.get('classId') ?? undefined, studentIds: ids })); } if (!canAccess(user, 'attendance.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, attendance.summary({ date: query.get('date') ?? undefined, classId: query.get('classId') ?? undefined, subjectId: query.get('subjectId') ?? undefined, studentIds: user.roleKey === 'TEACHER' ? user.assignedStudentIds : undefined })); }
      if (pathname === '/api/attendance/staff' && request.method === 'POST') { if (!canAccess(user, 'staff.attendance.write')) return json(response, { error: 'Forbidden.' }, 403); const record = attendance.saveStaffAttendance(await readJson(request), user); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'StaffAttendance', entityId: record.id, newValue: record })); return json(response, record, 201); }
      if (pathname === '/api/attendance/notifications' && request.method === 'POST') { if (user.portal !== 'parent') return json(response, { error: 'Forbidden.' }, 403); return json(response, attendance.setNotificationSettings(user.id, await readJson(request))); }
      if (pathname === '/api/examinations/dashboard') { if (!canAccess(user, 'examinations.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, examinations.dashboard()); }
      if (pathname === '/api/examinations' && request.method === 'POST') { if (!canAccess(user, 'examinations.write')) return json(response, { error: 'Forbidden.' }, 403); return json(response, examinations.createExamination(await readJson(request)), 201); }
      if (pathname.startsWith('/api/examinations/') && pathname.endsWith('/items') && request.method === 'POST') { if (!canAccess(user, 'examinations.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); return json(response, examinations.addExamItem(pathname.split('/')[3], body.type, body.item), 201); }
      if (pathname === '/api/examinations/grading' && request.method === 'POST') { if (!canAccess(user, 'examinations.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); return json(response, examinations.setGradingSystem(body.key, body.boundaries)); }
      if (pathname === '/api/examinations/marks' && request.method === 'POST') { if (!canAccess(user, 'marks.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); if (user.roleKey === 'TEACHER' && user.assignedStudentIds.length && !user.assignedStudentIds.includes(body.studentId)) return json(response, { error: 'Student is outside your assignment.' }, 403); const mark = examinations.enterMarks(body, user, { correction: Boolean(body.correction) }); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: body.correction ? 'CORRECT' : 'ENTER', entity: 'ExaminationMark', entityId: mark.id, newValue: mark })); return json(response, mark, 201); }
      if (pathname.startsWith('/api/examinations/marks/') && pathname.endsWith('/state') && request.method === 'POST') { if (!canAccess(user, 'results.read')) return json(response, { error: 'Forbidden.' }, 403); const parts = pathname.split('/').filter(Boolean); const body = await readJson(request); const mark = examinations.transitionResult(parts[3], parts[4], parts[5], body.state, { ...user, canApprove: canAccess(user, 'results.approve') }); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'STATE_CHANGE', entity: 'ExaminationMark', entityId: mark.id, newValue: mark })); return json(response, mark); }
      if (pathname === '/api/examinations/report' && request.method === 'GET') { if (!canAccess(user, 'results.read')) return json(response, { error: 'Forbidden.' }, 403); const query = new URL(request.url, 'http://localhost').searchParams; return json(response, { report: examinations.report(query.get('examId'), query.get('studentId')) }); }
      if (pathname === '/api/examinations/promotion' && request.method === 'POST') { if (!canAccess(user, 'promotion.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); const result = examinations.promote(body.studentId, body.academicYearId, body.decision, user, body.comment); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'PROMOTION', entity: 'PromotionDecision', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/fees/structures' && request.method === 'POST') { if (!canAccess(user, 'fees.write')) return json(response, { error: 'Forbidden.' }, 403); const result = fees.addFee(await readJson(request)); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'FeeStructure', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/fees/invoices' && request.method === 'POST') { if (!canAccess(user, 'fees.write')) return json(response, { error: 'Forbidden.' }, 403); const result = fees.invoice(await readJson(request)); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'Invoice', entityId: result.invoiceNumber, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/fees/payments' && request.method === 'POST') { if (!canAccess(user, 'fees.write')) return json(response, { error: 'Forbidden.' }, 403); const result = fees.pay(await readJson(request), user); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'PAYMENT', entity: 'Receipt', entityId: result.receiptNumber, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/fees/receipts/change' && request.method === 'POST') { if (!canAccess(user, 'fees.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); const result = fees.changeReceipt(body.receiptNumber, body.action, user, body.reason); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: body.action, entity: 'Receipt', entityId: body.receiptNumber, newValue: result })); return json(response, result); }
      if (pathname === '/api/fees/statements' && request.method === 'GET') { const query = new URL(request.url, 'http://localhost').searchParams; const studentId = query.get('studentId'); if (user.portal === 'parent') { if (!(user.children ?? []).some((child) => child.id === studentId)) return json(response, { error: 'Forbidden.' }, 403); } else if (!canAccess(user, 'fees.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, fees.statement(studentId, user.portal === 'parent' ? user.id : null)); }
      if (pathname === '/api/finance/gateway' && request.method === 'POST') { if (!canAccess(user, 'finance.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); return json(response, fees.configureGateway(body.name, body.publicConfig ?? {})); }
      if (pathname === '/api/communication/announcements' && request.method === 'GET') { if (!canAccess(user, 'communication.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { announcements: communication.listAnnouncements(user) }); }
      if (pathname === '/api/communication/announcements' && request.method === 'POST') { if (!canAccess(user, 'communication.write')) return json(response, { error: 'Forbidden.' }, 403); const result = communication.announce(await readJson(request), user); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'Announcement', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/communication/notifications' && request.method === 'GET') { if (!canAccess(user, 'communication.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { notifications: communication.listNotifications(user) }); }
      if (pathname === '/api/communication/notifications/preferences' && request.method === 'POST') { if (user.portal !== 'parent') return json(response, { error: 'Forbidden.' }, 403); return json(response, communication.setPreferences(user.id, await readJson(request))); }
      if (pathname === '/api/communication/messages' && request.method === 'GET') { if (!canAccess(user, 'messages.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { messages: communication.listMessages(user, user.portal === 'parent' ? (user.children ?? []).map((child) => child.id) : user.assignedStudentIds) }); }
      if (pathname === '/api/communication/messages' && request.method === 'POST') { if (!canAccess(user, 'messages.write')) return json(response, { error: 'Forbidden.' }, 403); const body = await readJson(request); const result = communication.sendMessage(body, user, { authorizedStudentIds: user.portal === 'parent' ? (user.children ?? []).map((child) => child.id) : user.assignedStudentIds, authorizedParentIds: user.assignedParentIds ?? [], authorizedRecipientIds: user.authorizedStaffIds ?? [] }); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'SEND', entity: 'Message', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/communication/calendar' && request.method === 'GET') { if (!canAccess(user, 'calendar.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { events: communication.listCalendar(user) }); }
      if (pathname === '/api/communication/calendar' && request.method === 'POST') { if (!canAccess(user, 'calendar.write')) return json(response, { error: 'Forbidden.' }, 403); const result = communication.addCalendarEvent(await readJson(request), user); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'CalendarEvent', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname === '/api/staff' && request.method === 'POST') { if (!canAccess(user, 'staff.write')) return json(response, { error: 'Forbidden.' }, 403); const result = staff.createProfile(await readJson(request)); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'StaffProfile', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname.startsWith('/api/staff/') && pathname.endsWith('/assignments') && request.method === 'POST') { if (!canAccess(user, 'staff.write')) return json(response, { error: 'Forbidden.' }, 403); const result = staff.assign(pathname.split('/')[3], await readJson(request)); return json(response, result, 201); }
      if (pathname.startsWith('/api/staff/') && pathname.endsWith('/leave') && request.method === 'POST') { const body = await readJson(request); if (user.portal !== 'school' || (body.staffId !== user.id && !canAccess(user, 'leave.write'))) return json(response, { error: 'Forbidden.' }, 403); const result = staff.applyLeave(body); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'StaffLeave', entityId: result.id, newValue: result })); return json(response, result, 201); }
      if (pathname.startsWith('/api/staff/leave/') && pathname.endsWith('/decision') && request.method === 'POST') { if (!canAccess(user, 'leave.approve')) return json(response, { error: 'Forbidden.' }, 403); const result = staff.decideLeave(pathname.split('/')[3], (await readJson(request)).state, user); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'DECIDE', entity: 'StaffLeave', entityId: result.id, newValue: result })); return json(response, result); }
      if (pathname.startsWith('/api/staff/') && request.method === 'GET') { if (!canAccess(user, 'staff.read') && pathname.split('/')[2] !== user.id) return json(response, { error: 'Forbidden.' }, 403); const result = staff.getProfile(pathname.split('/')[3] ?? pathname.split('/')[2], { confidential: canAccess(user, 'hr.confidential.read'), requestedSchoolId: user.schoolId }); return result ? json(response, result) : json(response, { error: 'Not found.' }, 404); }
      if (pathname.startsWith('/api/students/')) { const parts = pathname.split('/').filter(Boolean); const studentId = parts[2]; if (parts[3] === 'class' && request.method === 'POST') { if (!canAccess(user, 'students.write')) return json(response, { error: 'Forbidden.' }, 403); return json(response, students.assignClass(studentId, await readJson(request))); } if (parts[3] === 'parents' && request.method === 'POST') { if (!canAccess(user, 'students.write')) return json(response, { error: 'Forbidden.' }, 403); return json(response, students.linkParent(studentId, await readJson(request)), 201); } if (request.method === 'GET') { if (!canAccess(user, 'students.read')) return json(response, { error: 'Forbidden.' }, 403); const record = students.getStudent(studentId, { allowHealth: canAccess(user, 'health.read'), requestedSchoolId: user.schoolId }); return record ? json(response, record) : json(response, { error: 'Not found.' }, 404); } }
      if (pathname === '/api/admissions' && request.method === 'POST') { if (!canAccess(user, 'admissions.write')) return json(response, { error: 'Forbidden.' }, 403); const application = students.createAdmission(await readJson(request)); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'CREATE', entity: 'AdmissionApplication', entityId: application.applicationNumber, newValue: application })); return json(response, application, 201); }
      if (pathname.startsWith('/api/admissions/') && pathname.endsWith('/advance') && request.method === 'POST') { if (!canAccess(user, 'admissions.write')) return json(response, { error: 'Forbidden.' }, 403); const applicationNumber = pathname.split('/')[3]; const application = students.advanceAdmission(applicationNumber, (await readJson(request)).stage); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'ADVANCE', entity: 'AdmissionApplication', entityId: applicationNumber, newValue: application })); return json(response, application); }
      if (pathname === '/api/parent/children') { if (user.portal !== 'parent' || !canAccess(user, 'children.read')) return json(response, { error: 'Forbidden.' }, 403); return json(response, { children: user.children }); }
      if (pathname === '/api/management') { if (!canAccess(user, 'users.read')) return json(response, { error: 'Forbidden.' }, 403); audit(createAuditLog({ schoolId: user.schoolId, userId: user.id, action: 'ACCESS', entity: 'ManagementDashboard' })); return json(response, { authorized: true, schoolId: user.schoolId }); }
      return json(response, { error: 'Not found.' }, 404);
    }
    const file = pathname === '/' ? '/index.html' : ['/communication/messages', '/communication/calendar'].includes(pathname) ? '/communication.html' : pathname;
    try { const body = await readFile(join(root, file)); response.writeHead(200, { 'Content-Type': mime[extname(file)] ?? 'application/octet-stream' }); response.end(body); } catch { response.writeHead(404); response.end('Not found'); }
  };
}
const server = createServer(createApp());
const port = Number(process.env.OSAAH_PORT || 3000);
if (process.argv[1] === fileURLToPath(import.meta.url)) server.listen(port, () => console.log(`OsaaH foundation listening on http://localhost:${port}`));
export { server };
function publicUser(user) { return { id: user.id, username: user.username, portal: user.portal, roleKey: user.roleKey, schoolId: user.schoolId, children: user.children ?? [], assignedStudentIds: user.assignedStudentIds ?? [], assignedClassIds: user.assignedClassIds ?? [], assignedSubjectIds: user.assignedSubjectIds ?? [], assignedDepartmentIds: user.assignedDepartmentIds ?? [] }; }
async function login(request, response, auth) { const body = await readJson(request); const result = auth.login(body); if (!result.ok) return json(response, { error: result.error }, result.status); return json(response, { user: result.user, expiresAt: result.expiresAt }, 200, `osaah_session=${result.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor(auth.sessionTtlMs / 1000)}`); }
function readCookie(request, name) { return (request.headers.cookie ?? '').split(';').map((part) => part.trim().split('=')).find(([key]) => key === name)?.[1]; }
function bearer(request) { const value = request.headers.authorization ?? ''; return value.startsWith('Bearer ') ? value.slice(7) : null; }
function readJson(request) { return new Promise((resolve, reject) => { let data = ''; request.on('data', (chunk) => { data += chunk; if (data.length > 100_000) request.destroy(); }); request.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('Invalid JSON')); } }); }); }
function json(response, value, status = 200, cookie) { const headers = { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }; if (cookie) headers['Set-Cookie'] = cookie; response.writeHead(status, headers); response.end(status === 204 ? '' : JSON.stringify(value)); }
