import { randomUUID } from 'node:crypto';

const ALLOWED_TYPES = new Set(['image/png', 'image/jpeg', 'image/svg+xml']);
const MAX_BYTES = 2 * 1024 * 1024;
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function actorId(actor) { return actor?.id ?? actor?.userId ?? null; }
function canManage(actor) { return ['PROPRIETOR', 'HEADTEACHER'].includes(actor?.roleKey) || actor?.permissions?.has?.('signatures.manage') || actor?.permissions?.has?.('*'); }
function validate(input) { const signatoryRole = String(input?.signatoryRole ?? '').trim().toUpperCase(); const mimeType = String(input?.mimeType ?? input?.documentType ?? '').trim().toLowerCase(); const size = Number(input?.size ?? input?.documentSize ?? 0); if (!signatoryRole) throw new Error('Signatory role is required.'); if (!ALLOWED_TYPES.has(mimeType)) throw new Error('Only PNG, JPEG, and SVG signatures are supported.'); if (!Number.isFinite(size) || size < 0 || size > MAX_BYTES) throw new Error('Signature file is too large or invalid.'); return { signatoryRole, mimeType, size }; }
export function createSignatureService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const signatures = new Map(); function assertActor(actor) { if (!actor || actor.schoolId !== schoolId || !canManage(actor)) throw new Error('Forbidden.'); } function list(actor) { assertActor(actor); return [...signatures.values()].map(({ data, ...safe }) => clone(safe)); } function upload(input, actor) { assertActor(actor); const meta = validate(input); const record = { id: randomUUID(), schoolId, ...meta, storageKey: String(input.storageKey ?? input.fileReference ?? '').trim() || null, data: input.data ?? null, active: true, uploadedBy: actorId(actor), uploadedAt: now(), updatedAt: now() }; for (const item of signatures.values()) if (item.signatoryRole === meta.signatoryRole) item.active = false; signatures.set(record.id, record); return clone(record); } function remove(id, actor) { assertActor(actor); const record = signatures.get(id); if (!record || record.schoolId !== schoolId) throw new Error('Signature not found.'); record.active = false; record.updatedAt = now(); return clone(record); } function activeFor(role) { return [...signatures.values()].find((item) => item.schoolId === schoolId && item.signatoryRole === String(role).toUpperCase() && item.active) ? clone([...signatures.values()].find((item) => item.schoolId === schoolId && item.signatoryRole === String(role).toUpperCase() && item.active)) : null; } return { list, upload, replace: upload, remove, activeFor, validate }; }
