import { randomUUID } from 'node:crypto';
export const LEAVE_STATES = ['PENDING', 'APPROVED', 'REJECTED'];
export function createStaffService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) { const staff = new Map(); const leave = new Map(); const assignments = [];
  function createProfile(input) { if (!input?.fullName) throw new Error('Full name is required'); const employeeId = input.employeeId ?? `EMP-${String(staff.size + 1).padStart(5, '0')}`; if ([...staff.values()].some((item) => item.employeeId === employeeId)) throw new Error('Employee ID already exists'); const record = { id: `STAFF-${String(staff.size + 1).padStart(5, '0')}`, schoolId, staffId: `STAFF-${String(staff.size + 1).padStart(5, '0')}`, employeeId, fullName: input.fullName, photograph: input.photograph ?? null, gender: input.gender ?? null, dateOfBirth: input.dateOfBirth ?? null, phone: input.phone ?? null, address: input.address ?? null, emergencyContact: input.emergencyContact ?? null, departmentId: input.departmentId ?? null, roleKey: input.roleKey ?? null, employmentType: input.employmentType ?? null, appointmentDate: input.appointmentDate ?? null, contract: input.contract ?? null, qualification: input.qualification ?? null, institution: input.institution ?? null, certificates: input.certificates ?? [], ntc: input.ntc ?? null, professionalDevelopment: input.professionalDevelopment ?? [], appraisal: input.appraisal ?? [], promotion: input.promotion ?? [], documents: input.documents ?? [], confidential: input.confidential ?? null, createdAt: now(), updatedAt: now() }; staff.set(record.id, record); return profile(record); }
  function profile(record, { confidential = false } = {}) { const result = JSON.parse(JSON.stringify(record)); if (!confidential) delete result.confidential; return result; }
  function getProfile(id, options = {}) { const record = staff.get(id); return record && record.schoolId === (options.requestedSchoolId ?? schoolId) ? profile(record, options) : null; }
  function assign(staffId, input) { if (!staff.has(staffId)) throw new Error('Staff member not found'); const assignment = { id: randomUUID(), staffId, subjectId: input.subjectId ?? null, classId: input.classId ?? null, streamId: input.streamId ?? null, departmentId: input.departmentId ?? null, timetableId: input.timetableId ?? null, academicYearId: input.academicYearId ?? null, termId: input.termId ?? null, createdAt: now() }; assignments.push(assignment); return { ...assignment }; }
  function applyLeave(input) { const record = { id: randomUUID(), schoolId, staffId: input.staffId, leaveType: input.leaveType, startsOn: input.startsOn, endsOn: input.endsOn, reason: input.reason ?? null, state: 'PENDING', appliedAt: now(), decidedAt: null, decidedBy: null }; leave.set(record.id, record); return { ...record }; }
  function decideLeave(id, state, actor) { const record = leave.get(id); if (!record || !LEAVE_STATES.includes(state) || state === 'PENDING') throw new Error('Invalid leave decision'); record.state = state; record.decidedAt = now(); record.decidedBy = actor.userId; return { ...record }; }
  return { createProfile, getProfile, assign, applyLeave, decideLeave, listLeave: (staffId) => [...leave.values()].filter((item) => item.staffId === staffId).map((item) => ({ ...item })), assignments: () => assignments.map((item) => ({ ...item })), counts: () => ({ staff: staff.size, leave: leave.size }) };
}
