import { randomUUID } from 'node:crypto';

export const CORE_LEVELS = ['KG1', 'KG2', 'Primary 1', 'Primary 2', 'Primary 3', 'Primary 4', 'Primary 5', 'Primary 6', 'JHS 1', 'JHS 2', 'JHS 3'];
export const ADMISSION_STAGES = ['ENQUIRY', 'APPLICATION', 'DOCUMENT_REVIEW', 'ASSESSMENT_INTERVIEW', 'DECISION', 'ADMISSION_OFFER', 'ACCEPTANCE', 'REGISTRATION', 'FEE_ASSESSMENT', 'ENROLLMENT', 'STUDENT_ID', 'CLASS_ASSIGNMENT'];
const transitions = new Map(ADMISSION_STAGES.map((stage, index) => [stage, ADMISSION_STAGES[index + 1]]));

function nextNumber(prefix, collection) { return `${prefix}-${String(collection.size + 1).padStart(6, '0')}`; }
export function createStudentService({ now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight' } = {}) {
  const students = new Map(); const admissions = new Map(); const parentLinks = new Map(); const permanentIds = new Set(); const indexSequences = new Map();
  function nextIndex(year) { const key = String(year ?? new Date().getFullYear()).match(/^\d{4}/)?.[0] ?? String(new Date().getFullYear()); let next = (indexSequences.get(key) ?? 0) + 1; let candidate = `OSAAH/${key}/${String(next).padStart(4, '0')}`; while ([...students.values()].some((student) => student.schoolId === schoolId && student.permanentStudentId === candidate)) candidate = `OSAAH/${key}/${String(++next).padStart(4, '0')}`; indexSequences.set(key, next); permanentIds.add(candidate); return candidate; }
  function createStudent(input) { if (!input?.firstName || !input?.surname) throw new Error('First name and surname are required'); if ([...students.values()].some((student) => student.schoolId === schoolId && student.admissionNumber === input.admissionNumber)) throw new Error('Admission number already exists'); const id = `STD-${String(students.size + 1).padStart(6, '0')}`; const student = { id, schoolId, permanentStudentId: input.permanentStudentId ?? nextIndex(input.admissionYearId ?? input.year), admissionNumber: input.admissionNumber ?? nextNumber('ADM', students), indexNumber: input.indexNumber ?? null, firstName: input.firstName, middleName: input.middleName ?? null, surname: input.surname, preferredName: input.preferredName ?? null, gender: input.gender ?? null, dateOfBirth: input.dateOfBirth ?? null, placeOfBirth: input.placeOfBirth ?? null, nationality: input.nationality ?? 'Ghanaian', photograph: input.photograph ?? null, qrCode: `osaah:student:${id}`, classId: input.classId ?? null, streamId: input.streamId ?? null, houseId: input.houseId ?? null, admissionDate: input.admissionDate ?? null, previousSchool: input.previousSchool ?? null, admissionType: input.admissionType ?? null, family: input.family ?? [], health: input.health ?? null, documents: [], createdAt: now(), updatedAt: now(), history: [] }; students.set(id, student); if (student.classId) assignClass(id, { classId: student.classId, academicYearId: input.academicYearId ?? null, streamId: student.streamId }); return structured(student); }
  function assignClass(studentId, assignment) { const student = students.get(studentId); if (!student) throw new Error('Student not found'); student.classId = assignment.classId; student.streamId = assignment.streamId ?? student.streamId; student.history.push({ id: randomUUID(), studentId, classId: student.classId, streamId: student.streamId, academicYearId: assignment.academicYearId ?? null, reason: assignment.reason ?? 'CLASS_ASSIGNMENT', effectiveAt: now() }); student.updatedAt = now(); return structured(student); }
  function linkParent(studentId, parent) { if (!students.has(studentId)) throw new Error('Student not found'); const links = parentLinks.get(studentId) ?? []; if (!links.some((link) => link.parentId === parent.parentId)) links.push({ parentId: parent.parentId, relationship: parent.relationship ?? 'Guardian', telephone: parent.telephone ?? null }); parentLinks.set(studentId, links); return links.map((link) => ({ ...link })); }
  function search(query, { userId, roleKey, assignedStudentIds = [], parentPhones = [], requestedSchoolId = schoolId } = {}) { const term = String(query ?? '').trim().toLowerCase(); return [...students.values()].filter((student) => student.schoolId === requestedSchoolId && (roleKey === 'PROPRIETOR' || roleKey === 'HEADTEACHER' || roleKey === 'SCHOOL_ADMIN' || roleKey === 'ADMISSIONS_OFFICER' || assignedStudentIds.includes(student.id)) && (!term || [student.id, student.admissionNumber, student.firstName, student.middleName, student.surname, ...student.family.flatMap((contact) => [contact.telephone, contact.alternativePhone])].filter(Boolean).some((value) => String(value).toLowerCase().includes(term)))).map(structured); }
  function createAdmission(input) { const application = { applicationNumber: nextNumber('APP', admissions), schoolId, stage: 'ENQUIRY', applicant: { ...input }, documents: [], createdAt: now(), updatedAt: now() }; admissions.set(application.applicationNumber, application); return { ...application }; }
  function advanceAdmission(applicationNumber, stage) { const application = admissions.get(applicationNumber); if (!application) throw new Error('Application not found'); if (transitions.get(application.stage) !== stage) throw new Error(`Invalid admission transition from ${application.stage} to ${stage}`); application.stage = stage; application.updatedAt = now(); if (stage === 'ADMISSION_OFFER') application.admissionLetter = `ADMISSION-OFFER-${application.applicationNumber}`; if (stage === 'ENROLLMENT') application.enrollmentConfirmation = `ENROLLMENT-${application.applicationNumber}`; if (stage === 'STUDENT_ID' && !application.studentId) application.studentId = `STD-${String(students.size + 1).padStart(6, '0')}`; return { ...application }; }
  function listAdmissions() { return [...admissions.values()].map((application) => ({ ...application, applicant: { ...application.applicant } })); }
  function decideAdmission(applicationNumber, decision, year = new Date().getFullYear()) { const application = admissions.get(applicationNumber); if (!application || !['ACCEPTED', 'REJECTED'].includes(decision)) throw new Error('Invalid admission decision'); application.applicationStatus = decision; application.stage = 'DECISION'; application.updatedAt = now(); if (decision === 'ACCEPTED' && !application.permanentStudentId) { let index = permanentIds.size + 1; let id = `OSAAH/${year}/${String(index).padStart(4, '0')}`; while (permanentIds.has(id)) id = `OSAAH/${year}/${String(++index).padStart(4, '0')}`; permanentIds.add(id); application.permanentStudentId = id; } return { ...application }; }
  function getStudent(id, { allowHealth = false, requestedSchoolId = schoolId } = {}) { const student = students.get(id); if (!student || student.schoolId !== requestedSchoolId) return null; const result = structured(student); if (!allowHealth) delete result.health; return result; }
  function listStudents({ requestedSchoolId = schoolId } = {}) { return [...students.values()].filter((student) => student.schoolId === requestedSchoolId).map(structured); }
  return { createStudent, assignClass, linkParent, search, createAdmission, advanceAdmission, listAdmissions, decideAdmission, getStudent, listStudents, counts: () => ({ students: students.size, admissions: admissions.size }) };
}
function structured(student) { return JSON.parse(JSON.stringify(student)); }
