import { createHash, randomBytes, randomUUID } from 'node:crypto';
import PDFDocument from 'pdfkit';

const MANAGER_ROLES = new Set(['HEADTEACHER', 'ASSISTANT_HEADTEACHER', 'PROPRIETOR']);
const clone = (value) => JSON.parse(JSON.stringify(value));
const actorId = (actor) => actor?.id ?? actor?.userId ?? null;
const sha256 = (value) => createHash('sha256').update(String(value)).digest('hex');

export function createTranscriptService({ students, academicResults, signatures, now = () => new Date().toISOString(), schoolId = 'school-osaah-daylight', schoolProfile = {} } = {}) {
  const transcripts = new Map(); const versions = new Map(); let sequence = 0;
  const canManage = (actor) => actor?.schoolId === schoolId && (MANAGER_ROLES.has(actor.roleKey) || actor?.permissions?.has?.('*'));
  const studentFor = (id) => students?.getStudent?.(id, { requestedSchoolId: schoolId });
  const linked = (actor, student) => actor?.portal !== 'parent' ? true : (actor.children ?? []).some((child) => child.id === student?.id || child.permanentStudentId === student?.permanentStudentId);
  const published = (studentId, academicYear, term, actor) => {
    const manager = { ...actor, roleKey: 'HEADTEACHER', permissions: new Set(['*']), schoolId };
    const student = studentFor(studentId); if (!student) return null;
    const publication = academicResults?.publicationFor?.({ academicYear, term, classId: student.classId });
    if (!publication || publication.status !== 'PUBLISHED') return null;
    const block = academicResults?.blockFor?.({ studentId, academicYear, term, classId: student.classId });
    if (block?.status === 'BLOCKED') return null;
    return academicResults.result({ studentId, classId: student.classId, academicYear, term }, manager);
  };
  function snapshot(student, years, actor) {
    const academicYears = [...new Set((years ?? []).map(String))];
    const rows = [];
    for (const academicYear of academicYears) for (const term of ['TERM_1', 'TERM_2', 'TERM_3', 'First Term', 'Second Term', 'Third Term']) {
      const result = published(student.id, academicYear, term, actor); if (result) rows.push({ academicYear, term, classId: result.classId, result });
    }
    return { studentId: student.id, permanentStudentId: student.permanentStudentId, studentName: [student.firstName, student.middleName, student.surname].filter(Boolean).join(' '), academicYears, rows, generatedAt: now() };
  }
  function reference() { sequence += 1; return `OSAAH/TR/${new Date(now()).getFullYear()}/${String(sequence).padStart(6, '0')}`; }
  function generate(input, actor) { if (!canManage(actor)) throw new Error('Transcript generation requires authorized academic leadership.'); const student = students.findByPermanentStudentId(input.permanentStudentId, { roleKey: actor.roleKey, requestedSchoolId: schoolId }); if (!student) throw new Error('Student not found.'); const existing = [...transcripts.values()].find((item) => item.studentId === student.id); const transcript = existing ?? { id: randomUUID(), schoolId, studentId: student.id, transcriptReference: reference(), currentVersion: 0, status: 'DRAFT', generatedBy: actorId(actor), generatedAt: now(), publishedBy: null, publishedAt: null, createdAt: now(), updatedAt: now() }; const versionNumber = transcript.currentVersion + 1; const academicSnapshot = snapshot(student, input.academicYears ?? [input.academicYear].filter(Boolean), actor); const manifest = { ...academicSnapshot, transcriptReference: transcript.transcriptReference, version: versionNumber }; const checksum = sha256(JSON.stringify(manifest)); const token = randomBytes(32).toString('base64url'); const version = { id: randomUUID(), transcriptId: transcript.id, versionNumber, academicSnapshot: manifest, documentChecksum: checksum, verificationToken: token, verificationTokenHash: sha256(token), generatedBy: actorId(actor), generatedAt: now(), publishedBy: null, publishedAt: null, regenerationReason: input.regenerationReason ?? null, status: 'DRAFT', supersededByVersion: null, revokedBy: null, revokedAt: null, revocationReason: null }; transcripts.set(transcript.id, { ...transcript, currentVersion: versionNumber, generatedBy: actorId(actor), generatedAt: version.generatedAt, updatedAt: now() }); versions.set(version.id, version); return clone(publicView(transcripts.get(transcript.id), version)); }
  function publish(transcriptId, actor) { if (!canManage(actor)) throw new Error('Transcript publication requires authorized academic leadership.'); const transcript = transcripts.get(transcriptId); const version = [...versions.values()].find((item) => item.transcriptId === transcriptId && item.versionNumber === transcript?.currentVersion); if (!transcript || !version) throw new Error('Transcript not found.'); version.status = 'PUBLISHED'; version.publishedBy = actorId(actor); version.publishedAt = now(); transcript.status = 'PUBLISHED'; transcript.publishedBy = actorId(actor); transcript.publishedAt = version.publishedAt; transcript.updatedAt = now(); return clone(publicView(transcript, version)); }
  function revoke(transcriptId, reason, actor) { if (!canManage(actor)) throw new Error('Transcript revocation requires authorized academic leadership.'); const transcript = transcripts.get(transcriptId); if (!transcript) throw new Error('Transcript not found.'); const version = [...versions.values()].find((item) => item.transcriptId === transcriptId && item.versionNumber === transcript.currentVersion); if (!version || !String(reason ?? '').trim()) throw new Error('Revocation reason is required.'); version.status = 'REVOKED'; version.revokedBy = actorId(actor); version.revokedAt = now(); version.revocationReason = String(reason).trim(); transcript.status = 'REVOKED'; transcript.revokedBy = actorId(actor); transcript.revokedAt = version.revokedAt; transcript.revocationReason = version.revocationReason; return clone(publicView(transcript, version)); }
  function getForStudent(permanentStudentId, actor) { const student = students.listStudents({ requestedSchoolId: schoolId }).find((item) => item.permanentStudentId === permanentStudentId); if (!student || !linked(actor, student)) throw new Error('Forbidden.'); const transcript = [...transcripts.values()].find((item) => item.studentId === student.id); if (!transcript) return null; const valid = [...versions.values()].filter((item) => item.transcriptId === transcript.id && item.status === 'PUBLISHED').sort((a, b) => b.versionNumber - a.versionNumber)[0]; return valid ? clone(publicView(transcript, valid)) : null; }
  function verify(referenceValue, token) { const transcript = [...transcripts.values()].find((item) => item.transcriptReference === referenceValue); if (!transcript) return { status: 'NOT FOUND' }; const version = [...versions.values()].find((item) => item.transcriptId === transcript.id && (sha256(token ?? '') === item.verificationTokenHash || token === item.verificationToken)); if (!version) return { status: 'NOT FOUND' }; return { status: version.status === 'PUBLISHED' ? 'VALID' : version.status, schoolName: schoolProfile.name ?? 'OSAAH DAYLIGHT SCHOOL COMPLEX', studentName: version.academicSnapshot.studentName, permanentStudentId: version.academicSnapshot.permanentStudentId, transcriptReference: referenceValue, issueDate: version.publishedAt, version: version.versionNumber }; }
  function pdf(transcriptId, versionNumber, actor) { if (!(canManage(actor) || actor?.portal === 'parent')) throw new Error('Forbidden.'); const transcript = transcripts.get(transcriptId); const version = [...versions.values()].find((item) => item.transcriptId === transcriptId && item.versionNumber === Number(versionNumber)); if (!transcript || !version || (actor?.portal === 'parent' && !linked(actor, studentFor(transcript.studentId)))) throw new Error('Forbidden.'); const doc = new PDFDocument({ size: 'A4', margin: 48 }); const chunks = []; doc.on('data', (chunk) => chunks.push(chunk)); const done = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks)))); doc.fontSize(18).text(schoolProfile.name ?? 'OSAAH DAYLIGHT SCHOOL COMPLEX', { align: 'center' }).fontSize(14).text('OFFICIAL STUDENT ACADEMIC TRANSCRIPT', { align: 'center' }).moveDown(); doc.fontSize(10).text(`Transcript Reference: ${transcript.transcriptReference}/V${version.versionNumber}`); doc.text(`Student: ${version.academicSnapshot.studentName}`); doc.text(`Permanent Student ID: ${version.academicSnapshot.permanentStudentId}`); for (const row of version.academicSnapshot.rows) { doc.moveDown().fontSize(11).text(`${row.academicYear} — ${row.term} — ${row.classId}`); for (const subject of row.result.subjects ?? []) doc.fontSize(9).text(`${subject.subjectId}: CA ${subject.caScore} | Exam ${subject.examScore} | Total ${subject.totalScore} | ${subject.grade} — ${subject.remark}`); } doc.end(); return done.then((content) => ({ content, filename: `${transcript.transcriptReference}.pdf` })); }
  function publicView(transcript, version) { const { verificationTokenHash, ...safe } = version; return { ...transcript, version: safe, verificationToken: version.verificationToken }; }
  return { generate, publish, revoke, getForStudent, verify, pdf, list: (actor) => canManage(actor) ? [...transcripts.values()].map((item) => clone(item)) : [] };
}
